### ISSUE TITLE
Onboarding Erik Sundell (@consideRatio)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/team-compass#110]
Onboarding champion: `@<INSERT HANDLE>`
Person's name: `@consideratio`

# Onboarding checklist

Follow the checklist below to onboard a new team member!

**Accounts**

- [x] (if a 2i2c staff member) Make a `@2i2c.org` GMail account for them.
- [x] Add to [the proper GitHub team](https://github.com/orgs/2i2c-org/teams/2i2c-team)
- [x] Add to [the proper Slack group](https://2i2c.slack.com/admin/user_groups)
- [x] Add them to the proper Google group in our Google Admin space.

**Communication**

- [x] Send them a link to the [Getting started docs](https://team-compass.2i2c.org/en/latest/get-started.html)
- [x] Send them a link to the [2i2c Google Drive](https://drive.google.com/drive/folders/1ABxxSFycGfCzQc9czfwer_dat-GVi4jw?usp=sharing)
- [ ] Schedule an onboarding meeting for after they've read through the docs
  Here is a link to [schedule a chat](https://calendar.google.com/calendar/u/0/selfsched?sstoken=UUdEcnN2bHdZTUExfGRlZmF1bHR8Njc3ODg2NWJjOTIzMTkxYjc5MDZlODAzN2QzYzUzZDE) but if I'm around on slack I'd love to just jump into a call.

**Permissions**

- [ ] Add to appropriate Google Cloud projects
- [ ] Add to appropriate AWS projects
- [ ] Add to appropriate Azure projects
- [x] Add to the [auth0 2i2c tenant](https://manage.auth0.com/dashboard/us/2i2c/tenant/admins)
- [ ] NameCheap administration privileges to `2i2c.org` and `2i2c.cloud`

**External**

- [x] Add to [2i2c website](https://2i2c.org/about/)
- [ ] Tweet about their arrival!

**Wrap up**

- [ ] Have an onboarding session with the onboarding champion
- [ ] Announce in the `#general` Slack channel about our new team member
- [ ] Celebrate, they are now onboarded! 🎉

**Comment by consideRatio** [comment]
@2i2c-org/tech-team we also use quay.io for pushing docker images and I find myself being in use of such credentials now to push a tag of our custom `k8s-hub` image that adds the yuvipanda/jupyterhub-configurator Python package.

I'm `consideratio-2i2c` with an account associated with my 2i2c email, and I'm `consideratio` with an account associated with my GitHub ID on quay.io now.

**Comment by yuvipanda** [comment]
Ah, ty @consideRatio. It makes sense to move the configurator to its own deployment probably? I'll take a shot at it later.

**Comment by choldgraf** [comment]
I think that we can close this one, since @consideRatio has been working with the team for some time now! If there is something specific we need to follow-up on, maybe we can tackle that in a new issue?
