### ISSUE TITLE
Create a tech-team in the 2i2c-org on GitHub

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/team-compass#113]
# Summary

I wanted to ping the `@tech-team` equivalent on slack but on github from https://github.com/jupyterhub/jupyterhub/issues/3490, but I found that the 2i2c-org on GitHub didn't have a team to represent that so I ended up pinging only @yuvipanda.

Do we have agreement to create a `@2i2c-org/tech-team` on GitHub to help users ping us as a group on GitHub?

# Actions

- [ ] See if we have agreement to create and maintain a tech-team list in the 2i2c-org on GitHub
- [ ] Update documentation for example in the onboarding section to add the new team member to the GitHub org team
- [ ] Create such GitHub team and add current team members

**Comment by choldgraf** [comment]
There is: @2i2c-org/tech-team 

I wonder if you missed it somehow?

**Comment by consideRatio** [comment]
oooh :D missed it somehow
