### ISSUE TITLE
Materials / strategy for the Berkeley Education National Workshop

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#115]
# Summary

Berkeley holds a national workshop for the DSEP program each year. They'd like us to give some kind of "Jupyter / infrastructure overview" talk (which we've given in previous years), and potentially it's an opportunity for us to run hub infrastructure for the workshop off of the CloudBank credits.

The workshop is **June 14-18th**. [Here's the website](https://data.berkeley.edu/academics/resources/data-science-education-resources/2021-national-workshop-data-science-education)

# Ways we can engage

_these ideas came up after a conversation with @ericvd-ucb_

**Run the DSEP infrastructure**. There is a JupyterHub that the workshop uses to do demonstrations, learning, etc. We can run this on the `*.cloudbank.2i2c.cloud` domain, and they're happy to give a shout-out that it is running on 2i2c infrastructure. Doing this will entail:

- [x] Decide what kind of infrastructure we'll use for the workshop (e.g., `demo.cloudbank.2i2c.cloud` or a dedicated hub)
- [x] Make sure the hub is up-and-running
- [x] Have Eric's team run through the onboarding instructions for this hub to make sure it works.

**Thursday, June 17th: Panel discussion on Thursday**. There will be a panel discussion on Thursday with multiple vendors. 2i2c will be one of them. I'm going to attend, and give a 15 minute overview about 2i2c, followed by participating in the discussion itself. Doing this will entail:

- [x] Create a ~15 minute presentation about 2i2c
- [x] Attend the panel

**Wednesday the 16th and Thursday the 17th: 2i2c booth**. There will be two "open booth" sessions on Wednesday and Thursday afternoon, where vendors can join and talk about their tools and services. We can be one of these vendors if we wish. Doing this will entail the following things:

- [x] Create a 4 minute "demo reel" about 2i2c services
- [x] Maybe turn this into a video that can loop when we're not there
- [x] Get somebody to agree to pay attention to our booth for a few hours each of those days (I think this just means keeping an eye on a zoom room and chatting with whoever shows up)

# Our strategy around offering hub services

There are two kinds of organizations present:

- **Community colleges in California and HBCUs**: These groups are covered by the CloudBank grant and @sean-morris's time, and so we can offer 2i2c hubs to any organization that fits these categories, running on CloudBank credits.
- **Other universities / CCs / etc**: For all other organizations, we need to determine a strategy for what we'll offer them. For example, do we offer hubs free-of-charge if they are under a certain size? Do we create one big hub for them to use for free? Do we treat them the same as any other customer?

# Next steps

- [x] Decide on what we'll do for this workshop
- [x] Coordinate with Eric / DSUS people to know what they need
- [x] Figure out what time they'd like us to talk
- [x] Create a plan for what we'll offer to non-cloudbank organizations
- [x] Finish to-do items above

**Comment by ericvd-ucb** [comment]
I think @sean-morris is all over the demo hub and will tend to that
I think the 15 min deck - we can help you with if you like/need
I think similarly the 4 min reel is a great thing
Here is a nice example from CourseKata https://youtu.be/VgVmkZrJpgE

**Comment by choldgraf** [comment]
I believe that we've now covered all of these items - we used the cloudbank jupyterhub for our interactive computing sessions, and I just gave the 2i2c panel discussion talk, so I think we're done for this year! @ericvd-ucb does that sound right?
