### ISSUE TITLE
Onboarding Sarah G.

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#116]
Onboarding champion: @damianavila 
Onboarding champion sidekick: @consideRatio
Person's name: Sarah Gibson (@sgibson91)

# Onboarding checklist

Follow the checklist below to onboard a new team member!

**Accounts**

- [x] (if a 2i2c staff member) Make a `@2i2c.org` GMail account for them.
- [x] Add to [the proper GitHub team](https://github.com/orgs/2i2c-org/teams/2i2c-team)
- [x] Add to [the proper Slack group](https://2i2c.slack.com/admin/user_groups)
- [x] Add them to the proper Google group in our Google Admin space.

**Communication**

- [x] Send them a link to the [Getting started docs](https://team-compass.2i2c.org/en/latest/get-started.html)
- [x] Send them a link to the [2i2c Google Drive](https://drive.google.com/drive/folders/1ABxxSFycGfCzQc9czfwer_dat-GVi4jw?usp=sharing)
- [x] Schedule an onboarding meeting for after they've read through the docs

**Permissions**

- [x] Add to appropriate Google Cloud projects
- ~Add to appropriate AWS projects~ See: https://github.com/2i2c-org/pilot-hubs/issues/475
- ~Add to appropriate Azure projects~ See: https://github.com/2i2c-org/pilot-hubs/issues/475
- [x] Add to the [auth0 2i2c tenant](https://manage.auth0.com/dashboard/us/2i2c/tenant/admins)
- [x] Add to [quay.io 2i2c team](https://quay.io/organization/2i2c/teams/owners)
- [x] NameCheap administration privileges to `2i2c.org` and `2i2c.cloud`
- [x] Username/password for Grafana dashboards
- [x] Monday.com login

**External**

- [x] Add to [2i2c website](https://2i2c.org/about/)
- [x] Tweet about their arrival!

**Wrap up**

- [x] Have an onboarding session with the onboarding champion
- [x] Announce in the `#general` Slack channel about our new team member
- [x] Celebrate, they are now onboarded! 🎉

**Comment by sgibson91** [comment]
Hey 👋🏻 I've been reading through docs and have added grafana and monday.com to list of permissions I might need

**Comment by sgibson91** [comment]
My quay.io account is here (linked to my GitHub, so same handle) https://quay.io/user/sgibson91

**Comment by damianavila** [comment]
We met with @sgibson91 (really nice talk!) to talk a little bit about the onboarding process and update the list of items.
I recommended looking at our project boards and the pilot and pilot-hub docs before jumping into our main repo.

I will be working on getting her all the missing accounts and permissions.
We will meet again by EOW to see how the onboarding process went (and we will slack during the week in case she needs any help).

**Comment by damianavila** [comment]
@sgibson91, can you confirm you have access to the [2i2c gdrive](https://drive.google.com/drive/folders/1ABxxSFycGfCzQc9czfwer_dat-GVi4jw?usp=sharing)?

**Comment by damianavila** [comment]
Btw, I asked @choldgraf to create and set up the google related accounts. Thanks, Chris!

**Comment by sgibson91** [comment]
> @sgibson91, can you confirm you have access to the [2i2c gdrive](https://drive.google.com/drive/folders/1ABxxSFycGfCzQc9czfwer_dat-GVi4jw?usp=sharing)?

Confirmed, I have access!

**Comment by yuvipanda** [comment]
@sgibson91 I've invited you to the two gcp projects we have control over outside the 2i2c org (meom-ige-cnrs and cb-1003-1696). I've also added you as a [billing administrator](https://admin.google.com/ac/groups/01jlao463o1t8e2/members) to the 2i2c org, so you *should* have access to all the GCP projects under the 2i2c org - can you verify/

**Comment by sgibson91** [comment]
@yuvipanda I think I can only see the 2 projects you explicitly invited me too - I'm not sure I have the right access to Google Admin for the billing stuff to show up?

**Comment by consideRatio** [comment]
From mobile: 2FA setup is an action point as well, right?

**Comment by sgibson91** [comment]
@consideRatio it wasn't an explicit action point in this issue, but it has been done! It was enforced in the Google Workspace, which meant that I couldn't sign in to my account for this first time! 😱 @choldgraf edited the settings to allow new accounts a 2 weeks grace period to set up 2FA before being locked out.

**Comment by choldgraf** [comment]
I've added Sarah to the tech team in Google workspaces (this is the same group of people as the @2i2c-org/tech-team and the Slack tech-team group)

**Comment by damianavila** [comment]
Thanks, @yuvipanda and @choldgraf for your help here, let's continue ticking stuff...

**Comment by damianavila** [comment]
Asked @choldgraf for Monday access.

**Comment by damianavila** [comment]
@yuvipanda do you have more details about the grafana access?
I realized I do not have access to that one either 🤦

**Comment by damianavila** [comment]
Asked @colliand to set up access for Namecheap.

**Comment by damianavila** [comment]
Sent Auth0 invite, @sgibson91 please confirm when you are in.

**Comment by damianavila** [comment]
Sent quay invite as well, please confirm again when you are in.

**Comment by sgibson91** [comment]
Yep, I think I'm in both Auth0 and quay.io!

**Comment by yuvipanda** [comment]
@sgibson91 @damianavila https://github.com/2i2c-org/pilot-hubs/pull/456 is basically setting up our first usable grafana :D It's WIP, but you can get the password with sops from `support/secrets.yaml` there. Grafana empty tho

**Comment by sgibson91** [comment]
NameCheap access granted!

**Comment by damianavila** [comment]
>  2i2c-org/pilot-hubs#456 is basically setting up our first usable grafana :D 

I knew I recently read about this one... 
I even left comments there 🤦

**Comment by damianavila** [comment]
@2i2c-org/tech-team, our AWS access is currently a little bit disperse... thinking about putting all the access keys in some encrypted file in the repo, thoughts?
Btw, the Azure story is not clear to me neither... can somebody drop some lights there :wink:

**Comment by damianavila** [comment]
@sgibson91, you should have access to Monday (remember most of the stuff there is out of date by now).

**Comment by damianavila** [comment]
@choldgraf, who is doing the twitter ANN?

**Comment by damianavila** [comment]
> @2i2c-org/tech-team, our AWS access is currently a little bit disperse... thinking about putting all the access keys in some encrypted file in the repo, thoughts?
> Btw, the Azure story is not clear to me neither... can somebody drop some lights there 😉

Created a specific ticket for this one to boost this discussion: https://github.com/2i2c-org/pilot-hubs/issues/475
In the meantime, if @sgibson91 needs any AWS  credentials I may have, I will directly provide them.

**Comment by damianavila** [comment]
Met with @sgibson91 to check missing points, we are pretty close to being done here.

**Comment by sgibson91** [comment]
One last task? 😁 

- [ ] Add me to https://whena.re/2i2c-engineering-team

**Comment by choldgraf** [comment]
@sgibson91 done! https://whena.re/2i2c-engineering-team

I will post a tweet about it today! I'm not sure how to properly share twitter accounts so until we figure that out 😬

**Comment by sgibson91** [comment]
I think TweetDeck has a Teams feature that let's multiple people tweet from a single account without sharing the password https://help.twitter.com/en/using-twitter/tweetdeck-teams

**Comment by choldgraf** [comment]
TIL that tweetdeck still exists haha...I thought Twitter had shuttered it for some reason!

**Comment by choldgraf** [comment]
https://twitter.com/2i2c_org/status/1405919374276390917 :-)

**Comment by choldgraf** [comment]
(I may or may not have also created a party parrot for Sarah, as an unofficial extra onboarding step ;-) )

I believe that we are done?!? Does that mean we can celebrate Sarah's onboarding as complete?!

**Comment by damianavila** [comment]
Yep, let's celebrate :tada: and close this one!!!

**Comment by damianavila** [comment]
Btw, critics of the process and the champion (bad luck you had getting this one :wink: ) are more than welcome to improve the onboarding. Drop them here or create specific issues @sgibson91.
