### ISSUE TITLE
Questions to ask others interested in 2i2c infra

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#12]
# Background

When we're talking to someone interested in a hub, their needs and use-case have a big impact on the kind of hub that might be of use. In particular, they may:

- Need an event-based hub
- Need a research-focused hub
- Need an education-focused hub
- Just want access to interactive computing, not their own hub
- Not be a good fit for this kind of infrastructure at all

# Working draft

I've got a [working draft of questions to iterate on](https://docs.google.com/forms/d/1KHw-4Wdyoofv-6CENeiOSbnC62LKdx55QTcZmXQVkkc/edit). Can folks provide comments and thoughts there?

# To Do

- brainstorm a list of questions to ask
- determine how we'll ask these questions (e.g., a Google Form)
- define a checklist of things to do for any new hub engagement (one step of which should be "send this form")
- add it to the handbook (e.g., in a section on sales/partnership onboarding)

**Comment by choldgraf** [comment]
Two other things we need to know:

- What kind of skills does their team have? Are they python-proficient? Excel people? Do they need a big up-skill in order to be effective?
- If they need to *apply* for funding to be able to run this, what is their timeline?

**Comment by choldgraf** [comment]
I've got a draft google form here:

https://docs.google.com/forms/d/1KHw-4Wdyoofv-6CENeiOSbnC62LKdx55QTcZmXQVkkc/edit

@yuvipanda do you wanna give it a look and provide any thoughts? Then I can start sending this form to people that are interested in hubs. We may wanna merge this with the form that you put together specifically for events, I haven't taken a close pass at that one yet to see if I am duplicating some questions.

**Comment by yuvipanda** [comment]
@choldgraf wow, that is a good form!!! 

I'm trying to think through the cost/benefit of having one form that's big (5pages) vs multiple smaller forms. I think this form captures all the information we need, but I wonder if it is big will dissuade people from filling it. But maybe that doesn't matter to us right now, and it's better to get all this info from the get-go rather than painstakingly via email. Curious to hear what your thoughts are.

I found the "What kind of resources do you estimate needing per student (RAM, CPU, and Disk space)" question a bit confusing since google forms cuts out the most important part! Otherwise, I think this is a great framing.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/30430/102904723-21ef9800-4498-11eb-95db-65a6718a8e64.png">

Is there someone we can user-test this form on? That would help sharpen it. However, I don't think we need that before we start sending this to people.

**Comment by choldgraf** [comment]
Good points about length and sharpening it up. We're already in contact with a few folks that are interested in hubs, so perhaps they can be beta-testers of this form in addition to filling it out themselves. I bet they'd be willing to give feedback.

Ah I didn't realize that the words got cut off on the multiple choice section...lemme try to make it shorter

**Comment by yuvipanda** [comment]
What kinda funnel do you envision after this form? Who responds to folks? Or is this something we send to people in response to them contacting us? I guess we'll figure that out as we go too.

**Comment by yuvipanda** [comment]
> I bet they'd be willing to give feedback.

Yes, that would be great!

**Comment by choldgraf** [comment]
For now it is just a way to give them structured questions that we know are useful for us. After that, I think we can use the answers to build an estimated budget from them from one of the [template hub budgets](https://docs.google.com/spreadsheets/d/10Gxufgmiuhq2Up69a6NdQoRs0xgKOi1Jts66wwiqF50/edit). And more generally it should hopefully clarify whether they are in-scope and what kind of hub they'd need. Does that make sense?

That said, I think we should definitely define a more structured way to decide if / how to engage with them in the near future...this is just a first step. Do you have any thoughts on a good process to deciding to engage?

**Comment by choldgraf** [comment]
OK I've cut it down to 3 longer sections instead of 5 shorter ones, since some were *super* short and had sort-of overlapping content. Hopefully that makes it a bit more streamlined.

**Comment by yuvipanda** [comment]
I like it! Thanks for sharpening & shortening it.

> Do you require a URL for your hub that you define? If so, list it below.

We shouldn't have this. Hub URLs are the thing people bikeshed the most about, so I always try to steer the conversation away from it. It's trivial to make this be whatever, so let's not bring it up so early.

> Any particular concerns that you have about using the infrastructure?

adding a description with prompts might be useful. Not entirely sure what would go in here.

> Do you need any of these specific workflows? (check any you need)

Should this have an  'other' field? Common ones seem to be access to relational databases, but not sure if that's explicitly worth adding here.

**Comment by choldgraf** [comment]
Nice - OK will remove the "url for your hub" question.

re: concerns question - I was trying to get a feel for where is their hesitation for using this kind of infrastructure setup. Maybe instead we should focus this question on any "unique infrastructure needs" they think they have? (and maybe we can capture that with the "other" field in the "specific workflows" question?)

**Comment by yuvipanda** [comment]
> Maybe instead we should focus this question on any "unique infrastructure needs" they think they have? (and maybe we can capture that with the "other" field in the "specific workflows" question?)

That sounds great to me.

**Comment by choldgraf** [comment]
I've updated the questionnare w/ this new question 👍

**Comment by yuvipanda** [comment]
ok, this LGTM from me! <3

Wish this could be version controlled so we can learn as we go :cry:

**Comment by choldgraf** [comment]
ya I agree - maybe we can figure out a different system over time. For now, I'll send this to a few collaborators and see what they think about it :-)

**Comment by choldgraf** [comment]
After getting a response from the Texas Tech team, I added a few extra questions in there that I think are relevant:

- One about whether they have budget now, or need budget in the future
- A more explicit question about what their budget is
- An explicit question about expected cloud storage they need
- A question about whether they have their own cloud resources they can utilize outside of the budget in this contract (e.g. credits etc)

**Comment by choldgraf** [comment]
Closing this since we now have a set of questions that work well enough. We should update it as we begin taking in new clients

**Comment by damianavila** [comment]
@choldgraf where those questions are saved? I see several links above but I am not sure which one is the relevant one. Thanks!!

**Comment by choldgraf** [comment]
@damianavila The first link in the top comment (a Google form called  "help us understand your use case") is the one

**Comment by damianavila** [comment]
Thanks for the additional info!!
