### ISSUE TITLE
Have a kick-off meeting for the Pangeo collaboration

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#121]
# Summary

Now that @sgibson91 is onboarding with 2i2c, we should make some time to discuss potential first steps, as well as a general plan, for working with @rabernat and the Pangeo community. Can we find a time for at least the three of us to meet and brainstorm next steps? Ideally others on the @2i2c-org/tech-team could join as well.

I propose that we carve out an hour for this first meeting, unless @rabernat suspects that scheduling meetings in general will be challenge, in which case we could try to make this a longer meeting (e.g., 2-3 hours?) and cover more territory.

- [**Here's a when2meet**](https://www.when2meet.com/?12119683-zyQr5) to find a time when we can meet in either case. 

# Actions

- [x] Fill out when2meet above
- [x] Decide on the length of meeting
- [x] Decide on a day/time for the meeting
- [x] Create an agenda
- [x] Have the meeting
- [x] Write up notes and next steps

**Comment by rabernat** [comment]
Done. Unfortunately my schedule is very booked up already this week, as next week I am leaving for Italy. I may have some availability next week but can't really commit right now. So hopefully the Friday window will work.

**Comment by sgibson91** [comment]
Also, done - Friday is good for me

**Comment by damianavila** [comment]
It seems there is some consolidation around Fri at 14:00 UTC.

**Comment by choldgraf** [comment]
Hey all - let's shoot for [10am Pacific time](https://time.is/compare/1000am_18_June_2021_in_Berkeley). I've created a Google calendar and invited everybody that responded in the when2meet.

I've carved out 2 hours, though expect that some folks will be in-and-out during that time. @rabernat it might be helpful to have some overview of the Pangeo infrastructure setup (or other general information that would help @sgibson91 @damianavila and the team get oriented). What do you think?

Others - is there any particular agenda you'd have in mind? Otherwise we can try to pick out important topics to discuss within the meeting.

**Comment by choldgraf** [comment]
closing as we've had this meeting and I wrote ups some notes here:

https://discourse.pangeo.io/t/notes-from-the-pangeo-2i2c-kick-off-meeting/1587/4
