### ISSUE TITLE
Identify improvements to our onboarding docs

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#123]
# Summary

Now that we've onboarded @sgibson91 in #116 , this is a good opportunity to identify any updates that are needed to the process. Here are a few suggested steps we could take:

# Actions

- [x] Look for comments that showed any accounts we needed to provide access to but weren't in the issue template
- [x] Look for confusion around "how to do step XXX" and document it
- [x] Create issues for things to finish in the future
- [x] Finish up any documentation changes that we can make quickly

# Issues opened

- #102 
- https://github.com/2i2c-org/team-compass/issues/126
- https://github.com/2i2c-org/pilot-hubs/issues/476
- https://github.com/2i2c-org/team-compass/issues/127
- https://github.com/2i2c-org/team-compass/issues/128
- https://github.com/2i2c-org/team-compass/issues/129
- https://github.com/2i2c-org/team-compass/issues/130
- https://github.com/2i2c-org/team-compass/issues/133

**Comment by sgibson91** [comment]
Some ideas from me

- The Google group to be added to in order to see all the GCP projects was `gcp-organization-admins`, rather than `gcp-billing-admins`. Thanks to @yuvipanda for debugging that one!
- I'd like a "How to do practice deploys" reference. Is there a "safe space" project I can deploy to where it doesn't matter if I mess up? (i.e. separated from production hubs)
- There's a "how to add a hub" guide, but no "how to add a cluster" guide, which should be accompanied with a "when it's appropriate to add a new cluster" discussion as I imagine we'd like to keep clusters to a minimum but sometimes it's needed. E.g. I'm wondering if Pangeo will involve setting up a new cluster? If so, that'll be a good opportunity to draft the guide
  - Could also be accompanied by a "new cluster" issue template/checklist in pilot-hubs repo
- I also opened https://github.com/2i2c-org/pilot-hubs/issues/476 which is relevant to this discussion

**Comment by damianavila** [comment]
> I'd like a "How to do practice deploys" reference. Is there a "safe space" project I can deploy to where it doesn't matter if I mess up? (i.e. separated from production hubs)

There is a related issue where I asked about some 2i2c AWS playground: https://github.com/2i2c-org/team-compass/issues/102

>There's a "how to add a hub" guide, but no "how to add a cluster" guide, which should be accompanied with a "when it's appropriate to add a new cluster" discussion as I imagine we'd like to keep clusters to a minimum but sometimes it's needed. E.g. I'm wondering if Pangeo will involve setting up a new cluster? If so, that'll be a good opportunity to draft the guide

Both are great points!
Btw, a preexisting issue that may contain other points to improve as well: https://github.com/2i2c-org/pilot-hubs/issues/351

**Comment by sgibson91** [comment]
> There is a related issue where I asked about some 2i2c AWS playground: #102

Ah cool! I think a similar project in GCP would be good as well, since it's 2i2c's preferred platform :)

**Comment by choldgraf** [comment]
For "sandboxes" - is that just a matter of creating a project that is separate from our pilot hubs and then documenting these projects as safe spaces? That sounds like a good idea to me as well.

**Comment by sgibson91** [comment]
I think so, yes. I think the local deployment instructions detail how to just update one hub on a specific cluster, so point to those docs and then that should be a totally separate deployment.

**Comment by choldgraf** [comment]
Cool - see my latest comment in #102 , would anybody be willing to help me set up a project on AWS connected to my CC that we can use to run the infrastructure until we find a longer-term way to pay for it?

**Comment by choldgraf** [comment]
hey @sgibson91 - you mentioned this:

> The Google group to be added to in order to see all the GCP projects was gcp-organization-admins, rather than gcp-billing-admins.

but I'm having a hard time figuring out where the documentation was that suggested `gcp-billing-admins`. Could you point me there so that we can change this?

**Comment by sgibson91** [comment]
@choldgraf I did a quick, org-wide search and the only instance I can find is in the [org-ops](https://github.com/2i2c-org/org-ops) repo which mentions needing access to gcp-billing-admins to use that repo. So I suggest that it's actually not documented. We worked this out on Slack.

**Comment by choldgraf** [comment]
ahhh gotcha thanks :-)

**Comment by choldgraf** [comment]
OK I've created an issue for documenting how to provide GCP access: https://github.com/2i2c-org/team-compass/issues/133

can we close this one and follow up in the new issues?

**Comment by choldgraf** [comment]
closing this issue since I think it's addressed, feel free to re-open if there's something else to discuss! 🎉
