### ISSUE TITLE
Document how to provide GCP access

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#133]
# Summary

In #116 we discovered that instructions for getting access to the 2i2c Google Cloud projects was not clear and there were some uncertain steps such as knowing that the correct group for GCP access was `gcp-billing-admins`.

We should have a clearly-documented place for how to add a new 2i2c team member to our Google Cloud Projects, including permissions or groups that needed to be explicitly added.

# Information

We also have the [org-ops repository](https://github.com/2i2c-org/org-ops) that contains some infrastructure information around this, but it's unclear whether that is the right place for this information or not. Perhaps the @2i2c-org/tech-team can discuss and decide on where we should store this.

# Tasks to complete

- [ ] Decide where we would like this information to exist
- [ ] Create the proper docs so a new person could be onboarded in a straightforward fashion

**Comment by damianavila** [comment]
There is some documentation about the org-ops repository here: https://pilot-hubs.2i2c.org/en/latest/howto/operate/setup-new-project.html
I think that should be the place to drop this info for now, maybe?

**Comment by sgibson91** [comment]
Also note that the required role is "owner" rather than "organisation admin". See https://github.com/2i2c-org/pilot-hubs/pull/489#issuecomment-872209538 and the following comment for context.

**Comment by yuvipanda** [comment]
I changed the role for  gcp-organization-admins@2i2c.org to 'Owner' in the 2i2c organization at https://console.cloud.google.com/iam-admin/iam?folder=&organizationId=184174754493. So hopefully it should apply to all users added to that role now.

**Comment by damianavila** [comment]
> So hopefully it should apply to all users added to that role now.

I can see Pangeo stuff on that link so I guess this is confirmed, maybe?

**Comment by yuvipanda** [comment]
@damianavila I think so!

**Comment by yuvipanda** [comment]
@damianavila hmm, actually I'm not sure - The pangeo project is not in the same organization, so it shouldn't matter. Can you tell me what you see?
