### ISSUE TITLE
Set up a GCP sandbox project/space for our use

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#137]
I believe that I have added this sandbox project, and added the @2i2c-org/tech-team as "owners" on the project. It is called `two-eye-two-see-sandbox`. Could others confirm that they have access? Or let me know if you don't and I can add individuals directly?

**Comment by sgibson91** [comment]
:+1: I have access!

**Comment by yuvipanda** [comment]
Can confirm access!

**Comment by choldgraf** [comment]
ok cool - with two confirmations, I'll assume others have access to because I added everyone the same way :-)

**Comment by damianavila** [comment]
Belated confirmation, I can see the project!
