### ISSUE TITLE
@2i2c-org/tech-team gets credentials to AWS sandbox and confirms they have access

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#138]
See https://github.com/2i2c-org/team-compass/issues/102#issuecomment-868762889 for instructions!

I've assigned everyone that might be deploying on this infrastructure (most of the @2i2c-org/tech-team) - feel free to unassign when you've confirmed that you've got the AWS credentials figured out

**Comment by choldgraf** [comment]
Can @damianavila and @GeorgianaElena confirm that they have access?

**Comment by GeorgianaElena** [comment]
Yes :key:

**Comment by damianavila** [comment]
Yes 🗝️

**Comment by choldgraf** [comment]
yahoo!
