### ISSUE TITLE
Review slides that show off hub components + operations

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#147]
As a part of https://github.com/2i2c-org/meta/issues/211 I also needed to make a couple of slides that explain how 2i2c hubs work, what kind of components are in them, and the "roles" that people fill for the hubs.

There are two hub diagrams - one for an educational hub, one for a "scalable computing" hub. There is also a diagram showing off billing options and "roles" for a hub.
 
Would love feedback from the @2i2c-org/tech-team here:

https://docs.google.com/presentation/d/1kqrviwVOoZfey_rujhIasdkKZmlYgxV-1J2AG-nr3VY/edit?usp=sharing

I'll leave this open for a few days in case others have thoughts!

# Actions

- [x] Agree on language for roles in #152 
- [x] Modify these slides as needed
- [x] Done! 🎉

**Comment by sgibson91** [comment]
Love the roles slide! It sorts out some stuff I've had in my head about this sort of thing. Just a couple of notes:

- What sort of guidance is the Community Lead giving the Community Champion? I think I'm still a bit unclear on the difference between those roles and why it's important to the Lead, especially as they are visually separated from the users in the slide. Do you expect this relationship to change in the education vs research scenarios?
- I have notes from my onboarding week spent reading the docs written down that mention a few other roles: Hub Operators, Hub Architects and Hub Administrators. I think Hub Admins are synonymous with the Community Champion. Do the other terms map onto the roles in this slide? Once you're happy with the slide, it would be great to get it in the docs and make our language consistent 🙌🏻

**Comment by choldgraf** [comment]
@sgibson91 this is great feedback, thanks. A few thoughts below

> What sort of guidance is the Community Lead giving the Community Champion? 

Good question, I added the second role because many hubs might have two different people acting as the "main contact point" and the "decision-maker for the hub". But in many cases I think this is actually the same person. Do you think it's confusing to have both there?

> it would be great to get it in the docs and make our language consistent

Good point - for the mappings that I think are correct:

- Hub Admin == Community Champion (what if we called this Community Representative ?)
- Hub Engineer == Hub Operator
- Hub Architect isn't displayed in the diagram. It was originally intended to separate the role of people like @yuvipanda who designed the hub infra, from non-2i2c people that might serve as engineers. I'm not sure whether that's an important distinction to keep or not...

**Comment by sgibson91** [comment]
> Do you think it's confusing to have both there?

Yeah, a little bit. Perhaps just make it clear that the Community Champion hat can be worn by many people, possibly on a rotating basis? So long as only one person is performing admin tasks on the hub (to avoid conflicts).

> * Hub Admin == Community Champion (what if we called this Community Representative ?)

I think either term could work here as it's essentially someone to represent the needs of the users

> * Hub Admin == Community Champion (what if we called this Community Representative ?)
> * Hub Engineer == Hub Operator

These make sense and I'm happy with them

> * Hub Architect isn't displayed in the diagram. It was originally intended to separate the role of people like @yuvipanda who designed the hub infra, from non-2i2c people that might serve as engineers. I'm not sure whether that's an important distinction to keep or not...

Hmmm, yeah. That feels a little fuzzy right now and might become more well defined if/when we cross the bridge of "training folk to be their own engineers".

**Comment by choldgraf** [comment]
> Perhaps just make it clear that the Community Champion hat can be worn by many people, possibly on a rotating basis? 

I'm kinda leaning towards just removing the "Community Lead" from the picture, since I think for most communities, they'll decide how they want to govern the hub, but the important bit is that the Community Champion / Representative is the person that is the main 2i2c contact.

To that point, maybe we could add a little "cluster" of "Hub Admins" underneath the Community Representative? That way we can convey that more than 1 person can be a Hub Admin, but only 1 person can be the Community Representative at once.

> These make sense and I'm happy with them

All 4 names? I thought we wanted to just pick one of (hub admin // community champion) and (hub engineer // hub operator).

**Comment by sgibson91** [comment]
> I'm kinda leaning towards just removing the "Community Lead" from the picture, since I think for most communities, they'll decide how they want to govern the hub, but the important bit is that the Community Champion / Representative is the person that is the main 2i2c contact.

Yes, I like this. I think folk will like that they'll have some autonomy over how they organise and it's not crucial to 2i2c operations.

> To that point, maybe we could add a little "cluster" of "Hub Admins" underneath the Community Representative? That way we can convey that more than 1 person can be a Hub Admin, but only 1 person can be the Community Representative at once.

:+1:

> All 4 names?

Sorry, the mappings 😄 Though from the previous comment, sounds like we'll have one Community Champion and many Hub Admins. Hub Engineer more closely maps to 2i2c's current job titles, but I'm not taking a super strong stance on that.

**Comment by damianavila** [comment]
> but the important bit is that the Community Champion / Representative is the person that is the main 2i2c contact.

💯  and I think reducing that figure to just one will enforce that idea.

In general, I like the slides. They probably need some formatting love :wink: but the content is OK.

**Comment by choldgraf** [comment]
ok I've updated the slides per feedback from you all! I'm gonna close this one and we can track the hub role terminology in https://github.com/2i2c-org/team-compass/issues/152 since I don't think that should be a strict blocker for this one to be done :-)
