### ISSUE TITLE
Decide whether "Hub Community" is an acceptable drop-in for "customer" or "client"

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#153]
See https://github.com/2i2c-org/team-compass/issues/152 for context

What do people think about using "Hub Community" or short-hand "Community" instead of "Customer" or "Client".

My rationale here is that we are "in between" a SaaS platform and a consultancy, with a strong community+pro-social focus. As such, neither "customer" or "client" feel right to me. This is a stab at something that aligns more with the mission focus of 2i2c.

Examples of sentences where this would be used:

- We have a hub community that requested XXX feature.
- We have a potential community that wishes to have a new hub.

**Comment by yuvipanda** [comment]
I like it!

**Comment by damianavila** [comment]
> short-hand "Community"

Just "Community" makes sense to me.

**Comment by choldgraf** [comment]
thanks all for the feedback - let's go with "Hub Community" and "Community" then :-)
