### ISSUE TITLE
Team Meeting: August 2021

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#163]
This is a planning issue for our next team meeting! See below for information about the meeting and next steps.

# Information

_Information about when and where the meeting will take place_

- **Date:** 2021-08-02
- **Time:** 7AM US/Pacific time (or [**your timezone**](https://arewemeetingyet.com/Los%20Angeles/2021-08-02/07:00/2i2c%20Team%20Meeting#eyJ1cmwiOiJodHRwczovL2hhY2ttZC5pby9ZNVNCTXhWN1I2Q01xemVUWGdtNWtBIn0=))
- **Video conference link:** https://bit.ly/zoom-holdgraf
- **HackMD for meeting:** https://hackmd.io/Y5SBMxV7R6CMqzeTXgm5kA
- **Calendar for future meetings:** [this Google Calendar](https://calendar.google.com/calendar/embed?src=c_4hjjouojd8psql9i1a8nd1uff4%40group.calendar.google.com&ctz=America%2FLos_Angeles)

# Follow up issues

_Links to follow up issues below_

- https://github.com/2i2c-org/team-compass/issues/192
- https://github.com/2i2c-org/team-compass/pull/188
- https://github.com/2i2c-org/team-compass/issues/167
- https://github.com/2i2c-org/team-compass/issues/175

# Actions

_Steps to take to have the meeting._

- [x] Have the meeting
- [x] Open up any follow-up issues or discussions and link above
- [x] Cut notes out of HackMD and add to the Team Compass: https://github.com/2i2c-org/team-compass/pull/193
- [x] Update HackMD information for next month's meeting
- [x] Create a GitHub issue for next month's meeting: #195 
- [x] Meeting complete! 🎉

**Comment by choldgraf** [comment]
Hey @2i2c-org/tech-team - just a reminder that we've got a team meeting on Tuesday, so if you'd like to discuss something in particular please add it to the agenda!

**Comment by sgibson91** [comment]
> we've got a team meeting on Tuesday

I think it's Monday

**Comment by choldgraf** [comment]
Yes it's on Monday! 🤦

**Comment by choldgraf** [comment]
Hey all - I've put some items on the team meeting agenda for today, mostly around discussing team process, encoding deliverables/goals in issues, etc. Please feel free to make any edits or additions if you think these aren't quite the right questions!

https://hackmd.io/Y5SBMxV7R6CMqzeTXgm5kA

**Comment by choldgraf** [comment]
OK, I believe that I've got our notes ready to go, and have also opened/updated issues for the major things we discussed to do next.
