### ISSUE TITLE
Pilot Hubs should have a single non-2i2c admin user manually specified

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#166]
# Summary

We have run into some confusion with setting admin users on some of our hubs, where people didn't know whether they were admins and were asking 2i2c for admin users status.

This is some extra noise that we have to deal with, and it would be simpler if there were a single, repeatable policy for who gets admin user status on a hub.

I propose that we adopt the following practice:

- All 2i2c engineers get admin user status on hubs via **manual configuration** (ideally this would be automatically interpolated from config somewhere)
- The Community Representative gets admin user status on hubs via **manual configuration**
- All other Hub Administrators must be added via the JupyterHub UI **by the Community Representative**.

# Important information

- Some discussion in slack: https://2i2c.slack.com/archives/C01DB2JRP8W/p1626768120154300
- An issue that led to this conversation https://github.com/2i2c-org/pilot-hubs/issues/529

# Tasks to complete

- [ ] Discuss and/or agree with this policy
- [ ] Write it up into the pilot hubs documentation
- [ ] Done!

Note: I think we can leave our *current* hubs as-is, and adopt this for any new hubs.

**Comment by damianavila** [comment]
I think this is a sensible policy as is it presented here.

**Comment by choldgraf** [comment]
Some feedback we got from the OceanHackWeek community is that it would be helpful if ** up to two Community Representatives** could be designated for a hub. This way if somebody is away, on vacation, etc there is still another that can ask questions to 2i2c.

**Comment by choldgraf** [comment]
Another vote in favor of > 1 Representative per hub - the U. Toronto folks said that similar service-oriented groups usually designate at least 2 representatives as well.

**Comment by sgibson91** [comment]
This definitely makes sense
