### ISSUE TITLE
Play around with FreshDesk UI and understand how it works. Decide if this is a good solution.

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#169]
We have a 3-week FreshDesk trial set up at 2i2c.freshdesk.com

Each of the @2i2c-org/tech-team members should have access to this. See https://github.com/2i2c-org/team-compass/issues/167#issuecomment-883994584 for some background.

Here are some things to try:

1. Go to https://2i2c.freshdesk.com and log in with the address that was in the notification email to you)
2. Try opening a ticket by emailing the support email (support@2i2c.org should work)
3. Try reading tickets and responding to them, including adding comments

**Comment by yuvipanda** [comment]
So far, I like that:

1. There's one incoming email address
2. 'Private note' that is visible just to support staff
3. An integrated 'TODO' that helps track resolution for a single ticket

**Comment by yuvipanda** [comment]
There's also a web interface for customers to file tickets: https://2i2c.freshdesk.com/support/home. I think this can be customized as well to add additional fields, such as name of hub and other details.

**Comment by choldgraf** [comment]
This is a quick update with some early experience using FreshDesk and summarizing some conversations that we had today.

**Pricing**

They generally charge about $19 / month / user for their cheapest plan ($15/month if we use an annual plan). This should be enough for what we want, though there are some fancier features like multi-timezone SLAs if we pay for higher plans (more like $50/month/user). I suspect we'll want to start with the cheaper option if we go with them, and then scale up to higher plans if we find value in the service.

**Features**

It has some nice features around having a "single access point" for people to ask questions, but where **multiple** 2i2c team members could view, discuss, and answer those questions. I think this is the main use we'll get out of it.

**GitHub Integration**

The GitHub integration is not fantastic - [this is the plugin they use](https://www.freshworks.com/apps/freshdesk/github_integration/). It has basic support for things like commenting across issues, and has paid features like "synchronizing" tickets and github issue comments.

**Comment by choldgraf** [comment]
## Update on pricing

I heard back about the lower tier pricing option. For this we'd get a 15% discount as a non-profit. It would total **$80 per month at (~$15 per agent per month)**. This would get us all of the most important features we would use, I believe.

**Comment by choldgraf** [comment]
Assigning a few members of the @2i2c-org/tech-team that might be doing semi-regular support for various hub communities, so they have a chance to look at this UI :-)

**Comment by sgibson91** [comment]
I might recommend this to Paige for any support needed during the COESSING workshop next week.

**Comment by choldgraf** [comment]
That'd be great - anything that we can do to prototype process, get a better feeling for it, etc. I think we can also be pretty up front with folks about this being a test, and ask them for feedback and thoughts!

**Comment by choldgraf** [comment]
I'm going to close this as we've had some time to use this, and we have https://github.com/2i2c-org/team-compass/issues/167 to discuss whether to keep using it long-term
