### ISSUE TITLE
Process for decommissioning short-lived hubs

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#171]
# Summary

For hubs we deploy for a short-term, such as to support workshops and conferences, we should have a decommission process that checks-in with the Community Representative/Hub Admins that removing the hub is ok, any data from NFS servers they'd like to keep is migrated, and the hub is gracefully removed.

# Actions

- [ ] Decide and document how hubs should be decommissioned, including migrating data if required
- [ ] Create an issue template/form that tracks the decommission process and communications with Hub Representatives/Admins

**Comment by choldgraf** [comment]
100% this is a process improvement we should work out!

I've moved this to "needs discussion" so that it's clear this one needs more conversation and thinking before we move forward. Does that make sense?

**Comment by sgibson91** [comment]
The [end date for the COESSING workshop hub is Aug 31](https://github.com/2i2c-org/pilot-hubs/issues/473) so this would be a good opportunity to draft a process/issue template and get feedback on it

**Comment by sgibson91** [comment]
While we may not actually be decommissioning the COESSING hub, I wanted to get feedback on the checklist I put together in https://github.com/2i2c-org/pilot-hubs/issues/679#issue-995296431 Does this feel like a good first pass and an issue template to track such tasks?

**Comment by damianavila** [comment]
> Does this feel like a good first pass and an issue template to track such tasks?

YES.

**Comment by choldgraf** [comment]
agreed - I like that list quite a lot - I suspect that many hubs will have a similar response, so we should definitely explicitly ask them. This will often be an opportunity to convert single-use hub communities into longer-term communities! (obviously, it would be great if they'd be paying us as well 😅)

**Comment by sgibson91** [comment]
Ok, will try and open a PR soon

**Comment by sgibson91** [comment]
I have opened https://github.com/2i2c-org/pilot-hubs/pull/699

**Comment by sgibson91** [comment]
Closed https://github.com/2i2c-org/pilot-hubs/pull/699 in favour of https://github.com/2i2c-org/pilot-hubs/pull/700 which was created by following the workflow here: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates

This is because I noticed our "Hub Incident" template doesn't show up on the "New Issue" page and I'm wondering if it's because it was configured using the legacy workflow. If we merge https://github.com/2i2c-org/pilot-hubs/pull/700 and everything works, I will update the hub incident template too.
