### ISSUE TITLE
Define team process around when and how to share a grafana API key for deploying dashboards

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#176]
# Summary

When deploying grafana dashboards using [jupyterhub/grafana-dashboards](https://github.com/jupyterhub/grafana-dashboards), an API key is created to do the deployment. Should we keep this key for others to use? If so, where?

# Original Context

> What scenario do we envision others needing to use [the API key] once the grafana dashboards have been deployed? We need to figure that out and define that process
> 
> _Originally posted by @sgibson91 in https://github.com/2i2c-org/pilot-hubs/pull/550#discussion_r675601491_

# Actions

- [ ] Define a set of scenarios where an engineer may need access to a grafana API key after the initial deployment of the grafana dashboards
- [ ] Decide where and how to store these keys with appropriate metadata about which cluster they relate to

**Comment by choldgraf** [comment]
This feels like something we'd store via `sops`, similar to our other cluster-specific credentials. Does that make sense to others?

**Comment by sgibson91** [comment]
I think using `sops` for sharing would be right. I'd still like to work out the scenarios where sharing is needed over just deleting and recreating a key though. Otherwise, we'll end up with a huge file of API keys and metadata on which hub they belong to, and I'd like to know if that's "worth it" first.

**Comment by choldgraf** [comment]
Ah that's a good point - I don't think i have an intuition for that one. I think it comes down to whether we really expect the API key setup to be a one time operation, and how trivial it is to create a new one if need be. If either of those answers are yes, my feeling is we should just document how to recreate the API key if need be rather than storing it
