### ISSUE TITLE
Team practice for sharing passwords and secrets

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#183]
# Summary

There are a few places where we share accounts to access the same services or webpages. An example of this is the grafana of a hub, where we don't necessarily want to create a new admin username for every single hub engineer.

For these cases, we currently follow a practice of "ask a team member what the password is". This makes it hard to know who has access to which passwords, and is an extra step team members must follow to get access. It's also something that has to be done _each time_ a new password is needed.

```[tasklist]
- [x] Answer questions below, and if we wish to proceed...
- [x] Document process for sharing passwords with `sops` (now here: https://compass.2i2c.org/en/latest/engineering/secrets.html#sops-overview)
- [x] Proposal to use BitWarden here: https://github.com/2i2c-org/team-compass/issues/183#issuecomment-1497179602
- [x] Set up BitWarden account
- [ ] https://github.com/2i2c-org/team-compass/issues/719
- [x] Add relevant team credentials to organizational account
- [ ] https://github.com/2i2c-org/team-compass/pull/726
```
# Proposal

We use a team password application like [1Password](https://1password.com/). This would allow us to store the passwords in an encrypted service, and we could purchase a team account that would provide each of us access to them (I believe their base team account is $20/mo for 10 people, which isn't bad). We could then use this to store any team passwords that don't require 2FA in order to log-in, and then the only step for providing access to a new team member is to get them a 1Password account.

Latest more specific proposal is here: https://github.com/2i2c-org/team-compass/issues/183#issuecomment-1497179602

**Comment by sgibson91** [comment]
For the specific grafana admin case, the password is in `pilot-hubs` under `support/secrets.yaml` encrypted with `sops`. This info is in the docs [here](https://pilot-hubs.2i2c.org/en/latest/howto/operate/setup-grafana.html#setting-the-dns-a-record)

**Comment by yuvipanda** [comment]
Do we have a list of other passwords we share? Ideally we'd have none. Grafana's is there because it needs to be read by helm, so keeping it in the repo is the right thing so we don't duplicate it. We should have Grafana auth via GitHub or the JupyterHub itself instead though.

For stuff like twitter, I'd like us to use [twitter teams](https://help.twitter.com/en/using-twitter/tweetdeck-teams) or similar rather than share passwords. 

Sharing passwords also causes bad problems with 2 factor authentication, since that'll need to be shared too. 

If we *must* share passwords, I'd suggest using [bitwarden](https://bitwarden.com/) instead of 1password. They're open source, securely audited, work across devices, have decent UX, and matches our 'right to replicate' :D I'd rather support them than add on to the hundreds of millions of dollars in VC funding that 1password has now

**Comment by choldgraf** [comment]
I opened this issue before I really understood what sops is and what we were using it for...it may not be necessary for us to use a password manager other than this just yet. Do others agree? Instead perhaps we just need more documentation of the sops workflow, maybe I can help with this as I give it a shot.

Longer term, we will likely need something more non-developer-friendly but don't need to force it now IMO

**Comment by yuvipanda** [comment]
> Longer term, we will likely need something more non-developer-friendly but don't need to force it now IMO

100% :)

**Comment by damianavila** [comment]
If we can keep just one place, let's go with that... having some secret in someplace and others in some other place is ALWAYS problematic 😉  !

**Comment by choldgraf** [comment]
OK cool - I've updated the todo list with actions to document `sops` for password management in our practices, rather than to use a new password management tool 👍

**Comment by choldgraf** [comment]
# Update from CSS

I just had a conversation with the CSS admin team that seems relevant here as well. Two points of information:

1. The CSS team uses 1Password, and if we like we can get 50% off of a team account through them.
2. Apparently we can set up a 2i2c-specific credit card with CSS which we can use for big purchases like flights, hotels, and equipment (so that we don't have to file reimbursements). This might be a use-case that is outside the scope of `sops`

**Comment by choldgraf** [comment]
### Let's make a decision

I see that we discussed this one but didn't make a decision. Recently @pnasrat had brought this up again in #699, and given that we now have a number of places in our documentation that say "ask a team member for the password", I think we should just decide and move forward.

### Proposal: use Bitwarden's teams plan

BitWarden is an Open Source password manager with a hosted service for individuals, teams, and enterprise. It [is open source and has self-hosted options](https://bitwarden.com/open-source/) and generally seems like a good company. We've already got endorsement from @yuvipanda for this (and for what it's worth @choldgraf has used this for a few years and likes it).

They have two "group" plans, I think that the "Teams plan" has the features that we need. See link below for details:

https://bitwarden.com/pricing/business/

This will be $3 / mo / user. If we assume a team of 10 users, that equates to $360 / year. I think this is a minor cost given the security and efficiency benefit we get from sharing passwords in a more structured fashion.

**Note from @pnasrat on self-hosting**: While bitwarden is Open Source https://bitwarden.com/open-source/ and could be self-hosted, the hosted offering will make sharing across the team more straightforward along with user group control and passwords collections. The enterprise offering offers SSO connection, but the teams offering would have individual bitwarden accounts

### Alternatives Considered

Engineering currently uses [sops](https://compass.2i2c.org/en/latest/engineering/secrets.html) for encrypted files for machine readable API keys etc, however that is likely unsuitable for company wide usage.

CS&S uses [1Password](https://1password.com/pricing), which is similar to BitWarden, though slightly more expensive and not open source. There's some upside to sharing the same password manager as CS&S, but thus far we have not reached a situation where we needed to use one of their passwords, so I don't anticipate this being super useful on a regular basis.

**Comment by choldgraf** [comment]
We discussed this in the strategy and org meeting today, and agreed that going with bitwarden is a reasonable path forward.

If nobody objects then i will plan to sign up for a bitwarden team account in the next few days
