### ISSUE TITLE
Define the Support Steward role

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#187]
# Actions

- [x] #200
- [x] #291
- [x] Use this workflow for a few iterations of the Support Steward
- [x] Create the Support Steward calendar to link in our support steward issue
- [x] Create issue template for the steward and potentially update it
- [x] https://github.com/2i2c-org/team-compass/pull/311

**Comment by choldgraf** [comment]
### Update: Feedback from last support steward debrief

@damianavila and I had a brainstorm session about his experience with the support steward, here were a few things we'd like to improve in our support steward docs:

- [ ] Add language about the “support steward lifecycle” to our document, add a <24 hour turnaround with support. Something like
    - Target response time: <24 hours to respond (not to resolve) (and excluding weekends/holidays)
    - When you receive a ticket, communicate that you have received it and note the next steps you’ll follow to resolve it.
    - Give updates to the community as you work to resolve the issue
    - When it is resolved, tell the community what you’ve done to resolve the issue
    - In general, it is encouraged to prioritize support-related issues over development/backlog issues

- [ ] Emphasize that it is about "communicating" and "routing".
  - But as support steward is router, people develop *expertise* in certain areas, and it's ok to route requests to such a person. Also ok to route something to someone if they were just working on it / were very active in that space. Must be balanced against making sure we don't pigeonhole people
- [ ] Also language about tackling support *issues* that are created (like creating new hubs). These are auto-assigned to the support steward.
- [ ] Events, and when the support steward needs to pay special attention to certain kinds of tickets
- [ ] Update to be a 2 person team where one person rotates off every week
- [ ] Clarify that the support stewards are the main point of contact for all support tickets regardless of the community - there is no community-specific support person, just the team
- [ ] Make explicit that support steward has the right to ask others for help moreso than usual

**Comment by damianavila** [comment]
> Update to be a 2 person team where one person rotates off every week

I think the rotation would be every 2 weeks (to be in sync with the sprints) but still a 2 person team.
That means you will be serving in a support role for a month (2 sprints) but a 50% capacity since you will have a support partner.

**Comment by choldgraf** [comment]
I'm closing this one, as the PR that defined this role has been merged, and we have other issues opened to discuss iterative improvements to the role!
