### ISSUE TITLE
Team sync for January W1 2021

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#19]
Hey @2i2c-org/tech-team 👋 let's try out the first team (a)sync of 2021!

- Check out [our team sync process here](https://2i2c.org/team-compass/tech-team-coordination/#bi-weekly-team-syncs)
- Fill in your updates in [this HackMD](https://hackmd.io/i2Siurp1TkmPYgn3ZgxFQw)

That's it!

btw, do people actually get pinged when I @ tech-team? If so can you tell me below? :-)

**Comment by consideRatio** [comment]
@choldgraf yepp! It becomes a "team mention"

![image](https://user-images.githubusercontent.com/3837114/103642145-03d36e80-4f53-11eb-9a0d-8ed71513cf94.png)
