### ISSUE TITLE
Deliverables Review Meeting: 2021-08-10

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#198]
# 2i2c Deliverables Review meeting

This is a **30 minute** recurring meeting every two weeks on **Tuesday at 8:00AM Pacific time** (here's [**a timezone converter**](https://arewemeetingyet.com/Los%20Angeles/2000-01-01/08:00/2i2c%20Team%20Meeting#eyJ1cmwiOiJodHRwczovL2hhY2ttZC5pby9ZNVNCTXhWN1I2Q01xemVUWGdtNWtBIn0=), ignore the date!).

Our goal is to synchronize the team on the most important things to work on, and to divide work between one another so we know what to work on next.

- **Video conference link:** https://bit.ly/zoom-holdgraf
- **Calendar for future meetings:** [this Google Calendar](https://calendar.google.com/calendar/embed?src=c_4hjjouojd8psql9i1a8nd1uff4%40group.calendar.google.com&ctz=America%2FLos_Angeles)

## Meeting agenda

_Follow the agenda below, checking boxes as we complete each step._

### Activity Backlog
_(5m) Quick review of [Activity Backlog](https://github.com/orgs/2i2c-org/projects/5?fullscreen=true) to let team members signal-boost if needed._

- [ ] Team members signal-boost latest team sync items if they wish.
- [ ] Note items that 2i2c team members wish to highlight for review.
- [ ] Note important upcoming dates for the team.

### Major deliverables

_(20m) Overview major work items in our [Development Backlog](https://github.com/orgs/2i2c-org/projects/7?fullscreen=true)._

- [x] Discuss any high-priority items that need refinement.
- [x] Each 2i2c team member knows the next two things that they'll work on.
- [x] Each high-priority ready-to-work issue has at least one team member assigned to it.

### Support steward transfer

_(5m) Transition support steward roles to the next team member._

- [ ] Preview support steward describes major support issues that have come up (with links to relevant issues)
- [ ] Open issue for next Support Steward.
- [ ] Close previous issue for Support Steward.

**Comment by damianavila** [comment]
There was no review of the activity board since we were starting a new process with a blank sprint board.
The sprint board was filled with high prio issues and assigned to each team member.
@choldgraf agreed to continue on the Support Steward role for some time.

Closing this one now, re-open if you disagree.
