### ISSUE TITLE
Document a team process around sprint planning

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#201]

**Comment by damianavila** [comment]
Such as building the backlog (prepare the board from where we pick deliverables to add into the sprint board?
Something else? Another thing? It is not clear to me what you are aiming for here.
Thanks!

**Comment by choldgraf** [comment]
@damianavila I think that https://github.com/2i2c-org/team-compass/pull/188 will close this, I just wanted to create an issue to track this item for the week since I'm hoping we can get it merged this week
