### ISSUE TITLE
Document team process around signaling that something is blocked on external collaborators

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/team-compass#203]
Often, we are waiting on an external collaborator to perform an action before we can proceed with a deliverable - https://github.com/2i2c-org/team-compass/issues/136 is a great example. Signalling that we are blocked on  *external* action is helpful. A system that signals *actions* that *we* can take on these blocked issues may be very helpful. Actions I can think of include:

1. We can check them occasionally, see if we can do anything to make the process move along
2. Signal to ourselves that we can 'let it go' for a while.

For (1), it would be useful to encode *how often* we should make a ping - otherwise it will be unclear which ones need to be pinged again since it's been a month since last activity, vs something where the ping was done 3h ago.

**Comment by damianavila** [comment]
I have posted this on Slack:

> In our case, I think having a label to signal a "blocked" state makes sense (whatever tag you may use), then you add more properties with more labels, ie:
`<blocked> <external> <1w>` which means this is blocked by someone/something external, please check in 1 week. Since GH let us know when these labels were applied, we should be able to quickly figure it out when to look at them again...
This is just a way to handle it, it could be other ways as well...

**Comment by choldgraf** [comment]
I think that a first step could just be:

- Create two labels. `blocked:internal` and `blocked:external`
- When the label is applied, it should be paired with a status update (or update to the top comment) saying why it is blocked, and what action will un-block it.

I feel like this would be easy to find and remember to apply labels. I worry that adding more complexity than this (like 'check back in after XX time period' labels) would be less-likely to be followed. Could we just rely on the context in the issue for this? I don't think / hope that we will ever have _too many_ issues in "blocked" state, and so perhaps this is something that we can manage with regular check-ins and quick discussion for all issues with `blocked` labels?

**Comment by damianavila** [comment]
In Slack I have proposed a `paused` (blocked) column in the board and then labels for categorization and signaling:

An `external` label means it is blocked/paused on some external agent action
An `internal` label means it is blocked/paused on you (I can foresee cases where you are blocked and you need some time to process the stuff, so you start working on other tickets whereas that is "technically" blocked)
A `help` label inviting other team members to provide help.
In addition, if you need help from some specific team member (or the whole team) you could reassign the card to them and after the help is completed the card is reassigned to you?

**Comment by choldgraf** [comment]
I proposed something similar but slightly different here: https://2i2c.slack.com/archives/C01GLCC1VCN/p1628903157226400

**Comment by damianavila** [comment]
I do not totally concur with the concept of not seeing `blocked` as a status thing (and not using a column for that), but I understand things like this could be interpreted by a different and subjective (like mine 😉 ) vision.
As I said in Slack, I am happy to try your Slack proposal!

**Comment by choldgraf** [comment]
I think that we can close this one, as we've iterated in a process for a while now and currently have this documented at https://team-compass.2i2c.org/en/latest/practices/development.html#the-sprint-board
