### ISSUE TITLE
[discuss] What does DevOps mean to 2i2c?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#256]
In a recent issue, we added this language to our website:

> We design, develop, and operate JupyterHubs in the cloud for your community in research and education. We handle the DevOps, you focus on your work.

@yuvipanda rightly pointed out that this term was very overloaded, and asked me to clarify what I meant by it.

This is a quick discussion to give my thoughts, and see if others have their own! I'll plan on closing this issue in a few days or if conversation seems to have resolved.

### What is DevOps?

Here's how I'd define DevOps as it pertains to 2i2c:

2i2c provides DevOps as a service, because it **Develops** infrastructure for cloud deployments in research/education, and **Operates** those deployments on behalf of communities. The development and the operation happen hand-in-hand with one another - operating the infrastructure leads to ideas for new development, and new development is ~ immediately deployed into production and operated by us so that others benefit from it. Thus a short-hand way for describing that cycle is "DevOps".

I added that sentence into our website because folks at U. Toronto had been informally calling 2i2c "Operations as a Service", and I wanted to include the fact that we also _create and improve_ (AKA, develop) the technology, not just operate it for you, so that's why I went with "DevOps as a Service".

### Other thoughts?

This is just my take on what DevOps means to 2i2c - I'm curious if others have a different idea! And also wonder if this is something we should document, if in-fact we use this term.

**Comment by colliand** [comment]
This is an interesting issue and I look forward to learning from the discussion. 

A few years ago, I learned about Site Reliability Engineering from @yuvipanda. He shared [this link](https://sre.google/) with me then. A few things became clear to me after reading through that guide:

+ Universities tend to not have any SRE capacity and find it difficult to recruit site reliability engineers.
+ SRE enables economies of scale, with the scales often being larger than a single university.
+ Reliable low-cost JupyterHub service requires SRE.

In discussions at UBC and U. Toronto, I've heard administrators express interest in 2i2c while saying things like "...well, to run a hub for my university, I need at least one and maybe two or three FTEs. We will save money with 2i2c if you can effectively provide us the service at the cost of a fraction of an FTE." Having a solid and agreed-upon definition of `devops` and/or `SRE` for 2i2c will help us sharpen this way that our customers will use to find value in 2i2c service.

While working on pricing and tiers for an alpha service offering, @choldgraf and I have often talked about a key metric for 2i2c's operating cost. Quantifying and monitoring that metric, the number-of-hubs-2i2c-effectively-operates-per-engineer, will require a shared understanding of devops/SRE.

**Comment by choldgraf** [comment]
@damianavila that's a good point - in many ways I think that `DevOps` is often connected with a _style_ of development/operations rather than a service per-se. Site Reliability Engineering is more closely connected with value that a user gets. Put another way - a "DevOps mentality / process" is a way to do a good job of Site Reliability Engineering.

So I guess then we would say that 2i2c does not "do DevOps", we do a good job of _Site Reliability Engineering_ with an organizational culture that pulls from DevOps philosophy. In addition, the same group of people does software development for open source tools that eventually make their way into our managed service.

This makes me feel like devops.2i2c.org would be better-named to either infrastructure.2i2c.org or sre.2i2c.org ...

**Comment by damianavila** [comment]
> So I guess then we would say that 2i2c does not "do DevOps", we do a good job of Site Reliability Engineering with an organizational culture that pulls from DevOps philosophy. In addition, the same group of people does software development for open source tools that eventually make their way into our managed service.

I like this definition!

> This makes me feel like devops.2i2c.org would be better-named to either infrastructure.2i2c.org or sre.2i2c.org ...

I would agree with that...

**Comment by sgibson91** [comment]
> @sgibson91 do you know if the RSE community has defined 'DevOps'?

I have asked in the RSE slack :)

**Comment by choldgraf** [comment]
Thanks all for the nice discussion! Closing this as I think we generated some interesting ideas to think through :-)
