### ISSUE TITLE
Write blog post for launch of Pangeo on 2i2c

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#272]
### Description

We should write a blog post announcement to be released when the Pangeo prod hub goes live :)

Blog post should cover:

- What is the collaboration between Pangeo and 2i2c and what does it mean for Pangeo hub users
- Any questions raised in the staging announcement discourse thread: https://discourse.pangeo.io/t/migration-of-staging-us-central1-b-gcp-pangeo-io-to-2i2c-infrastructure/1864

### Value / benefit

- Increased visibility/publicity of the collaboration
- Let people know the migration is happening and what to expect

### Implementation details

I created a blank(ish) hackmd to draft this here: https://hackmd.io/@sgibson91/BJ4Mfi0BK

**Comment by sgibson91** [comment]
I've transferred this into a PR https://github.com/2i2c-org/2i2c-org.github.io/pull/85

**Comment by choldgraf** [comment]
### Update: this is posted!

- Blog post link: https://2i2c.org/posts/2021/pangeo-goes-live/
- Twitter link: https://twitter.com/2i2c_org/status/1460712555811262467
- LinkedIn link: https://www.linkedin.com/feed/update/urn:li:activity:6866518963405377536
