### ISSUE TITLE
[Proposal] Cloud cost estimation for JupyterHubs on shared clusters

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#277]
### Description

In our alpha service doc (#262) we need to be able to estimate the cloud resource usage for each community's hub. This is more difficult on shared clusters, because we do not have a 1-to-1 mapping of billing account to hub community.

Here is a proposal to estimate cloud costs for our alpha service, I'd love comments and ideas from others:

- [**Link to cloud costs proposal section**](https://docs.google.com/document/d/1R3ovKIcHCpE7A77ovrXntRc2XkmK8nnZgVhUMWDT4vQ/edit?usp=sharing)

It makes the following assumptions, and I'd love feedback about whether these are correct:

1. The largest driver of cost for most communities will be interactive user sessions
2. All other cloud costs like support infrastructure is shared between user communities and thus fairly low
3. RAM is the biggest driver of cloud costs, because it is generally the thing that triggers node scale-up events.
4. We have the ability to track the RAM requested for user pods for each hub by the hour. (I looked at our Prometheus metrics and I _think_ this is possible)

Finally, because I'm not sure how to estimate cloud usage for Dask Gateway hubs yet, I suggest that we *only run these hubs on dedicated clusters* for the alpha. We can change this if we come up with a good way to estimate their usage on a shared cluster (but not for the alpha).

### Value / benefit

This is designed to be a balance between what is possible right now and what is reasonable given our costs. So the main benefit is that it accurately reflects our actual costs, and is possible to calculate in a sustainable way given the Prometheus metrics we're generating.

### Tasks to complete

- [ ] Take a look at the proposal and let me know if you think it should be amended in a significant way (feel free to suggest or make edits!)

**Comment by yuvipanda** [comment]
> Should I just include something hand wavy in the document, with the confidence that we will figure it out by the time we need to send somebody an invoice?

I think that's the way to go. State that we generally commit to just passing through cloud costs based on our calculation of *resources your hub is using on a monthly basis*, and handwave on the details. 

I think the way to develop cost model is to try to put a dollar number on a particular hub, and then generalize that. I think that will work better than going the other way around. So if you know someone we are working with who is in a position to start paying, we can work on figuring out cloud cost for that user and tweak the formula as we go. We can and should provide some guarantees that we aren't going to be wildly changing it each month, but it is going to change anyway as we make optimizations and rejig infrastructure.

**Comment by choldgraf** [comment]
@yuvipanda sounds good - this is what I'll do then. The thing I worry about is that other communities may want a specific number, but let's start with the more hand-wavy approach and we can cross that bridge when we get to it.

**Comment by yuvipanda** [comment]
@choldgraf yeah - I think picking a community and giving them a specific number is something we should prioritize.

**Comment by choldgraf** [comment]
To make sure we are on the same page, you're suggesting:

- In the alpha service doc, we include language that says we'll estimate cloud costs based on hub usage, and give general ideas of what this means (RAM, storage, etc) but without adding specific numbers or equations.
- When we actually work with a specific community, at the end of a month we'll go through the process of estimating their costs, and use this as a starting point for how to do the same for other communities.
- Use this to iteratively build up a model for passing-through cloud costs

**Comment by yuvipanda** [comment]
@choldgraf correct!

**Comment by choldgraf** [comment]
OK, I've updated our alpha rationale etc with this new language, and we can track the improvements to tracking hub usage costs in https://github.com/2i2c-org/infrastructure/issues/730

will close this one, thanks all for the helpful explanations!
