### ISSUE TITLE
Attend the EOSS meeting

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#281]
### Description

This is just a note that the EOSS meeting is from Tuesday November 2nd, through Thursday November 4th.
I'm giving a short talk on Wednesday about the EOSS work that we'll be doing, and otherwise will generally be trying to attend and participate where I can.

### Value / benefit

This is a great community to connect with, as it may spur collaborations with open source projects or with scientific projects. We also are funded by CZI so wish to be a positive part of their community!

**Comment by sgibson91** [comment]
Going to close this one now as the EOSS meeting wrapped up yesterday!

**Comment by choldgraf** [comment]
Two sessions that I found really interesting:

- @gvwilson hosted a workshop on effectively managing (research) projects. [Here are the slides](https://codebender.org/czi-2021-11/). It covers a lot of great stuff on strategy, implementation, thoughtful organizational and team leadership, etc. 
- @k8hertweck hosted a workshop on building sustainable and inclusive communities in open source projects. [Here are the slides](https://docs.google.com/presentation/d/1kiewWhpjutX0iYYkDli2DN_LdfrWtzbi5TUFyAqJMPM/edit#slide=id.gfd298f0ae7_0_2679). It covered a lot of topics around community governance, inclusion, strategic thinking about structure, etc.
