### ISSUE TITLE
Enforce HTTPS on 2i2c.org

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/team-compass#284]
### Description

If you go to http://2i2c.org, it doesn't automatically redirect you to the https version!

### Value / benefit

The world is a better place when everyone is always on https. Plus It makes us look a little more competent.

### Implementation details

I think we just need to turn this setting on in GitHub pages.

**Comment by sgibson91** [comment]
<img width="785" alt="Screenshot 2021-11-05 at 10 20 37" src="https://user-images.githubusercontent.com/44771837/140495864-3aa80dce-5319-4687-91aa-f70b7f7de9ef.png">

I think we also need to change to a CNAME from an A record too

**Comment by sgibson91** [comment]
I changed the record in Namecheap and now GitHub is happy

<img width="690" alt="Screenshot 2021-11-05 at 10 34 58" src="https://user-images.githubusercontent.com/44771837/140497679-a95ffdd0-5ab8-4db9-991c-268896c496d3.png">

And I confirmed in a private browser that http://2i2c.org redirects to https!! 🎉

**Comment by yuvipanda** [comment]
Thanks a lot, @sgibson91!

**Comment by choldgraf** [comment]
amazing!
