### ISSUE TITLE
[Proposal] Deliverables backlog cleanup and simplification

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#289]
### Description

As a follow-up to our meeting today, I'd like to try an experiment on the Deliverables Backlog. I fear that we have way too many things on that backlog at once, and this makes it cumbersome to navigate and inspect. Are folks OK with (and do you have any feedback for) the following plan:

- Remove deliverables from the backlog to reduce the total number, and only keep the deliverables that we want to work on within the next 3 sprints.
- Assume that in a given sprint, each team member finishes an average of 2 deliverables.
- In the future, limit the number of deliverables on this board to `n_team_members * 2 (deliverables per sprint) * 3 (sprints)` and round up to the nearest 10 (so currently this would be `40`)
- In the future, if we wish to add a new deliverable to the backlog, but we are already at this limit, we must remove one from the backlog first.
- Stop grouping the backlog by category by default, and just keep it as a flat list.

Does anybody object to this? Or have thoughts on how to improve it? **If I don't hear any objections, I'll plan to do this in the next day or so**.

### Value / benefit

My hope is that this will keep that backlog more manageable, and encourage us to be realistic in our planning. We can update the limit up or down depending on our experiences of how much we complete on average, but the important thing is that we have a limit in general.

**Comment by sgibson91** [comment]
I'm +1 on trying this out iterating as needed
