### ISSUE TITLE
Team Roles Meta Issue

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/team-compass#294]
### Description

This is a meta-issue to keep track of who is currently on the Support Team. When we transition support stewards, update the top comment of this issue with the latest information.

### Support Team

Our current support stewards are:

- @choldgraf 
- @yuvipanda

### Meeting Facilitator

Our current meeting facilitator is:

- @choldgraf

**Comment by consideRatio** [comment]
Some takeaway points:
- Good thing to always reply quickly with a "I've received this ticket" or "I'll look into this" etc.
- Perhaps we need a procedure about how to go about closing tickets or similar?
- We have merge/split tickets techniques that can be used in freshdesk
- We have add private note as a technique that can be used to for example summarize a situation for a ticket, helping other people not need to re-read the entire tickets discussion.
- We also enabled email notifications on https://2i2c.freshdesk.com/a/admin/email_notifications

**Comment by consideRatio** [comment]
If this issue is meant as an issue to be closed by "Tasks to transition the support steward!", absolutely we close it.

I figured it was more like an issue to keep open until the stewardship is over and the next one has opened, like the jupyterhub/team-compass typically has an issue open to represent the next team meeting.

**Comment by choldgraf** [comment]
I think we should either:

- Leave this issue open to reflect who is the current support steward
- Have some other place where we keep track of who is the support steward (e.g., a google sheet that is also displayed on the team compass?) and then add a task to this issue that says to update that sheet.

Anyone have opinions?

**Comment by consideRatio** [comment]
I'm opinionated towards leaving it open.

**Comment by choldgraf** [comment]
let's just leave the issue open for now, and we can re-visit if there's a better practice for tracking this in the future

**Comment by sgibson91** [comment]
> * Leave this issue open to reflect who is the current support steward

We could pin the issue too, so it's always at the top of the issues list?

**Comment by choldgraf** [comment]
I'm +0, since I rarely look at the issues list . But if it would be useful for others I'm +1 on giving it a shot

**Comment by sgibson91** [comment]
> since I rarely look at the issues list directly

It's the first place I go if I'm _searching for a specific issue_ since it's not guaranteed to be on the sprint or backlog boards. And I think "Who is the current support steward?" is a scenario where we are looking for a specific issue.

**Comment by choldgraf** [comment]
I've repurposed this issue to serve as a "meta issue" that lists our current roles. I've also opened a PR to include a step to update this issue when those roles changed. Finally, I've pinned this issue so it has high visibility!
