### ISSUE TITLE
Sprint Planning Meeting: 2021-11-24

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#312]
# 2i2c Sprint Planning meeting

This is a **60 minute** recurring meeting **every other Wednesday at 7:30AM Pacific time** (here's [**a timezone converter**](https://arewemeetingyet.com/Los%20Angeles/2000-01-01/07:30/2i2c%20Team%20Meeting#eyJ1cmwiOiJodHRwczovL2hhY2ttZC5pby9ZNVNCTXhWN1I2Q01xemVUWGdtNWtBIn0=), ignore the date!).

Our goal is to synchronize the team on the most important things to work on, and to divide work between one another so we know what to work on next.

- [**Sprint Board**](https://github.com/orgs/2i2c-org/projects/21)
- [**Deliverables backlog**](https://github.com/orgs/2i2c-org/projects/22)

### Meeting roles

- **Meeting facilitator**: @sgibson91 
- **Next Support Steward**: @sgibson91 

### Meeting agenda

_Follow the agenda below, checking boxes as we complete each step._

**Review the Sprint Board.** (10m)

- [x] Celebrate our accomplishments
- [x] Archive deliverables we finished

**Populate Sprint Board with new deliverables** (45m)

- [x] Review in-progress deliverables from the last sprint: drop or carry over items as needed
- [x] Review a few more urgent items in the [deliverables backlog](https://github.com/orgs/2i2c-org/projects/22/views/1)
- [x] Add new deliverables to Sprint Board
- [x] Somebody is assigned to each deliverable
- [x] Everybody agrees the current cycle's plan is realistic and that the right items are on the board.

**Support steward** (5m)

- [ ] Support steward describes any open support issues.
- [ ] Support steward transition issue is opened

**Comment by GeorgianaElena** [comment]
@2i2c-org/tech-team, I forgot to ask about the next Support Steward and if we plan to do it in teams this time, or during the next round?

**Comment by choldgraf** [comment]
After some conversation in Slack, here is our plan for support steward etc.

**Problem**: @sgibson91 is currently the meeting facilitator, but she is also next in line for support steward. So we need to increase the gap in time between "being meeting facilitator" and "being support steward". The easiest way to do this is to increase the number of people between these two roles in the rotation.

**Next steps**:

- We will skip @yuvipanda who was going to be the next meeting facilitator, to increase the gap in time between these roles. The next meeting facilitator will be @choldgraf
- **effective now** @choldgraf is the meeting facilitator. We accelerated this transition as a one-time event. @choldgraf will be the facilitator for the next team meeting and the next sprint meeting
- **effective now** @sgibson91 joins @GeorgianaElena on the support team (issue to track this: #317 )

**Comment by sgibson91** [comment]
Thank you for the update @choldgraf! I think this issue can be closed now 🙌🏻
