### ISSUE TITLE
How to balance operations and development as a team?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#321]
### Description

There are three major kinds of work that our engineering team is doing:

- **Development** of our infrastructure to improve it, add new features, etc. This is something we can plan for ahead of time.
- **Operations** of our infrastructure to address issues as they pop up, perform upgrades, put out fires, etc. This is something that pops up in a semi-unexpected way.
- **Support** the community representatives that ask questions and report issues. This the least-predictable of our work.

I think that we are building a nice story around support with the support team, but I feel like we have still not figured out a clean story for how to balance operations vs. development. Here is the tension that I have felt recently:

- Development works best when we can plan out significant chunks of work, with clear outcomes, and where we can dedicate time to building things and addressing whatever issues are needed to get it done.
- Operations work is more unpredictable and often "one-off", and has a tendency to interrupt the momentum needed to enjoy and effectively do development work.
- As a result, we often have plans to do development work, but a person will get pulled into doing operations work instead and they'll be a bit derailed from their original goal.

### Question

Is there a team process or practice that we can create that can satisfy the following constraints:

- Ensure we have the operations capacity to do whatever tasks are needed to keep our infrastructure running smoothly
- Protect time for development so that people can dedicate the attention needed to see things through to completion
- Balance these in an equitable way across our team

I am curious what others think about this, I suspect that there will not be an obvious or easy answer, but I'd love to make iterative progress and potentially discuss as a team in our meeting.
 
This isn't a deliverable with a clear answer, but I'm hoping it can spur some discussion and maybe generate some ideas!

**Comment by yuvipanda** [comment]
https://sre.google/sre-book/eliminating-toil/ is a good read

**Comment by choldgraf** [comment]
We touched on this a bit, but we generally agreed that we weren't sure how to best do this. A few ideas that came out of it were:

- Have a dedicated team for operations that rotates through team members, similar to what we do with support. If you're on the operations team then you don't work on major development tasks for that cycle. You are also expected to be the first point of contact for dealing with hub outages. This would need to be a 2 person team at least, and ideally with coverage across major time zones.
- Assign operations tasks to people on an ongoing basis, via our sprint planning process. If each team member is focusing on one  major development project at a time, then they may be able to handle a small amount of operational tasks on the side, provided that these tasks were not too numerous or too complex.
- For particularly complex operational tasks (like https://github.com/2i2c-org/infrastructure/issues/868) we can frame these as a project, and have a dedicated person to carry them out over a fixed period of time.

**Comment by damianavila** [comment]
> We should revisit this question as we try this out.

Having a dedicated team is something I think will help us in the future (with a team you already have an "assignee": the operations team, whereas with option 2 we will continuously "fight" for finding the operation person at each sprint), so let's keep it in the back of our heads if we find enough issues with the option 2 (plus option 3) approach 😉  .

**Comment by choldgraf** [comment]
One goal we could shoot for is something like:

- Define the minimum number of people that would make a dedicated operations team viable (e.g., that would not unfairly or unrealistically ask too few people to do too many things)
- Once we hit that minimum number, define two teams:
  - The Site Reliability Engineering team - this team is fully responsible for operating our running infrastructure. They do development work as well, but focus it on improving the resiliency, speed, etc of our infrastructure. This team would be run similarly to https://sre.google/sre-book/table-of-contents/
  - The Product team - this team focuses on new development, features, etc in the ecosystem (e.g., improvements in Jupyter Hub/Book/Lab).
- We could define a rotation schedule between these two teams (maybe every 2 months or something?) so that people have a mix of "SRE-style engineering" and "creating new features".

**Comment by damianavila** [comment]
> Define the minimum number of people that would make a dedicated operations team viable (e.g., that would not unfairly or unrealistically ask too few people to do too many things)

That is a good and a difficult one. I do not think we have enough mass yet... definitely something to talk about!

> We could define a rotation schedule between these two teams (maybe every 2 months or something?) so that people have a mix of "SRE-style engineering" and "creating new features".

That is a nice idea so everyone has exciting times!
