### ISSUE TITLE
Create a "team roles calendar"

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#334]
### Description

We currently use [a team roles meta-issue](https://github.com/2i2c-org/team-compass/issues/294) to track which team members are in each role. However, this is a bit clunky to update, and also doesn't make it easy to see when team members will take on a role in the *future*.

Instead, we can create a Google Calendar that tracks all of our team roles. We can update this instead of a GitHub issue	

### Value / benefit

A few benefits:

- Calendars are easier to track into the future
- We can compare this calendar with our other team calendars, most importantly the **Team Leave** calendar - this could help us spot when people are planning to be away while they are in an important role
- It feels more natural to track dates in a calendar, than in an issue, so it may be more findable.

**Comment by sgibson91** [comment]
I am very +1 on this idea, and filling ti out ahead of time for, say, the next quarter.

**Comment by choldgraf** [comment]
alright I see lots of +1s on this, so how about this: https://github.com/2i2c-org/team-compass/pull/344
