### ISSUE TITLE
Plan for next week with many team members away

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#370]
### Background information
Currently we have 3 team members who are away next week (Mon 14th -> Fri 18th). @choldgraf @yuvipanda @sgibson91 

This means that we will be at a significant reduced capacity to help with operational and support issues, which will also likely impact people's ability to work on development projects.

I'm opening this issue in case there's any coordination that people would like to take in advance of next week. For example:

- Is there anything that **needs** to be wrapped up this week?
- Should we still plan on having a sprint planning meeting next week? @damianavila as facilitator I'll leave that to your discretion!
- Should team members plan to dedicate less time to development in the anticipation that some operational things will require more time than usual?

Just want to see if others have thoughts here!

**Comment by sgibson91** [comment]
I think we need to think about https://github.com/2i2c-org/infrastructure/issues/930 in some shape or form

**Comment by choldgraf** [comment]
@sgibson91 what do you think is the best path forward there? The team members that are around next week are @GeorgianaElena and @damianavila, @consideRatio has a lot on his plate next week.

@GeorgianaElena or @damianavila do either of you have experience with the GPU side of things?

If not, then I suggest we tell Joe that this definitely won't be implemented next week, and that we'll need to pick it back up when there are more team members present who can dig into it in the week after.

**Comment by yuvipanda** [comment]
I was overcaffeinated so I spent some time looking at the carbonplan GPU hub. I got it to work I think - see https://github.com/2i2c-org/infrastructure/pull/933#issuecomment-1035444897.

**Comment by damianavila** [comment]
> Should we still plan on having a sprint planning meeting next week? @damianavila as facilitator I'll leave that to your discretion!

With a 50% quorum (modulo everyone attends, it could be less), I think it is probably better to skip this week's sprint meeting. @GeorgianaElena and @consideRatio, I plan to cancel the meeting (and remove it from the calendar) by Wed morning. Raise your hand before that time if you disagree.

**Comment by damianavila** [comment]
Since both agreed with thumbs up, I will remove it now so prevent any confusion by tomorrow.

**Comment by consideRatio** [comment]
Thanks @damianavila!

**Comment by yuvipanda** [comment]
This week was over!
