### ISSUE TITLE
Populate our Team Roles Calendar for the next quarter/appropriate period

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#387]
### Background and proposal

It looks like the entries in the 2i2c Team Roles calendar tracking who the Support Steward and Meeting Facilitator are come to an end in April. We should populate the next 3 months (or more) with these roles by rotating through the names [here](https://team-compass.2i2c.org/en/latest/about/team.html).

**Comment by choldgraf** [comment]
I've updated the roles for the next few months - though I think we should discuss timing etc around these in the next team meeting, since there's some overlap, I think we've messed up the cycle periods a bit 😬

**Comment by sgibson91** [comment]
@choldgraf https://github.com/2i2c-org/team-compass/issues/392 may be able to help with the cycles?

**Comment by choldgraf** [comment]
yep! I added it to the agenda notes as well
