### ISSUE TITLE
Proposal to change how we rotate through team members for the Support Steward role

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#392]
### Background and proposal

Right now to select Support Stewards, we cycle through an alphabetical list of team members. This is a fine, if arbitrary, system.

However, now we have 3 team members in roughly American continental timezones and 3 team members in roughly European time zones. What if we start alternating the Support Steward role through timezones?

That way someone in ~Europe will always be paired with someone in ~America to hand off to if high priority tickets come in late in their day. We will also have better coverage of freshdesk monitoring/response since we are covering more timezones by combining a western and a central timezone. (One day we'll hire someone in Australia and then the fun begins!)

What do people think?

**Comment by damianavila** [comment]
I think it is a sensible idea!
I am actually in the middle of PT/EU zones so I could play in both teams 😉. In fact, I am slowly migrating to start working on my very early mornings - my time - which would effectively put me in an EU-like sort of zone... but again, in general, I think this is a good idea.

**Comment by choldgraf** [comment]
I think this is a great idea - spreading our support time across time zones would be a good way to minimize gaps in availability.

Though I am going to be on a European time zone starting around late April, so things might be a little less-balanced then. Over time, we can try to keep this balanced though.
