### ISSUE TITLE
Strategy / philosophy for engaging with open source projects

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#395]
### Background and proposal

One of 2i2c's core tenets is the development and operations model that we follow. I often describe this as:

1. **Curate** a collection of open source tools that are useful for a use-case.
2. **Customize** those tools and integrate them together for the use-case.
3. **Contribute** back to the communities that underlie those tools.

Doing number 3 requires that we have an understanding of how to interact with open source communities, and also often means that we have **status** in those communities. An example of this is the Jupyter community, where all of 2i2c's team members are also "Distinguished Contributors".

Having status and power within a community also means there is the potential for conflicts of interest and abuse of power. So we should make it clear what is 2i2c's strategy regarding the communities we work with.

We want to both:

1. Recognize that our connection to jupyter is part of 2i2cs strategic plan and value
2. Recognize that we are thoughtful about the potential negative implications of this, and share how we try to ensure that our actions are in line with jupyter's mission

### Proposal

We should define a strategic plan for how we engage with open source communities as a part of our work. This should answer questions like:

- Why are open source communities important to 2i2c's mission?
- How does open source code intersect with our day-to-day development and operations?
- What kinds of contributions do we want our team to encourage to make in these communities?
- What policies and practices do we follow to make this happen effectively?
- Are there any particular open source communities we care about more than others?
- What is our strategy for ensuring we do this well and without negative outcomes?

### Actions and updates

- [ ] Brainstorm a lightweight strategy / policy towards open source
	- [Draft open source strategy](https://docs.google.com/document/d/1RpjNWq4r376CEoMkyX188aX5FtH-sF-ht3AboN65w9I/edit?usp=sharing)
- [ ] Sharpen the language and get down to 1-2 pages.
- [ ] Convert into our team compass

**Comment by damianavila** [comment]
This is lovely content for the page we should write exposing/presenting our position on the matter.
