### ISSUE TITLE
Define Key Performance Indicators (KPIs) for 2i2c

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#407]
### Context

In recent @2i2c-org/steering-council meetings, we have consistently gotten feedback (particularly from @rabernat) that we should define some **Key Performance Indicators** of 2i2c. [Key Performance Indicators](https://en.wikipedia.org/wiki/Performance_indicator) are metrics that we explicitly track to reflect our success in a given area. These are generally dependent on a **functional area** and the operations/goals of that area.

Having metrics to track will help us have an objective and potentially quantifiable way to watch our progress over time, and to define "what is important" to subsets of 2i2c.

This is related to the following issue, though this is more about deciding what we want to quantify and measure, rather than the objective we set for ourselves.

-  https://github.com/2i2c-org/team-compass/issues/206

### Proposal

We should define a basic set of KPIs for 2i2c. This should be split across major functional areas, and we should generally try to keep the number of KPIs as small as possible. We can always refine and add later if need be.

I'd propose that we start with the following functional areas, and try to define one or two KPIs for each:

- Development (e.g., development issues resolved)
- Operations (e.g., service level indicators, time to incident resolution)
- Support (e.g., average time to ticket resolution, average time between user/agent response loop)
- Sustainability and Sales (e.g., new contracts, number of communities served, number of unique countries w/ a community)
- Community engagement (e.g., average length of community retention, positive feedback in community surveys)

### Keep it simple

There are a lot of ways to use KPIs (e.g., defining targets to shoot for, thresholds that trigger different behavior, etc) but I suggest we start by just _defining_ some KPIs and tracking them. Over time, we can refine our processes and add more complexity as needed.

### Checkpoints

https://github.com/2i2c-org/team-compass/issues/407#tasklist-block-ee5f3bf6-577c-4c94-a52f-d860c69c157b

**Comment by rabernat** [comment]
Thanks for getting this started. I support it a lot! I think it's useful to just brainstorm a bunch of ideas for KPIs at this stage and then narrow down to a few key ones.

Here are some things I am interested in that are even simpler than what you listed

- Hub-related
  - Number of hubs
  - Number of users
  - Number of hours per month of active user sessions 
- Financial
  - Monthly revenue from invoices
  - Monthly operational costs (broken down into salaries and cloud expenses; are there any other major categories?)
- Upstream Jupyter Development
  - Number of bugfix PRs contributed by 2i2c team
  - Number of new feature PRs (I know counting PRs is probably not the best metric, but you gotta start somewhere)

**Comment by damianavila** [comment]
I agree about the need to measure ourselves in all those different functional areas (mentioned above).
I also agree it is important to start as simple as possible and start generating the data sooner than later.

**Comment by choldgraf** [comment]
### Update: team meeting notes

We had a team meeting where we brainstormed several more ideas around current and potential KPIs to track. Cleaned up notes from that meeting can be found here:

- [KPI meeting notes](https://docs.google.com/document/d/1HoNX8T8IQ1uhS2ryi1r9iS-nSbPT1b1Y7HsjosbHme8/edit#heading=h.qbwifytjz2j8)

### Next steps

There was a lot of different stuff we could potentially track, but we should start with something that is minimally-useful and doable right now. Over time we can define and track more complex KPIs, particularly those that are more directly tied to impact, but I propose that for now we do the following:

- Define two types of KPIs:
	- Impact KPIs: Reflect actions that we take for the communities we work with
	- Sustainability KPIs: Reflect our financial information about burn rate, cash on hand, etc.
- Impact KPIs to track:
   - Number of communities served.
   - Monthly Active Users.
   - 10th, 50th, and 90th percentils of MAUs per hub.
- Sustainability KPIs:
	- Monthly revenue, broken down by category (grants, development contracts, cloud service contracts)
	- Monthly operational costs, broken down by category (engineering, partnerships and community, executive, fiscal fee, services)
	- Cost per community (operational costs / number of communities served)

I'll update the top comment and give myself a deadline to at least tackle a subset of these KPIs by then.

**Comment by choldgraf** [comment]
I'm going to close this one, as we have dashboards that describe the major KPIs described here at the following address:

https://2i2c.org/kpis 

I think that we'll still need to build more team practices around these KPIs, and potentially add or refine them, but let's consider this initial effort complete and we can start new initiatives on this in the future.
