### ISSUE TITLE
Write a blog post on new CI/CD infrastructure

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#411]
wohooo! what an impressive leap forward for our infrastructure! @sgibson91 I wonder if you'd be interested in working with me on a short blog post that explains some of these changes? there were some folks on twitter who were intrigued about our GitHub actions :-)

_Originally posted by @choldgraf in https://github.com/2i2c-org/infrastructure/issues/879#issuecomment-1098511019_

**Comment by sgibson91** [comment]
I created an outline with major points here: https://hackmd.io/@sgibson91/SJankuBNq

cc: @choldgraf

**Comment by consideRatio** [comment]
I got very happy about the last CI run that had all green lights and wrote about it in `#wins` on our slack: https://2i2c.slack.com/archives/C02B7RS6YV8/p1649974397476719

**Comment by choldgraf** [comment]
I've put together a quick blog post from that excellent HackMD at this PR!

- https://github.com/2i2c-org/2i2c-org.github.io/pull/101
