### ISSUE TITLE
Make role-change events (support, facilitator) more visible/explicit

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/team-compass#415]
### Context

We currently have issues being opened by a bot every two weeks to pass over the support steward role to the next team member.
But the bot opens generic issues and it has to be a real person that edits the bot's message and pings the right next person to serve in the support steward role.

Recently, in https://github.com/2i2c-org/team-compass/issues/414 I only realized that it was me that was supposed to be the next support steward after 3 days the issue was opened because we probably all missed or the notification from the bot.

### Proposal

I don't know which is the best solution to this, but I see a few possible things to try:
- find a way to be more explicit about role changes
- make more noise when a role should change persons?
- make the bot smarter
- or maybe even decide which person is responsible for editing the bot's message

### Updates and actions

- @sgibson91 mentioned in https://github.com/2i2c-org/team-compass/issues/414 some Slack standups that we could use for these role changes and agreed to be assigned to this issue in order to try prototyping that solution.
Thanks @sgibson91 ✨

**Comment by consideRatio** [comment]
Thanks @GeorgianaElena for opening this, I realized I've also forgot to open an issue related to this as decided I'd do in the team meeting on tuesday. For now, this issue that issue. For reference, below are the notes from the team meeting.

Some summarizing notes

1. We appreciate having calendar entries made so we can plan ahead of time
2. We appreciate if we could be pinged in slack about when transitions happens
3. We appreciate not having to make calendar entries or slack pings manually
4. We would be fine removing the automated creation of the support steward ticket
5. We are unsure what source of truth can/should be used to keep track of who is the support steward/meeting facilitator. This choice influences any bots making slack pings or updates to the calendar if the calendar isn't the source of truth etc.
6. Sarah was willing to look into previous solutions to similar challenges for inspiration on how to proceed.

<details>
<summary><em>Click to expand: meeting notes about this</em></summary>

>### About github issues and calendar entries for meetings
>
>There is a GitHub issue opened for team sprints, but also calendar entries, and hack-md notes. Do we keep opening issues automatically?
>
>Sarah suggests that we have a calendar and a bot that reminds and asks for an acknowledgement about becoming a meeting facilitator and support steward.
>
>GitHub issues are now opened without being coupled with a specific user, and that is the core issue of the reminder to acknowledge as we have it ow.
>
>Chris, three purposes:
>- General its happening reminder
>- Specific person 
>- Storage space for agenda / todo-list etc.
>
>Proposal from Sarah:
>
>- Move these two issues to the same process we use for monthly meetings
>  - Support steward transition
>  - Bi-weekly sync issues
>- Add a Slackbot (#team-updates) that sends reminders to specific people that they need to fill some role for the next meeting.
>
>Erik additional purpose:
>- Able to see whats going to happen ahead of time etc
>
>Sarah knows its possible to setup the desired automation, and will get in touch with collegues to verify this.
>
>Chris notes its also manual toil associated with adding google calendar entries for support steward / team facilitator.
>
>Chris suggests that if we had a central place where we know everything of relevance, it can be used to drive the automation - also of adding entries in the calendar etc.
>
>Damián empasize the value of being able to plan multiple months ahead of time.
>
>Action points:
>- Create an issue to represent the wish to automate with short term goals and a background of the vision. Erik will do it.

</details>

**Comment by sgibson91** [comment]
I am experimenting in this repository https://github.com/2i2c-org/team-roles-geekbot-sweep

**Comment by choldgraf** [comment]
that would be excellent!

**Comment by sgibson91** [comment]
I have rolled out the slackbot that assigns monthly team meeting facilitators to the whole team and debugged the updating issue in CI, so please keep an eye out for those slack messages!

I will roll out the support steward bot after Yuvi and Damián have resolved their role swapping

**Comment by choldgraf** [comment]
ooooh nice, I am looking forward to not having more issue noise!

**Comment by sgibson91** [comment]
I started playing around with the Google Calendar API today and got a [little script](https://github.com/2i2c-org/team-roles-geekbot-sweep/blob/gcal-api-integration/examples/quickstart.py) working to create an event in my personal calendar 🙌🏻 Next steps are:

- Figure out how to run the script without needing OAuth flow for CI/CD - probably a service account
- Add logic for creating team role events:
  - Meeting Facilitator: monthly (whole month)
  - Support Steward: fortnightly on Wednesdays
- Port over to the `two-eye-two-see` project
- Automate in CI/CD
  - Rolling update: As one cycle ends, create the next cycle at the tip of the queue so there are always events in the Team Role calendar for the next 6 months/year
  - Quick population: Quickly populate a 6 month/year-long timeframe (like "initialising" the calendar before the rolling update workflow takes over)

**Comment by damianavila** [comment]
Niceeeee...

**Comment by choldgraf** [comment]
Amazing! So would we still treat the roles calendar as the "source of truth" once it has been populated with events? I ask because sometimes people swap roles and such, and it seems like the calendar is the only thing with the flexibility to do this in a non-hacky way.

**Comment by sgibson91** [comment]
@choldgraf Yes, but the slackbot will likely not take notice of the calendar. So if you are pinged by the slackbot, but you have changed the calendar, best thing to do is probably reply to the slackbot tagging the person you have swapped with.

**Comment by sgibson91** [comment]
I have opened https://github.com/2i2c-org/team-roles-geekbot-sweep/pull/48 which will make the bot read the next team member from the calendar, and only fallback onto the data in the team-roles.json file if no calendar entry is available, before creating the standup app. So this elevates the calendar to the source of truth for the bot as well as us. However, I will wait until after various role swaps have ended before deploying.

**Comment by sgibson91** [comment]
Yep, sounds good to me!

Here's what I understand so far:

- You are in the role until Tue
- Erik is currently in the role
- So beginning the role on Wednesday would be Georgiana?

**Comment by damianavila** [comment]
Correct!

**Comment by sgibson91** [comment]
Ok, I have updated all the roles so that Georgiana will be pinged by Geekbot next Wednesday. I will enable the automation and populate the calendar with the upcoming roles.

**Comment by sgibson91** [comment]
I opened https://github.com/2i2c-org/team-compass/pull/474 to disable the automatic opening of support steward transfer issues

**Comment by sgibson91** [comment]
I have opened https://github.com/2i2c-org/team-compass/issues/475 as a related, but not critical, discussion point

**Comment by sgibson91** [comment]
All of the PRs over on https://github.com/2i2c-org/team-roles-geekbot-sweep have now been merged so I will close this issue as complete. We can iterate in new issues either in https://github.com/2i2c-org/team-roles-geekbot-sweep for technical implementations, or here for process-based iterations
