### ISSUE TITLE
Commit to holding our team meeting on a set date

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#417]
### Context

At the minute, our team meeting happens every 4 weeks. Which means the meeting creeps earlier into the month as the year passes since not all months have four weeks. When trying to create a standup bot that will more reliably notify the team member who will be the facilitator for the meeting (related https://github.com/2i2c-org/team-compass/issues/415), syncing up these migrating periods is really difficult without complex logic (especially since the period of the standup is not available to be set via the API! The default is weekly and needs manually updating in the dashboard!)

### Proposal

Instead of "every four weeks", we commit to holding our team meeting "every 3rd Tuesday of the month". This will prevent the date it happens creeping through the month and means I don't have to write complicated, calendar-based logic to sync up the standup to provide the facilitator enough warning of their role.

### Updates and actions

- [ ] @2i2c-org/tech-team votes on above proposal
- [ ] If proposal passes vote, change the repeat frequency of our team meeting to "every 3rd Tuesday of the month" in the Team Calendar

**Comment by choldgraf** [comment]
That makes a lot of sense to me - as long as the day of the week is set, and the meeting is predictable in general, that works for me 👍 

I think things like the sprint sync meeting are more important to have on a fixed schedule, but team meetings are fine IMO

**Comment by sgibson91** [comment]
Yeah, this is for the monthly team meeting only since Damián is our de-facto facilitator for the sync meeting as PM :)

**Comment by damianavila** [comment]
My positive vote on this one!

**Comment by damianavila** [comment]
@2i2c-org/tech-team can you please quickly vote on this one? Thanks!

**Comment by choldgraf** [comment]
@damianavila I see 👍 from myself, you, @GeorgianaElena and @consideRatio so I think the only other person we're missing is @yuvipanda

**Comment by sgibson91** [comment]
I think we have consensus on this so I will just action it :)

**Comment by sgibson91** [comment]
"Monthly every 3rd Tuesday" wasn't an available option, so instead I went with "Monthly every last Tuesday". I also have not changed the May meeting, this change will affect the June team meeting onwards.

**Comment by damianavila** [comment]
I do see two monthly meetings in May calendar, more details in Slack.

**Comment by sgibson91** [comment]
Sorted.

**Comment by yuvipanda** [comment]
Apologies for not getting to this earlier, am happy with this too!
