### ISSUE TITLE
Meet with a Google Cloud rep?

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#430]
### Context

A representative from Google Cloud reached out and asked if we'd like to meet with them just to discuss how we're using the infrastructure. It might be a good opportunity to ask questions about our use of Google Cloud and see if there are better ways of using it.

Here's their text:

```
Hi there - we'll keep this short!


My name is XXX, part of your Google Cloud Platform account team, and I’m interested in discussing your needs. Please respond or schedule time with me here [I omitted the link], or forward this message to a more appropriate contact.

I want to check in on your usage of our products (Kubernetes Engine, Cloud Storage, Compute Engine) and discuss your digital transformation needs.

I can also connect you with a member of our customer team to help you ensure International Interactive Computing Collaboration cloud‘s infrastructure is optimized around cost and performance.


I look forward to hearing from you,
```

### Question

Anybody interested in taking this meeting? I don't think I have the capacity or the knowledge to do it, so welcome anyone else that would like to join. If you're interested let me know here and I'll connect you with the person.

**Comment by yuvipanda** [comment]
I could do it but it would be nice to have someone else as well to build capacity.

**Comment by damianavila** [comment]
I smell a little bit of a way generic email here (I just want to prevent @yuvipanda - and everyone else who wants to join him on this meeting -  to lose precious time 😉 but feel free to ignore me if you think otherwise).

**Comment by yuvipanda** [comment]
I agree it's pretty generic, but i think this is the escalatioin pathway when we need more quotas. Hence...

**Comment by damianavila** [comment]
> i think this is the escalatioin pathway when we need more quotas. Hence...

That's a good point!

**Comment by damianavila** [comment]
Thanks for taking the time to meet with them, @yuvipanda.
Closing this one now.
Feel free to add later down the road any further info that might be useful in the future (ie, contact for the account rep).
