### ISSUE TITLE
CUIT account due to expire - will lose access to Pangeo JupyterHub if not renewed

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#433]
### Context

I received the below email claiming my Columbia CUIT account is due to expire. The only reason I have this account is to access the GCP project that the Pangeo JupyterHub is deployed to. We have also had _many_ discussions throughout the team about how having separate university-based accounts for individual deployments is neither scalable nor sustainable.

![Screenshot 2022-06-17 at 16 13 43](https://user-images.githubusercontent.com/44771837/174328091-f414751b-b478-4244-88dd-889350f1b703.png)

### Proposal

If the proposal in https://github.com/2i2c-org/meta/issues/279 is granted to deploy a Pangeo Binder to a GCP account that we own/manage and bill Columbia for, I would very strongly suggest that we also move the JupyterHub we are already running for the sake of ease.

### Related issues

- https://github.com/2i2c-org/team-compass/issues/353
- https://github.com/2i2c-org/team-compass/issues/184
- https://github.com/2i2c-org/team-compass/issues/136
- https://github.com/2i2c-org/meta/issues/279
- ...

**Comment by rabernat** [comment]
I would like to resolve this for all the team members, but right now I am just working on your UNI. Do we have a list of everyone who needs renewal?

**Comment by sgibson91** [comment]
So far, Yuvi is the only other person who reported the renewal email.

I believe @damianavila and @GeorgianaElena are the only others on the team with UNIs. Folks can you provide Ryan with your UNI IDs please?

**Comment by damianavila** [comment]
`da3008` in my case.

**Comment by yuvipanda** [comment]
I'm `yt2796`

**Comment by damianavila** [comment]
Super!
It is intriguing to me that I have not received any notification (neither the first one nor the extension).
@GeorgianaElena is that the case for you as well?

**Comment by sgibson91** [comment]
@damianavila and @GeorgianaElena you won't have received an expiration notification from them, because you got your accounts after me and Yuvi, therefore your cycle is offset from ours :)

Also, it wasn't really a "your account has been extended" notification type of email. Ryan just cc'd me into the email thread with an administrator at LDEO who extended the account and it was an email from them saying "I have completed this task".

Generally I'm a bit annoyed with this scenario. CUIT told me my email address was being expired because my "role at LDEO finished on the 17th". I had no idea I had a role at LDEO and I didn't receive any indication that that "role" was expiring either. It's university admin/politics that I don't really understand and is a big time sink (for a lot of people) to sort out.

**Comment by damianavila** [comment]
> It's university admin/politics that I don't really understand and is a big time sink (for a lot of people) to sort out.

Yep, indeed. And Columbia is not alone. It is a spread "practice" among all the Universities I have interacted with...

**Comment by damianavila** [comment]
Closing this one since now @sgibson91 and @yuvipanda UNIs were extended.
We can reopen later down the road if this is eventually impacting others.

**Comment by sgibson91** [comment]
<img width="430" alt="Screenshot 2022-08-17 at 16 15 11" src="https://user-images.githubusercontent.com/44771837/185177336-46f2a9bc-9525-4099-890c-c484d5603e37.png">

I just got pinged _AGAIN_ - I thought the renewal was supposed to be good for a year?

**Comment by choldgraf** [comment]
huh, the date is even later than last time so something indeed got updated in their database, it's not just an accidental re-send of the same notice.

Another cross-ref to the incommon issue since I think that would resolve issues like these:

- https://github.com/2i2c-org/meta/issues/348

**Comment by damianavila** [comment]
I am reopening this one again until we know more about this one. @sgibson91 did you ping them again about this situation?

**Comment by sgibson91** [comment]
Yeah, it got renewed again so can be closed.

**Comment by sgibson91** [comment]
I'm really regretting not mentioning who the contact was in this issue as the email thread is gone and no one useful is showing up in my contacts

* https://github.com/2i2c-org/meta/issues/666
