### ISSUE TITLE
Document a reimbursement process

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#442]
### Context

In some cases team members will need to purchase things (tickets, travel, equipment, etc) and file reimbursements for them. We don't currently have a clearly-defined process for what people should do to make this happen.

### Proposal

We should get guidance from Code for Science and Society about the reimbursement process that they recommend for:

- Employees of their FSPs
- Contractors of their FSPs

We should also define our own policies for reimbursement, such as when we require "approval" for certain purchases.

**Comment by choldgraf** [comment]
### Update from Page

CS&S said they often use this process:

- For employees, we submit reimbursements via Expensify
- For contractors, we ask them to submit a separate line item on their monthly invoice, called `Reimbursement - <item>`

And for contractors, we'll need to amend each contract with this language:

```
Expenses: Organization agrees to reimburse Independent Contractor for all expenses reasonably incurred in the performance of the Engagement and approved by Organization in advance, upon presentation of supporting receipts and documentation.
```

**Comment by damianavila** [comment]
CS&S outlines a good and straightforward process, IMHO.
