### ISSUE TITLE
[suggestion] Ask Erik if he'd like to leave the support steward rotation

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#458]
### Context

For the past several months, @consideRatio has been serving in our Support Steward rotation with the other team members. He is funded by an NSF grant for Jupyter Meets the Earth (JMTE) at Berkeley, and we had originally set this up because his plan was to run the JMTE infrastructure via 2i2c. However, [that process has taken longer than expected](https://github.com/2i2c-org/infrastructure/pull/436) and there are still many changes that need to take place to make it possible.

That means that Erik is effectively doing support + operations for the JMTE hub by himself, and _in addition_ is working with the 2i2c engineering team on our infrastructure as a volunteer rather than on time on the JMTE grant.

I feel like this is not a fair request to make of Erik, and generally isn't a realistic ask for people who don't have any paid time to work on 2i2c's infrastructure directly.

### Proposal

I propose that we ask @consideRatio if he would like to roll off of the Support Steward team rotation, assuming that he has been doing this work as a volunteer and not on paid time. We could revisit this if the JMTE infrastructure starts to use 2i2c's deployment CI/CD and support mechanisms (so that Erik would then get support on that hub as well).

I've also opened up an issue to discuss the broader question of what responsibilities we'd like to give people who are not on paid time working with 2i2c:

- https://github.com/2i2c-org/team-compass/issues/459

**Comment by consideRatio** [comment]
Thank you Chris!

If its acceptable, I'd like to rotate out so I don't schedule for being a support steward again soon. Is there an action point on me with regards to that? I saw that #505 was opened and wondered if I should do something similar?

**Comment by choldgraf** [comment]
- I did the same thing for you @consideRatio : https://github.com/2i2c-org/team-compass/issues/506

I don't have time to follow those steps though. Can somebody else help with this?

**Comment by damianavila** [comment]
@consideRatio was offboarded here: https://github.com/2i2c-org/team-compass/issues/506.
