### ISSUE TITLE
Create a `community` repository to track our community engagement and guidance work

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#468]
### Context

Currently, we have three public repositories to track our work:

- `infrastructure/` - for cloud infrastructure work
- `team-compass/` - for our team coordination, planning, and organizational structure/policy
- `docs/` - for user-facing documentation for the service

However, there are many new things that we need to work on related to community engagement, and that don't quite fit into these three repositories. For example:

- Writing blog posts for communities
- Planning presentations and resources around events
- Planning content creation for workshops etc

Right now, I think a lot of this content ends up going into `team-compass/`, but that doesn't quite feel right to me, as this is meant to be a "meta" repository that focuses on team processes etc.

### Proposal

We could create a repository that is dedicated towards our "community guidance" efforts at 2i2c. This could either host its own infrastructure (like a documentation site) or it could just be a place to track these kinds of issues so that they don't clutter up the team compass / infrastructure / etc stuff. The repository would primarily be a place for @2i2c-org/partnerships-and-community-guidance folks to work and coordinate, but would be open to anybody else as well.

I'm curious if @jmunroe or @colliand would find something like this useful, or if it would be an unnecessary fracturing of our planning workflows. Would you recommend a different place to track this kind of work? Or is `team-compass/` + `docs/` enough? What do you think?

**Comment by jmunroe** [comment]
@choldgraf  and I had a chat on this. While I like the idea of documenting more of our commuity building and engagements through GitHub, I don't think we need yet another repo at this time.  

We can revisit this idea again if we start clogging up the `team-compass/` or `docs/` repos too much.
