### ISSUE TITLE
Deploy and operate a hub for the 2i2c team

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#472]
### Context

Currently we do not have a hub that is dedicated for our own team to use, we only deploy hubs for other communities, and have some hubs that are "community-agnostic" (like `staging`, `demo`, etc). However, there are a few cases where it might be useful for us to have our own space to do work via the workflows we enable. For example:

- Dogfooding the workflows so that we are familiar with them and get intuition for how we'd like them to improve
- Having a space for running analyses that are relevant to 2i2c
- Having a space that we can use to collaborate with one another around analysis
- Being a place to test out new changes and enhancements from a user perspective

### Proposal

We should deploy a hub for our own team to use. It should be accessible to anybody on the 2i2c team, and would run a DaskHub-like setup, with as many features turned on as possible. It would live at a place like:

```
hub.team.2i2c.cloud
```

Longer-term, we might consider deploying a *cluster* for our team, in order to learn more from a user's perspective what it feels like to use this workflow as well.

**Comment by jmunroe** [comment]
I agree with this.  We should create a "New Hub" request to get this going (based on conversation with @damianavila )

Would this hub also be appropriate to "show-and-tell" to potential new users and communites?

**Comment by choldgraf** [comment]
> Would this hub also be appropriate to "show-and-tell" to potential new users and communites?

Note that we do have this hub: https://demo.2i2c.cloud/hub/login?next=%2Fhub%2F

**Comment by jmunroe** [comment]
Yep - the docs reference "demo.pilot.2i2c.org" :
> 
> About our demo hub
> 
> The 2i2c operates a hub for demonstration and experimentation at demo.pilot.2i2c.org. This hub is primarily for the 2i2c team to try things out, and it may change or break occasionally. Team members should feel free to experiment with this hub and try out new functionality and features they’d like to show off to others.

demo.2i2c.cloud is in the table of hubs, but falls on "page 2" of 50 hub pagination so it is not obvious.

**Comment by damianavila** [comment]
I think the demo hub is different from an internal 2i2c hub. One could argue that a 2i2c hub could be used to "show and tell" and "demo'ing" things... but I think we are talking about different sorts of hubs. Do we agree on that?

**Comment by jmunroe** [comment]
With the deployment of 

- https://github.com/2i2c-org/infrastructure/issues/1949

I think we can close this issue.  https://researchdelight.2i2c.cloud I think is the perfect spot for anyone internal to 2i2c to actual use the hub if needed!

**Comment by choldgraf** [comment]
Can we close this issue once that hub is documented in our team compass?

**Comment by damianavila** [comment]
Btw, I am not reopening this one since we already have a child issue (reference above) to capture the documentation piece.
