### ISSUE TITLE
[Proposal] Create @support-stewards and @meeting-facilitators Slack teams

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#475]
### Context

I built https://github.com/2i2c-org/team-roles-geekbot-sweep to allow us to create geekbot standups to notify team members when they should be serving in a specific role. This uses the `@tech-team` team on Slack as our source of truth for who serves in these roles.

However, if https://github.com/2i2c-org/team-compass/issues/458 is accepted, then we would have to remove Erik from the `@tech-team` Slack team, and he would also stepping down as a possible meeting facilitator as well.

Regardless of whether or not Erik chooses to fully step down from all these responsibilities or just the support steward, we should make it more flexible for two scenarios: i) anyone to be a meeting facilitator but not a support steward (or vice versa), and ii) allow anyone not in the tech-team to take up these roles, e.g., folk from leads and partnerships if they wish, or a dedicated support team if and when we build one.

### Proposal

I propose that we create two new teams in our Slack workspace (naming convention is up for negotiation!):

- `@support-stewards`: this team will be the source of truth of folk who agree to serve in the support steward role
- `@meeting-facilitators`: this team will be the source of truth of folk who agree to serve in the meeting facilitator role

This will decouple these roles from membership of `@tech-team` and allow folk to choose which roles they would prefer to serve in (when we're big enough for such choices to be available).

### Updates and actions

If we agree this is a good idea, then the technical steps are:

- [ ] Create the appropriate teams in the Slack workspace and add the correct members
- [ ] Update the TEAM_NAME env var in the CI/CD workflows of the team-roles-geekbot-sweep repo to the appropriate team names

**Comment by damianavila** [comment]
It makes total sense to me to add more granularity here.

**Comment by choldgraf** [comment]
This is a cool idea - we could even auto populate some headshots to show the latest members of each group in our team compass or something. 👍

**Comment by sgibson91** [comment]
Yeah, I think we might be able to pull people's Slack profile pics

**Comment by sgibson91** [comment]
I am not an admin on the workspace so I can't action this proposal btw https://2i2c.slack.com/account/workspace-settings#admins

**Comment by damianavila** [comment]
Somehow it seems I am actually an admin! And I gave you admin powers, @sgibson91.

<img width="565" alt="Screen Shot 2022-08-21 at 18 41 28" src="https://user-images.githubusercontent.com/1640669/185813957-f68d1f0d-37ea-4d1c-a118-ad6a5431b6ac.png">

Use them wisely... 😜 

![responsability](https://user-images.githubusercontent.com/1640669/185813968-96e05ad7-c1c3-4efb-afce-689bc1f9b246.jpeg)

**Comment by damianavila** [comment]
> (I haven't added James yet, should we?)

I think so, at least for now...

**Comment by sgibson91** [comment]
Done!
