### ISSUE TITLE
Simplify and standardize our GitHub issue labels

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#484]
### Context

Right now we have a mishmash of a bunch of different **github labels** across our repositories. Some were created as part of experiments in team / project management, others were created more organically as people had ideas for things to track.

I don't think that they are being utilized super heavily, and I wonder if one problem is just that there are so many of them, and they don't particularly follow a clear system or structure.

As I was working on @damianavila's "2i2c update post", I really liked the "changelog of PRs" that he made. Since we do almost all of our actions in GitHub, it got me wondering if we could generate a "changelog of 2i2c's activities over the last N months" semi-automatically by categorizing the issues/PRs that we've closed based on labels, and generating a summary with something like [github-activity](https://github.com/executablebooks/github-activity).

### Proposal

I want to experiment with **significantly simplifying our labels across all repositories**. What I'd suggest doing is something like the following for all repositories:

There are two kinds of labels:

- High-level functional area (e.g., Cloud Ops, Development, Partnerships, Community, Administration, Finance, and Strategy)
- Issue action category (e.g., enhancement, bug, task, incident)

And we just use that set of labels as a starting point across all of our repositories, re-placing our current labels with these new ones as-needed. All other kinds of labels we would just remove since we're not using them much anyway.

I'd hope that this would make things much more standardized and easier to reason with. But I wanted to ask if others had any objection to something like this.

**Comment by damianavila** [comment]
I totally concur with the intended simplification proposed by @choldgraf on this issue.

**Comment by damianavila** [comment]
@2i2c-org/tech-team, WDYT?

**Comment by choldgraf** [comment]
In my opinion this one is now awaiting implementation. I think the next steps are to:

- define the labels we use
- create some script to synchronize them across our repos

Then we can see how it goes and spot check improvements as needed

**Comment by sgibson91** [comment]
From an engineering standpoint, I care more about the assignment (who's working on what? Is it me?) than I do the labels. But I understand how the C-suite and team leads would use labels to quickly overview what kind of work was happening and where. I would therefore suggest that we define the labels that are most useful for this purpose for this audience. And I would empower Chris and others to be opinionated about that.

**Comment by choldgraf** [comment]
This has now been done!

- https://github.com/2i2c-org/.github/actions/runs/3067293527
