### ISSUE TITLE
CZI Open Science 2022 - Planning and coordination

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#493]
### Context

The [Open Science team at CZI](https://chanzuckerberg.com/science/programs-resources/open-science/) is hosting their annual CZI Open Science meeting from **Sunday, September 18th - Wednesday, September 21st, 2022 in Santa Rosa, California**. This is a place where grantees across the Open Science spectrum come together to discuss all kinds of things.

Attendance at the meeting was for individuals who had been funded previously by CZI grants, @sgibson91 is going to be there representing the JupyterHub EOSS grants that we received, and @choldgraf will be there to represent the 2i2c core funding.

I believe that @yuvipanda and @fperez may be there as well since they are in the area and connected to a few of these efforts.

I don't have any specific proposals here, but wanted to note the event in case it sparks any ideas for coordination and planning. For example, if many of us will be in the same place at once, this may be a good opportunity to connect with other a bit or to do some brainstorming!

### NumFocus meeting as well

Note that there's also a NumFocus meeting on the **Thursday and Friday** following the CZI meeting, in the same location. @choldgraf may be attending this as well but I'm not positive.

**Comment by sgibson91** [comment]
I'm really excited to be co-located with so many cool people!

I wonder if this is a good space to generate some ideas about a Showcase/Do-athon/Birds of a Feather session we could present?

(I can copy-paste the contents of the email describing those activities if it would help)

**Comment by jmunroe** [comment]
Given that there will be colocation of several 2i2c folks, is there any interest in organizing a 2i2c mini-retreat before or after these meetings?  Specifically, if @sgibson91 and @choldgraf have already made the trip effort to get to the US west coast, perhaps we should take advantage of the opportunity. Even though I am not part of the CZI meeting, I'd be willing to make the trip to CA to be there in-person.

(Is the NumFocus meeting also a closed meeting like the CZI one?)

**Comment by sgibson91** [comment]
> organizing a 2i2c mini-retreat before or after these meetings

FYI, my flight is being booked by CZI and I don't have a lot of time pre-meeting (arriving Saturday the 17th). My flight home is the following Saturday and I haven't as yet made any bookings about what to do between the CZI meeting and then, so I could do a mini-retreat on the Thursday/Friday. This is also my first time to the US though so I have a desire to do a few touristy things too 😄 

This may or may not influence Chris's decision to attend the NumFOCUS meeting 😉

**Comment by yuvipanda** [comment]
I also maybe wanna try sneak myself into the numfocus meeting somehow? Not sure how.

There's also a NASA meeting I might end up being able to go to on the east coast right after this, so maybe not the best time either unfortunately.

**Comment by choldgraf** [comment]
For what it's worth, unless I _have_ to attend some session at one of these events, I will prioritize having a chance to meet and speak with you all during the week.

If we can't find a time for like a dedicated team mini-meeting, I think we should start finding a time to do so in the next few months. It has been way too long since we have seen each other in person (never, in some cases)

**Comment by damianavila** [comment]
> If we can't find a time for like a dedicated team mini-meeting, I think we should start finding a time to do so in the next few months. It has been way too long since we have seen each other in person (never, in some cases)

Definitely!!

**Comment by GeorgianaElena** [comment]
Is everyone going to be there except for me? 😢

**Comment by choldgraf** [comment]
This is now finished and you can find highlights from it at the issue below!

- https://github.com/2i2c-org/meta/issues/388
