### ISSUE TITLE
Define Monthly process to Calculate cloud costs for dedicated clusters on Google Cloud

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#498]
### Context

For some communities, we pay the cloud costs directly, with the intent of passing through those costs to the communities we work with each month.

Currently, we do not have a defined way to incorporate cloud costs into our monthly invoicing process. This makes it difficult for @colliand to generate the necessary information that Page @ CSS needs to send the right invoice.

As a start, we should define a _manual_ process by which we should generate costs for monthly invoices. I recently figured out how to define the cloud costs incurred by each cluster in google cloud. Here's a quick rundown for reference by the @2i2c-org/partnerships-and-community-guidance team.

#### For communities with dedicated clusters

Here's a way to get monthly costs, broken down by the `project`. Assuming that projects are unique for each community, we can easily determine how much cloud spend they have.

Go to the billing page for Google cloud (`https://console.cloud.google.com/billing`). This will least _all of our billing accounts_. Each one is attached to a credit card or to an allotment of credits.

The `two-eye-two-see` billing account is the one we use for communities with dedicated clusters where we pay the cloud bill. Select it like so:

![image](https://user-images.githubusercontent.com/1839645/187202410-04b28528-0c96-42bd-a79d-539f6a68ca5d.png)

(note that there's also an account called `two-eye-two-see`, which is a dedicated billing account for the m2lines project that we need to migrate over, see https://github.com/2i2c-org/infrastructure/issues/1651)

you'll be taken to a page that describes the costs / billing for this billing account, it looks like this:

![image](https://user-images.githubusercontent.com/1839645/187202592-aba3c831-7dbd-40f4-8801-c1837e124881.png)

For a quick overview of the cloud costs being drawn for each of our projects, click on `Reports`. Below is an example showing a few projects, the two most important are:

- (in blue) The `two-eye-two-see` project is the collection of hubs that are running on our shared 2i2c cluster. Calculating billing for them is a bit more complicated.
- (in red) The AWI cluster project.

<img width="960" alt="chrome_iJPCR0ZZhG" src="https://user-images.githubusercontent.com/1839645/187205316-2fe5594c-2d7a-4ad2-bd34-d3971c3b6b71.png">

To calculate the exact costs, go to **`Cost Breakdown`**. This will give us a more detailed breakdown of costs by project. You can choose an invoice month and download a CSV of the billing data broken down by project:

![image](https://user-images.githubusercontent.com/1839645/187205982-d7faed31-3c6a-4f57-b357-005cdd5328b6.png)

**Comment by pnasrat** [comment]
The billing automation written by @yuvipanda  and built upon in  the billing deployer module handles dedicated and shared GCP billing

https://github.com/2i2c-org/infrastructure/tree/master/deployer/billing
