### ISSUE TITLE
Offboarding from Support Steward: @consideRatio

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#506]
**Role(s) this person will be stepping away from:**

- [ ] Meeting Facilitator
- [x] Support Steward

### Checklist

- Remove them from the appropriate [Slack usergroup](https://2i2c.slack.com/admin/user_groups)
  - [ ] `@meeting-facilitators`
  - [x] `@support-stewards`
- Delete all upcoming events for the appropriate role(s) using [code described here](https://github.com/2i2c-org/team-roles-geekbot-sweep/blob/HEAD/README.md#delete_events_bulkpy)
  - [ ] Run for `meeting-facilitator` role
  - [x] Run for `support-steward` role
- Regenerate upcoming events for the appropriate role(s), without the new member in the roster, using [code described here](https://github.com/2i2c-org/team-roles-geekbot-sweep/blob/HEAD/README.md#create_events_bulkpy)
  - [ ] Run for `meeting-facilitator` role
  - [x] Run for `support-steward` role

:sparkles: **Congratulations! This person is no longer on the rota for their role. Thank you for all your hard work!** :sparkles:

**Comment by sgibson91** [comment]
done

**Comment by consideRatio** [comment]
Thank you @choldgraf and @sgibson91!
