### ISSUE TITLE
Create a GitHub team `@2i2c-org/hub-admins` to give hub administrator access

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#511]
### Context

We currently provide any member of @2i2c-org/tech-team to also have administrator access to the JupyterHubs that we manage (via the GitHub OAuthenticator).

There are a few challenges with this:

1. @2i2c-org/tech-team is also meant to denote "members of the engineering team at 2i2c", and there are some members that need admin access that aren't members of this team.
2. It's not explicit that membership in this team comes with hub administrator priviliges

### Proposal

Create a new GitHub team that is dedicated to providing Administrator access to our JupyterHubs. This could be called `@2i2c-org/hub-admins` and by default any team member working with communities would have membership on this team.

It's a little bit redundant, but I feel there's enough benefit in resolving the two challenges above that it would be worth it. What do others think? Any objections?

**Comment by sgibson91** [comment]
I am +1

**Comment by choldgraf** [comment]
While we're at it, I'd also propose renaming @2i2c-org/tech-team to `@2i2c-org/engineering` so that we can standardize our naming here with other documentation of our team structure

**Comment by sgibson91** [comment]
I actually recommend that we call this team `hub-access` or `2i2c-staff` and leave the word admin out of it. There is a misunderstanding of what the GitHub Teams are used for here. The Teams are used to grant 2i2c staff regular, old user access to a hub that has Teams-based authentication. **We currently cannot grant admin rights to a group of users via Teams membership.** The list of members who are granted admin rights lives in our helm chart, and we always use this method of granting admins rights to staff, regardless of authentication method.

https://github.com/2i2c-org/infrastructure/blob/b38117e8aa828bacc1e1449d85f960c1d275f25c/helm-charts/basehub/values.yaml#L78

**Comment by sgibson91** [comment]
I'm going to action this by:

- [ ] Creating a new team called `hub-access-for-2i2c-staff` (to be really clear about the purpose of the team) and ensuring all staff are added (This is the union of `2i2c-org/tech-team`, Chris, James, and Jim)
- [ ] Updating all hub configs that use GitHub Teams-based auth. Replace `2i2c-org/tech-team` with `2i2c-org/hub-access-for-2i2c-staff`
- [ ] Once above change has been reviewed and merged, ensure membership of `2i2c-org/tech-team` is just the members of the engineering team, and also rename to `2i2c-org/engineering`

**Comment by sgibson91** [comment]
@2i2c-org/engineering We are now engineering!!

I also checked all the hubs that had been affected by the new team auth swap, and I could log in to all of them 🎉
