### ISSUE TITLE
Complete the CS&S Invoicing retrospective questionnaire

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#527]
### Context

CS&S reached out and noted that they thought there are likely many ways that we could improve our invoicing process for the communities that we work with. They sent us a short set of questions to brainstorm, and suggested that we have a meeting to discuss as a group afterward.

### Action items

- [**Fill out answers in this proposal**](https://docs.google.com/document/d/1Dz7R9rYoGMecrEBwhoVN6-aICh2OEvXRunzXZFt6ZUo/edit#) asynchronously
- Schedule a meeting with CS&S to discuss

**Comment by choldgraf** [comment]
cc @jmunroe - maybe this is something we can think about at the same time that we tackle #519 ? I am happy to collaborate on this w/ you if it helps move things forward faster.

**Comment by pnasrat** [comment]
Is this something that should be included in the Q2 Billing project or is it too late for the retrospective and should be closed - cc @colliand

**Comment by damianavila** [comment]
> Is this something that should be included in the Q2 Billing project or is it too late for the retrospective and should be closed 

My inclination would be to close it (even more when we are still defining our complete invoicing process), but I will defer the final decision to @jmunroe and @colliand since they might see things I am ignoring with my biased (and most likely incomplete) view of the process.

**Comment by choldgraf** [comment]
I agree - I think that this questionnaire is now out of date. We can follow up with CS&S in new issues as they arise
