### ISSUE TITLE
Turn our monthly team meeting into a "team retrospective" / process meeting

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#528]
### Context

Currently, we have a single monthly "all team" meeting with a pretty open agenda. We [describe a few potential agenda topics here](https://team-compass.2i2c.org/en/latest/coordination/meetings.html#monthly-team-meetings). Historically these meetings tend to focus on "strategic" and high-level questions, dig into important content-related questions about our engineering infrastructure or service direction, or are "meta" questions about our team practices.

However, we're now dedicated meeting time for specific areas of content (product/engineering, community/partnerships, and strategy):

- https://github.com/2i2c-org/team-compass/issues/518

At the same time, we still have many ways that our team practices can improve, and I believe there is value in explicitly dedicating time to having conversations about our internal system and how to make it better.

### Proposal

I propose that we re-purpose our monthly team meetings to explicitly be a "team process" meeting. 

- Discuss how work seems to be going for everybody and understand if people are particularly stressed about something
- Make decisions about how we should change team process to become more efficient, inclusive, and effective
- Surface and discuss concerns that people have with our current practices
- Ensure that we are aligned on any changes to our practices and what / why they exist

I think it makes sense for this meeting to be led by the Project Manager, or by somebody else that has visibility over the work that everybody is doing.

**Comment by damianavila** [comment]
I agree with the re-purpose.
