### ISSUE TITLE
Convert our bi-weekly team sync to be a planning meeting instead of an update meeting

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#530]
### Context

At the moment, a large chunk of our bi-weekly "sprint planning meetings" are dedicated to talking about the _status of work items_, and _reporting what we have been up to_. However, as a distributed organization that pays a heavy cost for every synchronous meeting, I propose that doing status reports is not the best use of our time.

We absolutely need mechanisms to share knowledge and hold ourselves accountable, but we should use "synchronous time" to resolve ambiguity via discussion, share important information quickly, and make decisions.

### Proposal

I propose that we shift the focus of our every-two-week meetings to instead be one of **prioritizing work items** and **agreeing on the work we will do in the next two weeks**. Here are the three changes I'd propose:

- **2 days before this meeting, open an asynchronous team update issue** where team members report the status of what they've been up to over the last two weeks, and any major blockers they are encountering.
- **In our sprint planning meeting** we should agree on the most important issues to tackle over the next two weeks, and everybody should feel like they have exactly two weeks-worth of work to do[^1].

In a cycle we should _only commit to doing work that we will finish within the 2 weeks_. This means that we should break tasks down into manageable chunks, and try to _overestimate_ how long it will take to accomplish each one. The default expectation is that by the final Tuesday of a cycle, everything a person committed to doing is done. 

My hope is that this will make it easier for us to understand what is on our plate at any given moment, and make us less likely to drop balls because we committed to too many things without intentionally letting go of old things. 

[^1]: I don't want to clutter this proposal so putting this idea down here. I'd also suggest that we **define four types of issues we work on**: Planned development tasks, operational toil tasks, personal development tasks, and upstream support tasks. The goal of these categories is to make sure that we don't accidentally pile too many tasks of a given type on one person over time, and so that we make sure to create time for less-urgent but still-important things like personal development.

**Comment by yuvipanda** [comment]
i like it!

**Comment by damianavila** [comment]
I concur with the proposal and I will talk more about it in tomorrow's cycle meeting.

**Comment by damianavila** [comment]
FYI, this one started to be executed in the last sprint/cycle.

**Comment by damianavila** [comment]
We are now having sprint retrospectives for each of the goals in the quarter.
During those meetings, the first half is dedicated to retrospect on the previous sprint, and the second half is centered around general improvements for the next sprint that help us move closer to the completion of the goal (the specifics of the sprint plan are left to the goal lead, based on the feedback received during the second half).

The gathering of information is done via two bots:
* stand-down (MWT)
* retrospective bot running a botanical version of the goof, the bad, and the ugly as exercise.
