### ISSUE TITLE
Define a strategic priorities backlog for 2i2c

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#540]
### Context

We currently have an [engineering backlog](https://github.com/orgs/2i2c-org/projects/22/views/25) and plans to implement a [partnerships and community backlog](https://github.com/2i2c-org/team-compass/issues/510). These are used to track day-to-day priorities and deliverables in these parts of 2i2c.

However, these backlogs are very dynamic, and focused around day-to-day actions. We need a space to encode the **strategic priorities and objectives** that should drive most of the activity in these backlogs, and a process around defining them. These priorities should be the "source of truth" that helps us prioritize our daily actions. They should change less-quickly than our day to day tasks, and should represent major strategic objectives that we need to accomplish to succeed.

### Proposal

I propose that we **create a strategic priorities backlog**. It would be a way for the team leads to agree on the most important issues to tackle, prioritize them, and to hold ourselves accountable for making progress.

This will be a place to answer these questions:

- what are the most important objectives in each functional area of 2i2c?
- when do we hope to accomplish them?
- who is responsible for getting them done?

The lead(s) of each functional area is responsible for defining these priorities and updating them here, by integrating feedback from both their teams and the other leads within 2i2c. They are also responsible for making the progress we agree to making when we work on this backlog.

The details of _how_ we accomplish each should *not* be defined in this backlog - those are for other issues and coordinated/carried out in our team backlogs. 

I suggest that we:

- Define this backlog as a GitHub Project Board
- Focus our bi-weekly `strategy content meetings` around the items that are on this backlog
- Ask the leads of each functional area to be directly responsible for advancing these priorities
- Define a cadence by which we'd like to define and track our progress

#### What functional areas are represented here?

I think these would be the major areas and their directly-responsible individuals for now:

- Organization-wide (Executive Director)
- Community (Community Guide Lead)
- Engineering (Technical Lead and Engineering Team Lead)
- Partnerships (Partnerships Lead)
- Product (Product Lead)

#### Sorting the backlogs

Moreover, I think that we should restrict this backlog to be strictly **sorted** so that high-priority items within a group come first, and to **limit our work in progress** so that we only focus our efforts on a few objectives at a time.

#### Where do we discuss this backlog?

- In the `strategic content meeting`
- In the `#team-leads` channel
- In the issues that are defined on this backlog

#### Who is responsible for this backlog

The Executive Director, though they delegate responsibility for items in each functional area to their respective leads.

### Feedback

I would like feedback particularly from @colliand @damianavila @jmunroe and @yuvipanda on this, since this is the group that would be most-often interacting with this backlog.

A few specific questions:

- Is it helpful to encode this information in a dedicated space?
- Is it OK to encode this in a GitHub Project board?
- How should we define accountability and planning? A monthly cycle? Rolling checkpoints?

### Checkpoints

- [x] Discuss this asynchronously
- [x] Decide whether to implement it
- [ ] Create the backlog and populate it with priorities in each group
- [ ] Begin iterating on it over time

### References

- Related to: #407 and #36 and basically any of our strategic-level issues, since this is the place where we would encode our strategic objectives.

**Comment by damianavila** [comment]
> Is it helpful to encode this information in a dedicated space?

Not only helpful, it is needed, IMHO.

> Is it OK to encode this in a GitHub Project board?

I think it is OK to have it in a GH project as per consistency with other boards across the organization.

> How should we define accountability and planning? A monthly cycle? Rolling checkpoints?

A monthly cycle would be my preference, but I think the definitive call about the process implementation would be in @choldgraf's hands.

**Comment by jmunroe** [comment]
Copying a comment made in Slack to @choldgraf from @jmunroe:

> Do we need to rethink our project management into just two boards:
> 1. "Engineering Related (SRE,  Development, Product, Upstream Support)"
> 2. "Non-Engineering (Partnerships, Community, Communications, Strategy)"
> 
> 
> Currently, it looks like the "Organizational Board" is capturing issues that are mostly a) Team Operations and b) owned by 
> @choldgraf. 
>
> That would be well captured by using the "Type" and "Assigned" fields.  Also, it would allow you to track items that are cross-functional areas (like a blog post) that are not specifically assigned to you?
>
> A  "Strategic Priorities Backlog" still has value but that should be reserved for non-tactical issues.

**Comment by damianavila** [comment]
Having those 2 boards could be an intermediate step toward the migration to one board per functional area.
As the complexity grows the boards containing multiple concepts evolve into confusing monsters nobody wants to take a look at. There is a huge value in having a super-focused (local to the area) board. The "connection point" between the different boards is a good point to push for unified ones... but as the previous iteration of our board suggested, the pros coming from the connectivity (cross-functionality) are erased by people not interacting with the board because is huge and too complex.

**Comment by choldgraf** [comment]
@damianavila I'm not quite sure what path forward you are responding, could you clarify that?

**Comment by damianavila** [comment]
Sure, as the next step, I am OK to have a shared board for product and engineering.
That will help to minimize the cost we might pay for having things already split and effective connection wires.
In the future, as complexity grows, I think each functional area should have its own dedicated backlog and there will be a need to create/improve communication channels between those different areas.

> "Non-Engineering (Partnerships, Community, Communications, Strategy)"

Finally, IMHO, the strategy backlog lives at a higher level so it should be a different one from the Non-Eng one.
I can probably argue strategy and organization could live in the same backlog if you want to simplify things (effectively having 3 backlogs: Prod&Eng, Partner&Comm, Strategy&Org).
