### ISSUE TITLE
Test out using Freshdesk to triage hello@2i2c.org requests

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/team-compass#552]
### Context

From a Partnerships and Community meeting (2022-10-20) we agreed to test out using FreshDesk as a part of a CRM pipeline.  This is important for know that emails sent to `hello@2i2c.org` have received response and/or triaged appropriately.

Our current FreshDesk plan is "Free".  To support an [arbitrary number of email aliases](https://support.freshdesk.com/en/support/solutions/articles/37637-adding-multiple-email-addresses-to-freshdesk) we need to upgrade to at least the "Growth" plan ($15/user/month). There is 14-day trial available that was entered into on 2022-10-26.

### Proposal

- [x] Create a "Partnerships" group within FreshDesk to triage handling message sent to hello@2i2c.org
- [x] Add @colliand to FreshDesk as an agent
- [x] Add a new FreshDesk alias emails which automatically categorizes messages under the "Partnerships" group
- [x] Add a new user to the `hello@2i2c.org` Google group to forward messages to FreshDesk
- [x] Test

**Comment by jmunroe** [comment]
The FreshDesk assigned email is `2i2corghello@2i2c.freshdesk.com`. I add this email to the `hello@2i2c.org` Google group which required changing the permissions on that group to support 'non-organizational members'.

**Comment by choldgraf** [comment]
I saw a test message show up!

**Comment by jmunroe** [comment]
I've been able to verify that an email sent to `hello@2i2c.org` successfully generates a ticket on FreshDesk.

**Comment by jmunroe** [comment]
FreshDesk has reached out re: upgrading to their paid service:

> Simran Prakash <support@freshdesk.com>
> Thu, Oct 27, 6:10 AM (1 day ago)
> to me
> 
> Hi James, 
> 
> I hope you are doing well!
> 
> This is Simran, your Account Manager with Freshworks. I'm reaching out to you to understand if the Freshdesk Free plan is meeting your expectations.
> 
> If you would like to move to a higher plan, I’d suggest that this would be the right time. 
> 
> With the Holiday season upon us, we have launched an exclusive offer for all our “Free Plan” customers. If you are looking to upgrade to any of our paid plans anytime before Oct 31st, 2022, I can offer you a flat discount of 15%. As simple as that!
> 
> If you’re interested in learning more, you can write to me or schedule some time on my calendar using this link- https://calendly.com/simran-prakash/30min
> 
> Looking forward to your response, 
> 
> Best, 
> 
> Check your ticket status - https://support.freshdesk.com/support/tickets/12995270

I believe we (2i2c) were already assuming that we were on a paid plan and not only the free one.  We have 2 weeks of a trial available (which is actually is more like 21 days under as actually implemented) but if we want to advantage of this "15%" flat discount we'd need to make a decision by Monday, Oct 31.

FreshDesk is a key component of our current support strategy and I am generally happy with how it appears to work as an intake funnel for requests to `hello@2i2c.org`. If we also need the paid feature of "multiple support emails" to support multiple-organizations on AWS then I think upgrading to a paid plan for FreshDesk is the way to go. 

I am suggesting the FreshDesk "Growth Plan" will meet our needs. See https://freshdesk.com/pricing for details.  I am not as clear on how many "agents" should we set up under this paid plan. Currently we have 9 people set up as "agents". The price is $15/agent/month if paid annually (and $18/agent/month if billed monthly).  I have not yet asked about a non-profit discount.

FreshDesk does offer the concept of a "day-pass" meaning that we don't actually need everyone in 2i2c to be fully priced "agents" if certain individuals only need occasional access.  

**Proposal:**
- Remove @sean-morris and @consideRatio as 'agents' (last log in were > 1yr, and >3mo, respectively). There is the option of a day-pass open if ever that access is needed.
- Contact FreshDesk account manager Simran Prakash to inquire about an non-profit discount instead.
- Assuming there is no non-profit discount or the discount is less than this 15% "flat discount" they are offering, purchase 7 "agents" under a one year, paid plan.  (7 agents * 15/mo/agent  * 12mo + 15% flat discount = $1,071/yr)
- Confirm with FreshDesk how our costs would be calculated if we needed to add additional "agents" mid-year (anticipating our new hires will also need to be set up on FreshDesk)
- _Alternative proposal:_ Set up as monthly billing (7 agents * 18/mo/agent  + 15% flat discount = $107.10 / mo or $1285.20/yr)

I'll bring this up in Slack as well. I'm looking for guidance from others on how to proceed preferably before the end of Monday.

**Comment by yuvipanda** [comment]
I like this plan!

**Comment by damianavila** [comment]
I concur as well.

**Comment by choldgraf** [comment]
I agree with the plan as well 👍

**Comment by jmunroe** [comment]
A one year agreement with FreshDesk has now been signed and paid for. 

(Reciept on 2i2c-CS&S shared drive: https://drive.google.com/file/d/1VWomyJwtBGfrrpVqacn4f97fDyCHpBqV/view?usp=share_link)

Next step: I'll document this on our Team Compass.

**Comment by colliand** [comment]
I think we've completed the tasks associated with this issue.
