### ISSUE TITLE
Define a source of truth for Monthly Revenue and Monthly Costs KPIs

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#560]
### Context

We've decided to track our monthly revenue and costs as part of our Key Performance Indicators. However we do not currently have a single place to look to answer these questions, so we should define a source of truth for them.

### Proposal

We should define a page that summarizes our monthly revenue and costs by major category over a 30-day rolling window (or in pre-set cycles like monthly accounting cycles).

We can probably infer most of this from the CS&S financial data that is produced each month. There is some effort in this direction at the following repository:

- https://github.com/2i2c-org/kpis

**Comment by choldgraf** [comment]
I have been thinking about this one a bit more, and think we should modify these KPIs slightly. Here is my reasoning:

While monthly revenue and costs are important, they aren't an inherent indicator of our _performance_. We should choose indicators that can help us make decisions about what to prioritize or change. "Raw revenue / costs" don't seem like the right numbers to influence our actions because we expect both of them to be going up consistently.

So I propose that we do the following things:

- Make our monthly revenue streams and major costs available for transparency, but do not treat these as KPIs
- Define two sustainability-based KPIs that reflect _performance_ more directly.
	- **Burn Rate**: a 6-month (2 quarters) rolling average of the difference between our revenue and costs.
	- **Cash Runway**: Given our current funds and our average burn rate, how many months until we run out of funds.
- Define two _efficiency_-based KPIs that are combinations of our "Impact KPIs" and our "Sustainability KPIs":
	- **Cost per community**: `Burn Rate / Communities Served` - reflects the costs that we have for each community we work with.
	- **Cost per user**:  `Burn Rate / Monthly Active Users` - reflects the costs that we have for each user.
	- And an aspirational one that'll be more complex to track: **Average cost per user across communities**: `mean(Service Fee for each community / Monthly Active Users for each community)`.

I think these metrics are more tied to our decision-making. For example, both of them should be consulted when making decisions about whether we want to hire new people, or invest our time in making our processes more efficient.

**Comment by damianavila** [comment]
> So I propose that we do the following things:

I really like the proposal!

> I think these metrics are more tied to our decision-making.

Indeed!
