### ISSUE TITLE
Define an asynchronous-friendly meeting agenda policy

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#564]
### Context

We've had a few instances where team meetings were cancelled or defined their agenda just a few hours before the meeting, which made it difficult for other team members to participate, or caused them to wake up early unnecessarily because they were sleeping when this decision was made.

We are globally distributed team across many time zones, which means that we need to give one another a bit more runway for planning and coordination. We should define a meeting policy that respects one another's time and recognizes the fact that we're all working at very different hours of the day.

### Proposal

I propose that we define a _team meeting policy_ with the following goals:

- Be fairly lightweight and minimal
- Be respectful of our international team's time
- Be realistic that we cannot fit everybody in every meeting

In a Slack thread, there seemed like general alignment around these practices:

- A meeting agenda needs to be available at least **24 hours in advance**
- If there is no agenda defined within this window, **assume the meeting is cancelled**
- If the meeting facilitators wish to have a meeting even without an agenda, they should make this clear in the meeting notes at least 24 hours in advance.

**Comment by damianavila** [comment]
No objections, seems a reasonable policy to me.
