### ISSUE TITLE
Ensure PagerDuty notifications can get through to engineers during incidents

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#574]
### Context

We use PagerDuty in two ways:

1) Automatically generating alerts when infrastructure is down (before a user can),
2) Notifying engineers of an outage so they can respond in a timely manner

This process only works effectively when the PagerDuty notifications can actually make it through to the engineers being paged so they can respond.

I think some experimentation is required to figure out what stops notifications in what scenario. Then I can envision some docs in the team compass around "how to setup notifications for {insert notification channel}".

**Engineers should still be able to choose which notification channel they prefer to use. These docs should be focussed around "given a chosen notification channel, this is how you ensure the notifications are not blocked by Do Not Disturb, etc.**

**Comment by sgibson91** [comment]
I will help Yuvi test the new settings

**Comment by yuvipanda** [comment]
Let's try this at 8AM Pacific, Thu 8 (tomorrow). I think that's 4pm london time and should be ok?

Things to try:

1. Trigger an event in pagerduty. This should technically always call me.
2. Call me over whatsapp
3. Attempt to call me over regular phone (I'm not actually sure if this is possible?)

I am not sure if iOS lets calls from whatsapp through unfortunately, so that is something to test.

Thanks a lot for doing this, @sgibson91!

**Comment by yuvipanda** [comment]
@sgibson91 yep! that works :)

**Comment by damianavila** [comment]
Hey folks, did you test it? Can you report back if we are in a good shape on this one? Thanks!!

**Comment by yuvipanda** [comment]
We tested this (thanks for doing this two days in a row, @sgibson91!)

The upshot is that Apple can not fathom that people might want to use things other than the cellular phone network to call anyone, so there's literally no way to say 'silence everything, except phone calls and whatsapp calls' :( So goddamn USA centric (I almost wrote 'America centric', which itself is USA centric...)

Anyway, we determined the solution, given we are an international team and can not rely on old school cell phone networks, is for me to never put the phone in DND mode but to actually go and explicitly silence each app one by one except whatsapp. I have done so, and the second test made it ring! yay!

So I think this is good. We should perhaps document this somewhere but I'm not sure where, and trying to 'figure out where to document this' always stresses me out and I never do it :( Can someone help?

**Comment by sgibson91** [comment]
> We should perhaps document this somewhere but I'm not sure where

I think this should go into our Team Compass. We should have a guide like "How to setup PagerDuty notifications for on call" or similar, which subsections for whatsapp, etc, etc. I think this is a new guide under our support process documentation.

**Comment by damianavila** [comment]
Ensure that planned work did not trigger unwanted pings.

**Comment by yuvipanda** [comment]
I think perhaps this is related to https://github.com/2i2c-org/team-compass/issues/661, and we can have 'watch for pagerduty notices in the #pagerduty-notifications channels and acknowledge' as part of when engineers are doing regular maintenance? I think @pnasrat mentioned something like this in the chat during the sprint planning meeting today.

We currently don't have the expectation that pagerduty actually page anyone on their phones at all, just me :) I think figuring out a policy for that longterm would be ideal, but I think that's a bigger story.

**Comment by pnasrat** [comment]
Having the slack based acknowledgement makes sense, for cases where changes may trigger alerts but no action would be required such as cluster decomissioning I think pagerduty's maintenance windows might be of use. 

https://support.pagerduty.com/docs/maintenance-windows

**Comment by damianavila** [comment]
> We currently don't have the expectation that pagerduty actually page anyone on their phones at all, just me :) I think figuring out a policy for that longterm would be ideal, but I think that's a bigger story.

I agree the policy is a bigger story but I want to make sure you are not paged when you are in your upcoming away time (and the same for everyone else who is away).

**Comment by yuvipanda** [comment]
yeah good idea - I'll unhook myself from that before I go!

**Comment by damianavila** [comment]
We know PagerDuty notifications get through and we now have a dedicated Slack channel as well, so closing this one.

> We currently don't have the expectation that pagerduty actually page anyone on their phones at all, just me :) I think figuring out a policy for that longterm would be ideal, but I think that's a bigger story.

Btw, I have created https://github.com/2i2c-org/team-compass/issues/763 to further discuss it.
