### ISSUE TITLE
Refine and split up our onboarding checklist by role

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#600]
### Context

We have one catch-all onboarding checklist for any new member joining the team. So far our hires have been mostly engineers, so this checklist has become focussed on what they need to get setup.

As we begin to hire different types of roles, e.g. community guides, it may make more sense to have separate onboarding checklists for each role, so we know we're not overloading new team members with access to platforms they don't need, etc?

**Comment by damianavila** [comment]
Closing as a dupe in favor of #654 which has a little bit more content/discussion.
