### ISSUE TITLE
Buy a new Freshdesk slot for an additional full time agent

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/team-compass#608]
### Context

We reached our maximum agent number and need one more. More context https://2i2c.slack.com/archives/C028WU9PFBN/p1673531403509569

### Proposal

Buy an additional full time slot.

### Updates and actions

- [x] @choldgraf to reach out to Camille to get in contact to Freshdesk folks
- [x] buy an addtional slot from Freshdesk
- [x] make @colliand a full time agent again, as we temporarly switched him to occasionaly
- [ ] ~document that @yuvipanda is the person with full access to the 2i2c Freshdesk (billing?) account~
document the process we followed in https://compass.2i2c.org/en/latest/community/freshdesk.html

**Comment by GeorgianaElena** [comment]
@yuvipanda hope it's ok that I've assigned you for the first task. I can take care of the others if you'd like me to help.

**Comment by yuvipanda** [comment]
I don't seem to have access either:

If I follow https://support.freshdesk.com/en/support/solutions/articles/228105-how-do-i-increase-the-agent-seats-on-my-account- I see:

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/30430/212238207-54fe61f1-4768-4026-9969-e7973e566b88.png">

No 'edit' button found :( 

> If your payment is offline, please write to billing@freshdesk.com, with a request to increase agent seats and the number of agents you are looking to add. One of the agents from the Billing Team would get in contact with you to process your request.

perhaps this is the approach?

**Comment by choldgraf** [comment]
Yeah that's the page I found too. Ok I will ask Camille if she can follow up w them

**Comment by choldgraf** [comment]
oh hi @Camille-Gonzalez-VA :-)

**Comment by sgibson91** [comment]
On a slightly more meta-level, we should note in our onboarding docs/team compass that adding someone to Freshdesk requires communicating with Freshdesk right now to increment the number of full-time agent slots. I guess until we grow so big that we change our plan?

**Comment by damianavila** [comment]
> Is @colliand going to be the full-time agent slot we are adding or is @colliand 's situation another task I should work on with FreshDesk support?

I think this was already clarified via Slack.

**Comment by Camille-Gonzalez-VA** [comment]
> > Is @colliand going to be the full-time agent slot we are adding or is @colliand 's situation another task I should work on with FreshDesk support?
> 
> I think this was already clarified via Slack.

Correct, I am on this! @damianavila

**Comment by damianavila** [comment]
It seees everyone has access, so closing this one.

**Comment by damianavila** [comment]
As a follow-up, @Camille-Gonzalez-VA did not have access as an agent, so I added her as a full agent.

Additionally, I realized @colliand was set up as an occasional seat and he was consuming almost all of our occasional agents:

<img width="996" alt="Screen Shot 2023-02-03 at 11 15 33" src="https://user-images.githubusercontent.com/1640669/216626391-91fffc62-893d-42b0-b01f-2d04e623287d.png">

I have moved @colliand  to be a full agent
