### ISSUE TITLE
Product and engineering agree on major goals for Q1 2023

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#615]
We need to agree on our major priorities to accomplish in Q1 2023. I know that we're already well into January, so don't treat "Q1" as a hard rule, the point is to agree on our short-term priorities and agree to focus on these priorities in the next two months or so.

Assigning @jmunroe @damianavila and @yuvipanda to lead this effort since they represent the product, engineering project manager, and engineering technical lead perspectives.

**Comment by damianavila** [comment]
We had some shared planning in the latest Prod and Eng meeting: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#heading=h.3lmqgn6qzglw.

From the product perspective, we have 2 main goals for Q1:
* Storage documentation and tooling
* Environment creation and curation documentation

We are going to create specific goals for each of them and add subtasks accordingly.
Eng committed to providing time slots for conversation with @jmunroe so we can get Eng's feedback to make progress in the documentation piece and to ask about specific tooling that might be needed.

Eng goals were discussed and agreed on in the previous Prod and Eng meeting: https://docs.google.com/document/d/1dUO2USQlRbcjOEkjlCu1gyTaPBZmGZSRF4L-_9xecmA/edit#

From the engineering perspective, we have 4 main goals for Q1:
* Monitoring and alerting
* Billing
* Dynamic image building (GESIS)
* Deployer enhancements

We are going to create issues for each of those goals and a few specific subtasks.
The general idea is to have smaller goals but more concrete ones.

**Comment by choldgraf** [comment]
Closing this as the engineering team is focusing their efforts on Q2 2023 now (see https://github.com/2i2c-org/infrastructure/issues/2269)
