### ISSUE TITLE
Leadership team agrees on our capacity to accomplish goals/commitments of Q1 2023

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#618]
In https://github.com/2i2c-org/team-compass/issues/607 we have several issues to define priorities and track our major efforts across the organization. The @2i2c-org/team-leads need to agree on these, and we'll aim to do so in Wednesday's org strategy meeting.

**Comment by choldgraf** [comment]
Oops I accidentally added @consideRatio instead of @damianavila - Erik you are most certainly welcome to participate in these conversations, but it is not your _responsibility_ to do so :-)

**Comment by yuvipanda** [comment]
Q1 is done, and we have a better process for Q2 now. I would suggest we close this one.

**Comment by choldgraf** [comment]
Agree - @yuvipanda what is the better process that y'all are using now? Is it something that we can adapt for other parts of 2i2c as well?

**Comment by yuvipanda** [comment]
I'll let @damianavila answer that. We need to write this up somewhere too, so we can tinker with the process as well.

**Comment by damianavila** [comment]
I created an issue to document the process we followed up (with some preliminary information): https://github.com/2i2c-org/team-compass/issues/697
