### ISSUE TITLE
Consider two potential grant opportunities depending on whether we have capacity in Q1/Q2 2023

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#619]
There are two grant applications that seem in-scope for 2i2c in Q1 2023. [Both were discussed in this strategy meeting](https://docs.google.com/document/d/1HoNX8T8IQ1uhS2ryi1r9iS-nSbPT1b1Y7HsjosbHme8/edit#heading=h.61zv06ku3zec) but we need more information to decide whether we have the capacity to apply for them.

These two grants are:

- https://github.com/2i2c-org/meta/issues/380
- NSF Directorate for Geosciences Open Science Ecosystem (GEO OSE) (about `$1m`) (I couldn't find an issue for this)

We need to agree on whether we'll apply for one or both of these grants, as part of our broader strategic planning in https://github.com/2i2c-org/team-compass/issues/607

I'm assigning all of the @2i2c-org/team-leads here since we all need to be in agreement before committing 2i2c to major new work. @jmunroe has the most context and vision for what we could propose on each of these grants so I think he should lead discussion about the ideas around them.

**Comment by choldgraf** [comment]
I believe that one of these opportunities was related to running a BinderHub for NASA communities, so here's a set of resources in case it's helpful for @jmunroe or @colliand 

- [grafana.mybinder.org](http://grafana.mybinder.org/) - has real-time dashboards about Binder's service
- [a repository I set up to analyze mybinder.org's billing data](https://github.com/jupyterhub/binder-billing), [see this nbviewer version](https://nbviewer.org/github/jupyterhub/binder-billing/blob/master/analyze_data.ipynb?flush_cache=True) for an idea of what's in there.
- [here's the Binder impact report](https://docs.google.com/document/d/1DvW8TYgEVWYvsgZKlr4JrmuhLQoYC-jTie0okgnIjp0/edit?usp=sharing) I wrote for Google for our last batch of credits - it has both content+images you can re-use or replicate w/ updated data

I could not find an issue where this grant is being discussed, so sharing here. @colliand or @jmunroe can you please open issues about the above two opportunities so that we can have context, discussion, and proposals in one place?

**Comment by damianavila** [comment]
@choldgraf, I think you are referring to https://github.com/2i2c-org/meta/issues/467 in the above comment.

**Comment by jmunroe** [comment]
Yep -- I just created them!  The two grants under consideration are

- 2i2c-org/meta#467
- 2i2c-org/meta#468

**Comment by choldgraf** [comment]
I believe that we've submitted proposals for both of the two proposals listed above. I'm going to close this one because there's no more action to take here. I'll leave it to @colliand and @jmunroe to decide if they want to close the two grant-specific issues above.
