### ISSUE TITLE
Create a `#calendars` channel in Slack and move auto-generated notices about calendars there

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#631]
We currently have calendar events automatically displayed in our `#team-updates` channel. However, I find that this channel is most-useful when the content is generated by team members, where I can learn about what they're up to, how they're feeling, things they did over a weekend, etc.

When we have calendar entries show up in the channel, it often comes in a big wall that pushes any human-generated content "above the fold", which makes it harder to notice, read, and respond to. At the same time, I find that _auto-generated content that is not actionable and frequent quickly becomes easy to ignore_.

### Proposal

For this reason, I suggest that we move the auto-generated calendar entries to a dedicated `#calendars` channel. The idea is that this channel will almost always be auto-generated feeds that team members can subscribe to for a ping if they find it useful, but that won't be in-line with user-generated content in another channel.

I'd also suggest that instead of the bot, we encourage meeting facilitators to be more proactive about announcing to one another when meetings are happening, and what the agenda will be. I think that is a more valuable way to convey that information rather than a calendar bot. Not sure how to ensure this happens though.

Are there any objections or suggestions for this proposal? If I don't hear anything then I'll re-work the bots to post to a new `#calendars` channel.

### References

Initial conversation here: https://2i2c.slack.com/archives/C01GLCC1VCN/p1675070569871379?thread_ts=1675069205.018219&cid=C01GLCC1VCN

**Comment by sgibson91** [comment]
+1

**Comment by choldgraf** [comment]
OK, I have created a `#calendars` channel, and have told our Google Calendars app to start pointing to that channel rather than to `#team-updates`.
