### ISSUE TITLE
Add a "would you like to give thanks to anybody" section to our team update bot

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#632]
I've noticed that many people often use the Team Updates to say "thank you" to other team members (or others in the community) that have helped them out. This is often in the final question about "Requests for other team members", because we don't have a dedicated question about this.

I think it's a good practice to be thoughtful about our appreciation of one another, and the visible and invisible ways in which they help us. I think it might encourage us to think in this way if we had explicit space to reflect and give thanks to one another in our team updates.

### Proposal

Let's add a fifth question at the end, like the following:

- Would you like to give thanks and appreciation to somebody? 🙏

I'd also like to clarify somehow that people don't _have_ to answer every question, they can type `no` to anything and it'll skip it. I don't want people to feel forced to show appreciation but want it to be explicitly encouraged :-) 

If I don't hear any objections or suggestions to modify, I'll give this a shot later this week.

**Comment by sgibson91** [comment]
+1

**Comment by GeorgianaElena** [comment]
+1

**Comment by choldgraf** [comment]
I've added this to our bot, so let's see how it goes as we start to use it!
