### ISSUE TITLE
Onboarding Pris Nasrat

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/team-compass#651]
Onboarding champions: @GeorgianaElena and @consideRatio
Person's name: Pris Nasrat

# Onboarding checklist

Follow the checklist below to onboard a new team member!

**Accounts**

- [x] Member's GitHub.com account: @pnasrat
- [x] Member's ReadTheDocs.org account: pnasrat
- [x] Member's Quay.io account: prisnasrat
- [x] Member's NameCheap.com account: pnasrat
- [x] Create a `@2i2c.org` Google account for them
- [x] Add them to the proper Google group in our Google Admin space.
- [x] Add to [the proper GitHub team](https://github.com/orgs/2i2c-org/teams/2i2c-team)
- [x] Add to [the proper Slack group](https://2i2c.slack.com/admin/user_groups)
- [x] Add to [the proper FreshDesk group](https://2i2c.freshdesk.com/a/admin/agents)

TODO: add calendar note

**Communication**

- [x] Send them a link to the [2i2c Team Compass](https://team-compass.2i2c.org/en/latest/) and its [Team Operations section](https://team-compass.2i2c.org/en/latest/operations/index.html)
- [x] Send them a link to the [2i2c Team Google Drive](https://drive.google.com/drive/u/1/folders/0AJcabtB-T0LnUk9PVA)
- [x] Schedule an onboarding meeting for after they've read through the docs

**Permissions**

- [ ] Add to appropriate GCP organizations and projects
  - [ ] Organization `2i2c.org`'s [admin group](https://console.cloud.google.com/iam-admin/groups/03znysh73qbio4n?organizationId=184174754493)
  - [x] Organization `2i2c.org`s [engineering group](https://console.cloud.google.com/iam-admin/groups/01opuj5n2qnifml?organizationId=184174754493)
  - [x] Outside-organization project for [`cloudbank`](https://console.cloud.google.com/iam-admin/iam?project=cb-1003-1696)
  - [x] Outside-organization project for [`meom-ige`](https://console.cloud.google.com/iam-admin/iam?project=meom-ige-cnrs)
  - [x] Outside-organization project for [`callysto`](https://console.cloud.google.com/iam-admin/iam?project=callysto-202316)
  - [ ] (optional) Outside-organization project for [`pange-hubs`](https://console.cloud.google.com/iam-admin/iam?project=columbia)
    - An agreement has to be signed first, and they require a copy of our passports, see (TODO: clarify this)
- [x] Add to appropriate AWS accounts
  - [x] Management account [`2i2c-sandbox`](https://2i2c.awsapps.com/start/#/) (Grants SSO access at https://2i2c.awsapps.com/start#/)
  - [x] Outside-SSO account [`carbonplan`](https://631969445205.signin.aws.amazon.com/console)
  - [x] Outside-SSO account [`openscapes`](https://783616723547.signin.aws.amazon.com/console)
  - [x] Outside-SSO account [`nasa-veda`](https://smce-veda.signin.aws.amazon.com/console)
    - An agreement has to be signed first, see https://github.com/2i2c-org/leads/issues/104
- [ ] Add to appropriate Azure projects
  - [x] Outside-organization subscription for `utoronto` (TODO: figure out details here)
- [x] Add to the [auth0 2i2c tenant](https://manage.auth0.com/dashboard/us/2i2c/tenant/admins)
- [x] Add to [quay.io 2i2c team](https://quay.io/organization/2i2c/teams/owners)
- [x] Add to [RTD projects](https://readthedocs.org/)
  - [x] https://readthedocs.org/dashboard/2i2c-pilot-hubs/users/
  - [x] https://readthedocs.org/dashboard/2i2c-team-compass/users/
  - [x] https://readthedocs.org/dashboard/2i2c-pilot-documentation/users/
- [x] NameCheap administration privileges to `2i2c.org` and `2i2c.cloud`
  This is handled by Jim (`@colliand`)

**Roles**
- [x] Onboard into the [Support Steward Role](https://github.com/2i2c-org/team-compass/issues/new?assignees=&labels=type%3A+onboard&template=new-team-member.md&title=Onboarding+%3Cname%3E)

**External**

- [x] Add to [2i2c website](https://2i2c.org/organization/)
- [ ] Tweet about their arrival!

**Wrap up**

- [x] Have an onboarding session with the onboarding champion
- [x] Announce in the `#general` Slack channel about our new team member
- [x] Celebrate, they are now onboarded! 🎉

**Comment by pnasrat** [comment]
Note I already have links for (and google access) so those can be checked off

* 2i2c Team Compass
* 2i2c Team Google Drive

**Comment by damianavila** [comment]
Helping a little bit with the onboarding as well 😉 
Added Pris to the Eng and Support Slack teams.

**Comment by pnasrat** [comment]
I've also a branch that add me to the website, which I can push for review when I get GitHub org access.

**Comment by GeorgianaElena** [comment]
@pnasrat, I've just sent an invite into the org 🎉 and the appropriate teams

**Comment by pnasrat** [comment]
I think an item needs to be added for PagerDuty access, while SSO is on I get this error message

Unable to find user pnasrat@2i2c.org in PagerDuty account for 2i2c-org.pagerduty.com.

**Comment by damianavila** [comment]
Looking at PagerDuty, I do see we do not have available seats for new users. And it seems I do not have enough permissions to do admin stuff. @yuvipanda, IIRC, you created the account, right? Maybe you can help us a little bit with this one?

**Comment by yuvipanda** [comment]
@damianavila hmm, i think everyone in the team should have the same permissions - are you able to access https://2i2c-org.pagerduty.com/account/settings/subscription/purchase?

Regardless, I've purchased an additional seat and added @pnasrat.

**Comment by pnasrat** [comment]
Thanks @yuvipanda I can now see PagerDuty dashboard

**Comment by damianavila** [comment]
> @damianavila hmm, i think everyone in the team should have the same permissions - are you able to access https://2i2c-org.pagerduty.com/account/settings/subscription/purchase?

<img width="903" alt="Screen Shot 2023-02-17 at 16 05 11" src="https://user-images.githubusercontent.com/1640669/219763649-654abfe9-c0fe-4f4c-9bb9-8aac70758804.png">

cc @yuvipanda

**Comment by yuvipanda** [comment]
I've also put the invoice for this purchase on slack in #team-updates - not exactly sure where it should go, as it isn't a reimbursement (it goes via our organizational Ream card)

**Comment by damianavila** [comment]
@pnasrat, I think you are already "effectively" onboarded, and even if there are some tiny pieces that may be unresolved, we should be able to solve them with dedicated new issues down the road, do you concur with me? I want to make sure I am not closing this one prematurely.

**Comment by pnasrat** [comment]
Hmm. I need to do the external access stuff. I made a start reviewing the security training but probably should

Can we keep it open til sprint planning so I can try complete what I need and split off anything extra early next week

**Comment by pnasrat** [comment]
I've read and signed the security agreements and uploaded to google drive cc  @jmunroe do my docs need to be sent to nasa-veda

**Comment by yuvipanda** [comment]
For pangeo-hubs access, Pris would need a `columbia.edu` account. In the past, this has involved pinging Ryan Abernathey. I think now, we should probably ping him and Julius to see what the process is, as that would've changed.

Also, the original email where we got access had this line:

> Also I would appreciate getting a scan of his passport as I need to affirm which names are surnames or given names, and which are defined as first middle or last. Passports always make that clear. 

If *that* is the reason to require passport scans, perhaps we do not actually need to provide that?

Regardless, would someone else be able to own this?

**Comment by damianavila** [comment]
I can take care of pinging Julius to see what the process looks like by now.

> If that is the reason to require passport scans, perhaps we do not actually need to provide that?

If I remember correctly some team member provided a driver's license instead.

**Comment by jmunroe** [comment]
I had need to double check some time zones today using https://whena.re/2i2c-engineering-team (linked to our Team Compass at https://compass.2i2c.org/en/latest/reference/team.html) and noticed that Pris still needs to be added.

**Comment by pnasrat** [comment]
@jmunroe I'm not sure who has access to that -  also  while that's a pretty visualization if it requires a central person to edit then it doesn't really support updating for working from elsewhere (eg Yuvi is still listed as on Pacific when I think he's still travelling). I wonder if that's the best source of truth for timezones

**Comment by choldgraf** [comment]
If we're happy with _anybody_ being able to edit that webapp, then we can make that adjustment. As long as we have security through obscurity it probably wouldn't be an issue?

That said, I wonder if a better place for people to maintain their own personal working TZ hours etc is to do this as part of:

- https://github.com/2i2c-org/meta/issues/510

**Comment by damianavila** [comment]
> That said, I wonder if a better place for people to maintain their own personal working TZ hours etc is to do this as part of:

I like that idea... if we have some common formatting, it might be easy to grab that info and visualize it somehow (with recurrent updates).

**Comment by pnasrat** [comment]
`nasa-veda` and `utoronto` auth is done/underway. I think that's everything credential wise as pangeo  process is uncertain

**Comment by pnasrat** [comment]
Fine to close.
