### ISSUE TITLE
[Proposal] Damian as engineering manager

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#670]
Hey all - I would like to propose that we elect @damianavila to be our first Engineering Manager!

This is a new role ([here's a description in our compass](https://compass.2i2c.org/en/latest/engineering/roles/engineering-manager.html)), and we still need to learn how it fits in with 2i2c's structure and practices. However, Damian has been serving in a similar capacity for several months via his role as the engineering Project Manager, and we've all appreciated the benefit this has brought to the team. I've spoken with the team leads, as well as with Damian, and we all agreed that Damian would be a good fit for the role (and importantly, he is interested in it as well!).

In the next day or two, I intend to update our Team Compass to note that Damian is serving in this role. Please reach out to me (or comment here) if you have any questions or thoughts you'd like to discuss.

Given that it is brand new, this might mean that not much changes in terms of our day-to-day practices - @damianavila will continue to lead engineering team meetings and provide guidance to everyone. Over time, we will need to learn more about what "engineering management" means at 2i2c, and how we can support Damian in this role (and others in the future).

Thanks to @yuvipanda and @damianavila (and several others) for helping design the language for the role, and to @damianavila for being willing to serve in the role. ❤️  I think this will be really helpful at improving our team practices and systems!

### References

- We'll need a support system and training plan for this role! See: #656

**Comment by yuvipanda** [comment]
I Approve!

**Comment by choldgraf** [comment]
I opened a PR to make it more explicit what action would "formalize" this decision. Since 2i2c.org is the current source of truth for "our team" I think that's the place to define the change (we should probably have a more structured way to define our team roles but that's for another day!)

- https://github.com/2i2c-org/2i2c-org.github.io/pull/147

I'll plan to leave that open through early next week for others to think or provide comments. If I go on paternity leave before then, and there are no objections, I ask somebody to please merge the PR!

**Comment by damianavila** [comment]
@2i2c-org/engineering, I have added this one to the current sprint board given the timeline @choldgraf shared above.

> Please reach out to me (or comment here) if you have any questions or thoughts you'd like to discuss.

A little reminder from the first message ⬆️ 

>  I opened a PR to make it more explicit what action would "formalize" this decision. 

I will abstain to approve the referenced PR for obvious reasons.

> he is interested in it as well!

Indeed, I will be delighted to explicitly serve in this role!!
