### ISSUE TITLE
Agenda for our team retreat 2023

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#672]
We're planning to meet in-person together at JupyterCon this year (ref: #541). This will be the first time that 2i2c's team has gotten together in-person! (thanks COVID). 

It is critical that we make the most of this time together as a group. While we definitely want some of our time to be unstructured and/or purely social, I also think we should define a few topics that we _want_ to discuss. These should be like an "extreme" version of our meetings policy: what are the topics that are _particularly important to have in-person_? Topics that are particularly complex, important, sensitive, or that require input from many people?

We should have an **agenda for conversations** to happen during each day of our team retreat, and a **plan for who will lead them** etc.

### Resources

[**Draft guide and agenda for team meeting**](https://docs.google.com/document/d/1xU-9OsYIUCjOwu76qgfehyR7Ea9AuImWTC31KmxhUHg/edit?usp=sharing)
[**Team offsite planning folder**](https://drive.google.com/drive/folders/139aog4kSB6rQTwGLEz3mrSYVYWPt_ztC?usp=share_link)

### To do

```[tasklist]
- [x] Decide if we need any outside facilitation --> Agreed to investigate a few and if there was a good match, go for it. If not then we'll run it internally: https://github.com/2i2c-org/team-compass/issues/672#issuecomment-1499261915
- [ ] https://github.com/2i2c-org/meta/issues/538
- [ ] https://github.com/2i2c-org/meta/issues/541
- [x] Work with Superbloom team to create an agenda structure
- [x] Finalize this into an agenda
```

**Comment by choldgraf** [comment]
### Meeting with Danielle tomorrow

I'm going to meet with Danielle Robinson @ CS&S tomorrow to get some advice about designing an agenda for the retreat. Will report back when I do!

**Comment by damianavila** [comment]
I really like and, in general, agree with the takeaways, in particular, the 3 first points are totally spot on, IMHO.
About the external facilitator, I am probably more biased towards internal facilitation (but open to other alternatives if people agree on that direction).

**Comment by choldgraf** [comment]
### Update: 2 no's 1 maybe

I was connected to three external facilitators by Danielle, two of them weren't available. The third is a group called [superbloom](https://simplysecure.org/) (historically called "simply secure"). They are actually sending some team members to JupyterCon and might be interested. They've done facilitation of strategic and organizational planning before. I've worked with Georgia (their ED) before and she is pretty sharp + values-aligned with 2i2c. She'll ask her team if they have availability to work with us in the days ahead of time. If so, then I'd suggest we try to work with them. If not then I think we should work w/ them and others just to help us design an agenda.

@damianavila my gut feeling is that yes, we can facilitate this internally if need be without problem. However, facilitating a complex meeting benefits from dedicated expertise, and given that this is the first 2i2c has had, we'd benefit from leveraging this expertise to make the most of the time[^1]. I also think it would let all of our team members focus on the content of a session, rather than losing one or two team members in each conversation because they are facilitating instead of participating (in my experience, it takes somebody _super experience_ to meaningfully both facilitate and participate in a conversation like that).

[^1]: I'm kind-of assuming that our team doesn't have a lot of dedicated expertise in designing and facilitating strategic/organizational meetings. I've facilitated meetings before, but not of this complexity or scope. If somebody _does_ have more experience with this, please let me know and let's chat!

**Comment by damianavila** [comment]
Very good points you have raised and this is why I said before I am open to external facilitation as well 😉.

**Comment by choldgraf** [comment]
### Update: recommendation in issue below

I had a meeting with the superbloom team - a short summary and recommendation is in the issue below:

- https://github.com/2i2c-org/meta/issues/538#issuecomment-1508895651

I thought it'd be better to discuss this one in `meta/` since we might be discussing external people that folks on this team might already know.

**Comment by choldgraf** [comment]
### Draft agenda structure / guide here

I've put together a draft structure for each day, as well as guidelines around COVID policy etc for the meeting. [Check out the draft agenda structure / guide here](https://docs.google.com/document/d/1xU-9OsYIUCjOwu76qgfehyR7Ea9AuImWTC31KmxhUHg/edit#heading=h.vhuze712iw3s) and please provide feedback. I'll continue to flesh this out as the agenda topics take more shape.

**Comment by choldgraf** [comment]
Closing this as we now have an agenda!
