### ISSUE TITLE
Investigate switching to Slack Google Calendar App

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/team-compass#675]
### Context

We use [Google Calendar for Team Events (Legacy)](https://2i2c.slack.com/services/gcalendar) to post notifications to #calendars in our Slack workspace.  

We've noticed that calendar notification still are made even after an event has been canceled. https://2i2c.slack.com/archives/C04MZ8G8E9H/p1676984675647299?thread_ts=1676912404.222219&cid=C04MZ8G8E9H

Since this Slack app marked as legacy and "Google Calendar for Team Events is being retired."  Should we be switching to [Google Calendar App](https://slack.com/apps/ADZ494LHY) instead?

**Comment by damianavila** [comment]
@jmunroe, you closed this because you do not plan to spend time on it?
Trying to understand properly what "closed this as not planned" means.
Thanks!
