### ISSUE TITLE
COVID policy for our team retreat

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#684]
We should define a testing and/or masking policy to minimize potential COVID risk to our team during the retreat.
We can titrate this up or down based on the comfort level of our team and the current COVID situation as of ~late April.

```[tasklist]
- [ ] Get feedback from our team about any concerns or constraints they think we should take for this meeting.
- [ ] Decide on a COVID policy
```

### Some questions to consider

- Should we require a non-rapid test after travel?
- Should we require rapid tests each day?
- Do we require masking when meeting together as a team?
- Do we avoid certain locations in team meetings? (e.g., crowded bars)

### Resources

- [IETF covid mitigation analysis for their event](https://www.ietf.org/media/documents/IETF-114-COVID-Mitigation-Analysis.pdf)
- [UK Collaborations Workshop COVID policy](https://software.ac.uk/cw23/participation-guidelines#covid19-policyhttps://software.ac.uk/cw23/participation-guidelines#covid19-policy)
- [How to throw a company offsite in a post-COVID world](https://charity.wtf/2023/02/28/how-to-throw-a-company-offsite-in-a-post-covid-world/)

**Comment by sgibson91** [comment]
> Do we require masking when meeting together as a team?

If even one person says they want masking, publicly or privately, then yes make this a requirement.

**Comment by choldgraf** [comment]
I think that is a reasonable approach. Just a note that nobody has provided a private or public opinion on this yet.

**Comment by GeorgianaElena** [comment]
> Just a note that nobody has provided a private or public opinion on this yet.

Where is feedback about this expected?

**Comment by GeorgianaElena** [comment]
>  Would it be better if I created a Google Form for this?

I believe that would make it more clear what are the options being considered and simpler to aggregate. Also, I believe we should provide enough time so that **everyone** at 2i2c that's participating to provide their option about this one, and make sure everyone is comfortable.

**Comment by choldgraf** [comment]
OK let me whip together a quick survey and share it with the team later today (CET).

**Comment by GeorgianaElena** [comment]
@choldgraf, thank you very much! I'm sorry to be proposing extra work :(

**Comment by damianavila** [comment]
> If even one person says they want masking, publicly or privately, then yes make this a requirement.

First, I think this proposal can be applied to multiple pieces: masks, vaccine shots, rapid tests, etc.

Now providing my two cents as a former biochemist (with multiple contacts with doctors) and having read a lot of scientific papers about it: if everyone is vaccinated, we should be totally safe without masking or rapid tests.

But again, this is just additional context, I still believe @sgibson91's proposal is the way to go!

**Comment by choldgraf** [comment]
### Questionnaire for team members to provide feedback

Hey all - @jmunroe and I have put together this very short questionnaire to gauge how our team feels about COVID policies. Responses will only be available to myself and James. We'll use this to define a proposed policy for y'all to provide feedback on as well.

[Link to the questionnaire about COVID policy](https://docs.google.com/forms/d/e/1FAIpQLScTjmEvvr8-SySELtvwpUs0CjxJ50iILS2mc5n0OPDV3Ia4jA/viewform?usp=sf_link).

**Comment by choldgraf** [comment]
A few resources from responses on Hachyderm (linked in top comment as well)

- [IETF covid mitigation analysis for their event](https://www.ietf.org/media/documents/IETF-114-COVID-Mitigation-Analysis.pdf)
- [UK Collaborations Workshop COVID policy](https://software.ac.uk/cw23/participation-guidelines#covid19-policyhttps://software.ac.uk/cw23/participation-guidelines#covid19-policy)
- [How to throw a company offsite in a post-COVID world](https://charity.wtf/2023/02/28/how-to-throw-a-company-offsite-in-a-post-covid-world/)

**Comment by choldgraf** [comment]
A few notes from reading https://charity.wtf/2023/02/28/how-to-throw-a-company-offsite-in-a-post-covid-world/

ensure outdoor seating options as much as possible

assume people will be overwhelmed esp if this is the first in-person meeting in a while

masks were available but optional, and social norm to put them on if anybody around asked

daily rapid testing available for everyone, mandatory every 48 hrs

good quote:

> Take care of yourselves. Do what you need to do to be fully present while you’re here, rather than here 100% of the time.

This means:

- We scheduled only three sessions per day, plus lunch and dinner
- We set aside a “Recharge Room” with doors that closed, with nail polish, coloring books and markers, and board games.

And their summaries:

###

- Outdoor spaces for eating, temperate climate, extra-spacious rooms for circulatory purposes.
- The rapid-nucleic tests we used were made by Lucira. (Liz says: “The tests were far more reliable than we thought they’d be — the brand has a reputation for false positives but we saw none, and only 3 invalid tests out of several hundred performed.”)
- Testing. We were hyper-diligent about testing. We actually ran out of tests on Wednesday, despite provisioning two for each attendee and a bunch of extras, and had to emergency lift in more, which is a great sign.
- Taking a layered approach to COVID safety. Not relying on any single prevention method meant that if one didn’t work well, we still had a safety net.
- Having a knowledgeable COVID czar.
- The Recharge Room with nail polish, art supplies and games worked really well, although designating other areas as “Quiet Zones” was ineffective and unnecessary.

### What we can improve on

- The 30-60 minute breaks sprinkled throughout the day were well-intentioned, but ineffective. Everybody was fucking wiped by late afternoon. Next time, I would replace all those breaks with one solid “Nap Break” from 4-6pm.
- I think it’s important to acknowledge that we were all going to be flattened no matter what though. We aren’t used to this! It is HARD to leave the party to take care of yourself!
- We should have a team of COVID safety marshals, in addition to the Code of Conduct team.
- Next time we will ask people to submit their COVID test results — even if it’s just dropping a pic in a slack channel. Trust but verify.
- The CO2 monitors were confusing. They were hard to find, and most of them got installed in the wrong place. Also, the 650 ppm rule would have essentially meant everyone had to wear a mask in any closed room, which was not the goal. Our error here was not in failing to stick to the 650 ppm rule, but in making a rule we couldn’t keep.
- Next year, we will be explicit about the fact that CO2 monitors are for informational purposes, so individuals can factor it into their own masking choices and/or decide whether to move outside.
- Next year we will also emphasize that it is okay to ask the people around you to mask up so you can participate.
- If you aren’t comfortable asking those around you to put on a mask, you can DM a safety marshal who will ask on your behalf.
- One session in particular had external facilitators come in and roam around the (closed) rooms shouting stuff. They tested clear for COVID, but in retrospect I really wish we had asked them to mask up, as it generated a lot of anxiety. This was our biggest covid safety lapse, in my opinion.

**Comment by choldgraf** [comment]
### Suggested policy

Here's the outline of a suggested COVID policy. Please provide comments. We'll formalize this if there objections or formal requests to change it:

#### What we'll provide

- Rapid tests for each team member for each day of our team meeting.
- [FFP2 masks for each team member](https://www.amazon.fr/dp/B08R7RZV6G?psc=1&smid=A26JGLBHBBBNHE&ref_=chk_typ_imgToDp) (FFP2 is the French equivalent of N95)

#### Before arriving

- Everybody must confirm that they have been vaccinated or had COVID in the last 9 months.

#### Each day of team meetings

- Everybody takes a rapid test and texts a pic to a `#team-meeting` channel before the day begins.
- Everybody wears an FFP2 mask while we are inside during the meeting
- This applies to anybody participating in the meeting, including external facilitators
- If a team member feels uncomfortable or overwhelmed, they are not required to attend all team meeting sessions. If you expect to miss a significant chunk of the meeting, please inform @choldgraf.

#### Informal time outside of meetings

- We'll try to plan for dinners and/or lunch outside, weather and venue permitting.
    - We will be near the Canal St. Martin and the temperature should be nice outside, so generally we will try to take meals there.
- Dinners are not mandated and we should focus this time on informally connecting with one another rather than making decisions or discussing things that we haven't covered in person.
- These might happen throughout the week as well, but again will be on an "if you want" basis.
- Guests are allowed at these events

#### If somebody tests positive for COVID

- If anybody tests positive for COVID within 48 hours of our team meeting, notify the team via Slack, or `choldgraf` if you prefer to notify privately.
- Anyone who tests positive won't attend any of our in-person meetings. We'll take notes and share them to invite asynchronous feedback if so.
- For travel arrangements etc, see: https://github.com/2i2c-org/team-compass/issues/713

#### Attending JupyterCon

- Team members are not required to attend JupyterCon if they do not feel comfortable with the health standards of the conference.

**Comment by choldgraf** [comment]
A few people pinged me about that uncertainty, sorry for the confusion.

Here's more precise language:

Vaccinated ever, or had COVID within the last 9 months.

**Comment by damianavila** [comment]
The suggested policy LGTM.

**Comment by choldgraf** [comment]
### Policy written up in our agenda

I've written up a version of this COVID policy for an agenda document I'm creating for the meeting. If you have feedback or comments, please provide it there and we can continue to iterate on the language/policy if need be. I'll close this issue for now, and will add comments if we make substantial changes to the policy in follow-up comments.

[Agenda w/ COVID policy](https://docs.google.com/document/d/1xU-9OsYIUCjOwu76qgfehyR7Ea9AuImWTC31KmxhUHg/edit?usp=sharing)
