### ISSUE TITLE
Update for 2023 Q1

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#685]
We should provide an update about what we've been up to in 2023 to our team and our external stakeholders.

### Example structure

- Short summary
- Highlights
	- Community and Partnerships
	- Engineering
	- Org-wide
- Financial report for 2i2c
- Major upcoming goals
	- Community+Partnerships 
	- Engineering
	- Org-wide

### Actions

```[tasklist]
- [x] #688
- [ ] https://github.com/2i2c-org/team-compass/issues/720
- [x] Get highlights and upcoming goals from engineering / community+partnerships
- [x] Record a short video of our financial situation to share with the team ([video link](https://drive.google.com/file/d/1sBdBYEWsbyInWAILSAsWCpQhuoI8bhzQ/view?usp=share_link))
- [ ] https://github.com/2i2c-org/meta/issues/555
- [ ] https://github.com/2i2c-org/2i2c-org.github.io/pull/155
- [ ] Post to  our mailing list
```

**Comment by choldgraf** [comment]
### A few notable things

- Yuvi blog post about active users: https://blog.jupyter.org/accurately-counting-daily-weekly-monthly-active-users-on-jupyterhub-6fbec6c6ce2f
- CILogon: https://www.ncsa.illinois.edu/security-made-simple-with-ncsas-cilogon/
- OpenScapes: https://www.openscapes.org/blog/2022/11/17/nasa-earthdata-cloud-infrastructure/#cloud-optimized-data-formats

**Comment by damianavila** [comment]
What is the deadline for contributing content?

**Comment by choldgraf** [comment]
Let's say **in one week**, so Wednesday, April 5th. For content, what is most useful would be 1-3 of the most notable things that have happened, as well as short links to any issues/PRs/websites/blog posts/etc that you'd like to highlight.

**Comment by choldgraf** [comment]
CZI talk:

- https://github.com/2i2c-org/meta/issues/458

**Comment by damianavila** [comment]
# Engineering

**NOTE**: This is just a subjective and short list of things we have done during Q1. I am probably forgetting a few things and purposely avoiding very granular stuff. Complete information about what we have done lives in the Sprint board for each of our sprints (1-6).

## Several new hubs:
* https://github.com/2i2c-org/infrastructure/issues/1949
* https://github.com/2i2c-org/infrastructure/issues/1961
* https://github.com/2i2c-org/infrastructure/issues/2049
* https://github.com/2i2c-org/infrastructure/issues/2017
* https://github.com/2i2c-org/infrastructure/issues/2118
* and several new cloudbank-based hubs.

## Events:
* https://github.com/2i2c-org/infrastructure/issues/2108

## Migration from Auth0 into CILogon
* https://github.com/2i2c-org/team-compass/issues/621
* https://github.com/2i2c-org/infrastructure/issues/1304

## Improving support process:
* https://github.com/2i2c-org/meta/issues/452

## Maintenance:
* Upgrading the underlying kubernetes version
  * https://github.com/2i2c-org/infrastructure/issues/2125
  * https://github.com/2i2c-org/infrastructure/issues/2057
* Improvements in the deployer
  * https://github.com/2i2c-org/infrastructure/issues/1472
  * https://github.com/2i2c-org/infrastructure/issues/1925
* uptime check optimizations
  * https://github.com/2i2c-org/infrastructure/issues/2320
* sharing nodes optimizations
  * https://github.com/2i2c-org/infrastructure/issues/2209

## Fulfilling support-related requests such as:
* Publicly accessible bucket
  * https://github.com/2i2c-org/infrastructure/issues/2123
* Enable GitHub authentication to our Grafana dashboards for all *dedicated* clusters
  * https://github.com/2i2c-org/infrastructure/issues/1827

## New engineers and manager:
* https://github.com/2i2c-org/team-compass/issues/595 (Erik)
* https://github.com/2i2c-org/team-compass/issues/651 (Pris)
* https://github.com/2i2c-org/team-compass/issues/670 (Damián)

# Docs improvements:
* https://github.com/2i2c-org/infrastructure/issues/2055

# GESIS-related work:
* https://github.com/2i2c-org/infrastructure/issues/2120
* https://github.com/2i2c-org/binderhub-service/issues?q=is%3Aissue+is%3Aclosed

**Comment by choldgraf** [comment]
Hey all - I am sifting through the list above and wanted to note a few things that we should reflect on in the coming months. This is mostly just me reflecting and generating some data, I am not sure what actions to take next but wanted to get the ideas written down.

### A lot of the stuff above is operational

**`tl;dr`**:  We are doing too much operational toil and should figure out how to re-focus our efforts on investing in our technology / processes / etc.

First off, I want to note that a lot of the stuff above seems operations-focused. E.g., actions that we take in response to an event or a request from a community, that don't inherently improve the scalability or reliability of the service as a whole, or that don't add new functionality that all communities benefit from.

I think we should treat this kind of signal as a warning that we are not protecting our time for development-related tasks. It is critical that we not enter a spiral of operational toil.

### We are intermingling "operations / toil" work and development work

**`tl;dr`**:  We need make it clearer what of our work items are "toil" and what are investments in our service / technology / etc.

I also find it hard to tell when some of the engineering deliverables are operational in nature vs. development in nature. We need to make it really clear what is what, because we need to avoid the operational spiral described above. The majority of our work should be development / improving the service for all / etc, and we need it to be obvious if we're getting stuck in operational toil so that we know to course correct.

### We are double-counting some actions across teams

**`tl;dr`**:  We need do a better job of aligning goals and accomplishments across the team. Potentially share the same goals and deliverables across all parts of the org, not separated by functional area.

I noticed that @damianavila and @colliand both counted "deploying a hub" and "onboarding a new community" as two separate actions above. This suggests to me that we are not doing a good job of aligning our goals across our team. The things we work on need to benefit 2i2c as an organization, and the communities we work with, and we should think about our major goals/actions in that framework. "Creating a partnership with a new community" is an org-wide goal, not two separate accomplishments across teams.

This suggests to me that we are too silo'ed in our planning and coordination efforts. Onboarding a new community should feel like a natural cross-team effort...

### Many issues are titled in terms of actions, not value

**`tl;dr`**:  We need to describe our major accomplishments / deliverables in terms of value, not actions

Many of the issues above have titles based around actions. But what really matters is _why_ we took an action and what benefit this will give [our team / all communities / one community / etc]. Sometimes it makes sense to have an issue describe actions just to track and assign ownership to them, but I think the primary issue we work from should be value-focused.

For example, I tried a little thought experiment around the issue titled:

`Remove the 2i2c-specific auth0-based authenticating infrastructure`

The title of this issue makes it hard to understand the reason that we're doing this. Ultimately, we wanted to simplify our authentication infrastructure because we were supporting both CILogon and Auth0 simultaneously, and we felt it was better to just commit to CILogon and make things simpler for us and others. The title also doesn't reflect the fact that our goal there was to move from auth0 to CILogon, not just to remove Auth0.

So a way that we could improve the title to reflect this would be to re-name it something like:

`Simplify our authentication workflow by migrating all communities to CILogon authenticator and away from Auth0`

Alternatively, this might have benefited from a "tracking issue" that framed the high-level value, and use this action-focused issue as a subset of that.

**Comment by choldgraf** [comment]
### Blog post draft is up

Here's a PR with a blog post draft:

- https://github.com/2i2c-org/2i2c-org.github.io/pull/155

I'm happy to iterate with feedback from folks this week if others have thoughts, otherwise will plan to post at the end of the week.
