### ISSUE TITLE
Centralising 2i2c presentation decks

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#692]
### Context

Folk have given presentations/made slide decks about 2i2c previously, and if these were stored in a centralised space, then other team members could view and reuse them. This will:

1. Save folks time rewriting the same "Who is 2i2c? What do we do? What's our mission?" content over and over again, and
2. Ensure messaging about these topics are consistent (with wiggle room for specific contexts or audiences)

### Proposal

We should collate slides about 2i2c in a central spot for easy reuse across the team. This could be:

- Our team google drive
- A [Zenodo "community"](https://zenodo.org/communities/) if we wanted to be more open to others outside 2i2c reusing our material
- Something else?

**Comment by choldgraf** [comment]
I've got a PR to document this here:

- https://github.com/2i2c-org/team-compass/pull/693

Thanks for catching it.
