### ISSUE TITLE
Proposal: make strategy meeting happen weekly

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#696]
Currently our org strategy / team leads meeting happens bi-weekly. We've used it as a general way for team leads to share topics that think are worth discussing or updating on and that require discussion.

As I'm looping back in to work, I'd like to try increasing the cadence of this meeting so that we have more chances to dig into strategic and cross-functional priorities for the team. I also think that we should focus it around helping our team leads think through their strategic priorities, identify questions to answer, refine abstract ideas into more actionable ones, etc.

So I'd propose we **make the strategy meeting weekly, instead of bi-weekly**, and that we find a time that will work for people if we do this.

This is an issue to track the proposal, we can discuss in the next meeting (or gather async feedback/discussion here) and make a decision from there.

**Comment by choldgraf** [comment]
In our strategy meeting today, we agreed that it was a good idea to have this meeting weekly for the time being.

We noted that we will need to find another time for the off week meeting, as it conflicts with the engineering Sprint planning meeting.

We noted that for this meeting, the "just usually attend" people are the area leads (@choldgraf , @colliand , @jmunroe , @yuvipanda , @damianavila ). Everyone is welcome but these are the folks we must design the meeting times and agenda around.

We also noted that it is going to be hard to find a time that is possible for both @choldgraf and @yuvipanda / @colliand , so we may need to explore alternating times. But Chris has a relative hard stop at 6pm CET so it may simply not be possible

**Comment by yuvipanda** [comment]
Oh, I generally don't think of this as a meeting I attend - @damianavila represents engineering here. I'm happy to come to specific ones if needed.

**Comment by choldgraf** [comment]
### Proposal: move this meeting to every Thursday at 5-6pm CET (8-9am Pacific) 

I think that it's important that this meeting is at a reasonable meeting time for those involved. If that includes both CET and Pacific, I think that means 5-6pm CET is our only option.

Our current Wednesday slot overlaps with the Engineering Sprint Planning meeting. Looking our meetings schedule, it seems that we have a regular hole in this slot on Thursdays.

So here's a proposal:

- **Move our organization/strategy meeting to Thursday, 5-6pm CET, 8-9am Pacific**

Can @damianavila @colliand and @jmunroe confirm if this plan works for them?

**Comment by colliand** [comment]
I confirm this works for @colliand.

**Comment by jmunroe** [comment]
Works for @jmunroe

**Comment by yuvipanda** [comment]
To be clear, this doesn't mean other members of engineering aren't welcome :D Just that I'm not attending in my capacity as tech lead.

**Comment by damianavila** [comment]
> Move our organization/strategy meeting to Thursday, 5-6pm CET, 8-9am Pacific

Works for me as well!

**Comment by choldgraf** [comment]
OK let's do it then, I've made this meeting weekly, meeting on Thursdays rom 5-6pm CET. Thanks all!
