### ISSUE TITLE
Document the goal definition process we followed for Q2

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/team-compass#697]
### Context

Things we did:

* We started with proto-goal candidates.
* We worked through them in a sync fashion in at least two 1h meetings.
* We defined more concrete goals based on the proto-goals.
* We selected leads for each concrete goal.
* We guesstimated our capacity allocations.
* We scoped out the goals based on the planned resource allocation (on dedicated issues)

Things to complete:

* We form teams for each goal.
* We add the goals to the org board.
* We recurrently sync our sprint planning with the existing goals for the quarter
* We do a retro analysis 1 (one) month before the quarter ends
* We start the planning the next quarter 1 (one) month before the next quarter starts

### Updates and actions

* We talked about getting monthly updates from each team lead to understand the progress (we can do it in an async fashion with updates to a dedicated issue)
* We talked about having a dedicated tab in the Eng board for the quarter goals so we can track them on a high-level view
* We talked about how to make sure the goals are a priority in our sprint planning (probably through pre-prioritization in the preparation of the sprint meeting)

**Comment by choldgraf** [comment]
I think this is also quite related to the issue that @GeorgianaElena opened up as well:

- https://github.com/2i2c-org/team-compass/issues/695

**Comment by yuvipanda** [comment]
I've written down how I think the process went for Q2 in https://docs.google.com/document/d/1OweVv18mzCeVWg0VjjADi99fG9NIFvQ3p4BRfeNrImM/edit#, and think we can use it as a baseline for improvements for Q3. In addition, I'd love for us to expand this process outside of engineering to everyone in the team. I've also left TODO notes there that capture what is left to be done in this issue, so am going to close this and we can continue on #695
