### ISSUE TITLE
Company wide Secure mechanism for password sharing

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/team-compass#699]
### Context

Some services we use such as airtable have shared accounts..

Password sharing should be done in a way that is secure.

### Proposal

BitWarden is an Open Source password manager with a hosted service for individuals, teams, and enterprise. 

https://bitwarden.com/pricing/business/

While bitwarden is Open Source https://bitwarden.com/open-source/ and could be self-hosted, the hosted offering will make sharing across the team more straightforward along with user group control and passwords collections. The enterprise offering offers SSO connection, but the teams offering would have individual bitwarden accounts

Also see what CS&S use for this?

### Alternatives Considered

Engineering currently uses [sops](https://compass.2i2c.org/en/latest/engineering/secrets.html) for encrypted files for machine readable API keys etc, however that is likely unsuitable for company wide usage.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/team-compass/issues/183 is related and has more information. CS&S uses 1password, but I'd prefer we use bitwarden too! They're an OSS org and I like supporting folks like us wherever we can :)

**Comment by choldgraf** [comment]
Ah I knew that we had discussed this somewhere before. Let's close this one, and I'll migrate the content that @pnasrat has added to the other issue so that we can iterate there. Here's the issue where we can have conversation

- https://github.com/2i2c-org/team-compass/issues/183
