### ISSUE TITLE
Write JupyterCon talk: No Magic Added (infrastructure)

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#702]
### Context

WIP slides are here:

- https://docs.google.com/presentation/d/1Fzphlm4ww959H08xpZkZEYMmvJIGtjR-oxqIFrYemXw/edit?usp=sharing

**Comment by damianavila** [comment]
I invite @2i2c-org/engineering to provide feedback on @sgibson91's slides referenced above.

**Comment by damianavila** [comment]
Another great talk from @sgibson91.
Feel free to link the video when it is available.
Closing now!
