### ISSUE TITLE
Improvements to the 2i2c Onboarding Documentation

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#71]
# Summary

We recently onboarded our first team member (using our current onboarding docs) and got a lot of useful feedback from this process. We should convert some of this feedback into improvements for the documentation! Summaries are below:

# Missing information

These were a few key pieces of missing information that were noted:

- [x] **How to navigate the team compass itself**. Much information was documented somewhere, but it wasn't clear how to look in the right place.
  - [x] Create an "introduction to the team compass" page that helps people navigate its contents
  - [x] Create/improve a "welcome to 2i2c" page for new team members that gives people an idea for the whole process
- [x] **Current team activity**. It wasn't easy to know what people were working on _right now_ (both at a high- and low-level).
  - [x] Document [our team workflow](https://github.com/2i2c-org/team-compass/pull/73), and how people can use it to understand this
- [ ] **What steps needed to be taken to onboard?**. We had a checklist in our team compass, but it wasn't clear who was supposed to carry out this checklist, and how to accomplish some of the items on there.
  - [ ] Complete / document https://github.com/2i2c-org/meta/issues/69#issue-732238413
  - [x] Include information in the team compass about how team members should provide access to these accounts
  - [x] Update [the onboarding checklist](https://team-compass.2i2c.org/en/latest/get-started.html#onboard-checklist-for-new-members) with new steps + links to how to accomplish them

- [x] **Describing 2i2c's overall structure and efforts**. It was unclear what 2i2c's "current organizational commitments" were. We have "projects", and "pilot hubs", but also had some that weren't mentioned like the Toronto + Farallon hubs.
   - [x] Clarify our active projects, where their repositories / information are located, as well as our hub information.
- [x] **List of all our currently-running hubs**. It was hard to find an up-to-date list of our currently-running hubs. [Our list of currently running hubs](https://pilot.2i2c.org/en/latest/about/projects.html#a-list-of-current-hubs) was out-of-date.
  - [x] Create a canonical list of all hubs that we run (https://github.com/2i2c-org/meta/issues/175)
- [x] **Define a welcome wagon**. 
  - [x] Send out a tweet about the person
  - [x] Add process for an "onboarding champion", who's job it is to carry out the onboarding process for a given person.

**Comment by choldgraf** [comment]
@damianavila let me know if I'm missing anything on this one, these were the major points that I gathered from our conversations.

**Comment by choldgraf** [comment]
I updated the list above with what I think was accomplished in #74 - there are still some things to add in however!

**Comment by sean-morris** [comment]
This may be happening because I am not using a 2i2c account but the [drive link](https://drive.google.com/drive/folders/1BOC1AuqvQOcAlHAYkHsjbSbLQdkseujO?usp=sharing) at the top this [page](https://team-compass.2i2c.org/en/latest/practices/info-location.html) seems to be non-existant.

**Comment by choldgraf** [comment]
@sean-morris try this link?

https://drive.google.com/drive/folders/1ABxxSFycGfCzQc9czfwer_dat-GVi4jw?usp=sharing

I also needed to add you to the `engineering@2i2c.org` team. Will document that as well.

**Comment by choldgraf** [comment]
I think that these are now taken care of, and we have another issue open to track the onboarding updates from #116 so let's close this one and follow up in those issues
