### ISSUE TITLE
Write JupyterCon talk: Outreachy

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#712]
### Context

WIP slides:

- https://docs.google.com/presentation/d/1KT105qySUd78JqJHmGGqVT85g4os0AhlZICNMxDZPVk/edit?usp=sharing

**Comment by damianavila** [comment]
An awesome talk from @sgibson91 at JupyterCon 2023.
Feel free to post the link when the video is out.
Closing now!
