### ISSUE TITLE
Sign up all of our team members with our organizational BitWarden account

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#719]
We've now got a BitWarden organizational account. This will let us add team members to it, and share passwords/credentials/etc via this connection.

### Request for team:

- [Create a BitWarden account](https://bitwarden.com/help/create-bitwarden-account/). I recommend using your 2i2c.org address but if you've already got a personal address w/ them, that's fine.
- You can use a free account or a premium account, whatever you like
- Report here the e-mail address that you've used
- I'll then add you to our organization
- You'll then get an e-mail and "accept"
- I'll then "confirm" and afterwards you should have access.

### List of people:

```[tasklist]
- [x] @choldgraf
- [x] @colliand
- [x] @consideRatio
- [x] @damianavila (needs to accept)
- [x] @GeorgianaElena
- [x] @jmunroe (needs to accept)
- [x] @pnasrat
- [x] @sgibson91
- [x] @yuvipanda
```

### Suggested access policy

- We have two sets of passwords: `everyone/` and `leads/`
	- `everyone/` is for the vast majority of the passwords
	- `leads/` only contains passwords for super sensitive things like the ability to delete our credit cards or something (TBH I still don't know what exactly we'd put here, I can't think of anything, but it seems like a good split to have just in case).
- Any 2i2c team member has access to our `everyone/`  list and is a `manager` role in BitWarden
- Any 2i2c area lead has access to `everyone/` and `leads/` and has the `owner` role in BitWarden

**Comment by pnasrat** [comment]
pnasrat@2i2c.org

**Comment by choldgraf** [comment]
Invited both of you 👍

**Comment by GeorgianaElena** [comment]
georgianaelena@2i2c.org

**Comment by consideRatio** [comment]
I've accepted the organization invite, and it seems it needs to be confirmed on your end as well @choldgraf.

**Comment by choldgraf** [comment]
I've invited @GeorgianaElena !

Also updated the top comment reflecting the extra steps I hadn't noted before, thanks @consideRatio

**Comment by sgibson91** [comment]
sgibson[at]2i2c.org

**Comment by jmunroe** [comment]
jmunroe@2i2c.org

**Comment by damianavila** [comment]
damianavila@2i2c.org

**Comment by choldgraf** [comment]
ok @jmunroe and @damianavila are now invited - once you accept then we can close this one out!
