### ISSUE TITLE
Adapt our code of conduct to our team meeting

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#723]
We currently have a [code of conduct](https://compass.2i2c.org/code-of-conduct/index.html) for the spaces that 2i2c stewards. However, we should ensure that this COC is appropriate for an in-person meeting, and make the necessary adaptations / extra clauses and processes / etc to ensure it can be realistically followed and enforced in our team meeting in Paris.

```[tasklist]
- [x] Identify a Code of Conduct steward other than Chris H: @damianavila
- [x] Chris and Damian decide how to adapt our CoC to the team meeting
```

### References

- [A code of conduct is not enough](https://getpocket.com/read/750047968) describes some aspects of a COC that we should incorporate into our thinking here (thanks @pnasrat for the ref)

**Comment by choldgraf** [comment]
### Can somebody volunteer as a second Code of Conduct steward?

I think it's important that we have an option for CoC reporting / stewardship other than just myself. Can I get somebody on 2i2c's team to volunteer as a COC steward for this meeting? You will be expected to participate in any investigation and response if a COC report is made, in partnership with myself (if I am not involved in the CoC report).

Ideally, you will have had experience in CoC reporting and response in an in-person event. But I know this is a small team and I know this may not be realistic to expect. But I still think it's important to have an avenue other than me/the ED and would appreciate another person to be available.

Please reach out to me privately or volunteer in a comment here if you're interested in serving in this role.

**Comment by damianavila** [comment]
I volunteered in Slack, doing the same here in case you missed my reply.
Btw, if there is someone else interested, feel free to drop me.

**Comment by choldgraf** [comment]
Thanks @damianavila - I'll note it in the docs.

**Comment by choldgraf** [comment]
Damian and I chatted about this briefly, and I also discussed it with our facilitators who have read the CoC and can provide some guidelines for our team's interactions as well.
