### ISSUE TITLE
Reimbursements in different currencies?

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#733]
### Context

I read through our team compass regarding reimbursements and ended up at CS&S's documentation [here](https://www.codeforsociety.org/resources/getting-paid-by-css), but my question is still unanswered so I'm opening an issue.

The context of my question is that a contractor has chosen to pay for something themselves and be reimbursed by adding it as a line item on their invoice. But the currency of the line item for the `$something` is different to the line item for our contract, which I believe is USD.

How does CS&S want us to handle that difference? Should I convert the cost of the `$something` into USD? But then the receipt won't match (which I'm assuming we'd have to submit as evidence), so would I also need documentation of the exchange rate on the date of purchase?

**Comment by choldgraf** [comment]
Will ask CS&S in Slack and see if I get a quick response...

**Comment by choldgraf** [comment]
### Convert the currency to USD

I heard back from Page. They'd prefer if you just did a conversion to USD based on the daily conversion rate, and use that number on the invoice. It's OK if the receipts are in a different currency as long as the numbers roughly correctly map onto each other given rates in the recent past.

**Comment by sgibson91** [comment]
Thank you - I will open up a PR to clarify this in our docs in this section: https://compass.2i2c.org/administration/reimburse/#reimbursement-for-contractors

**Comment by sgibson91** [comment]
- https://github.com/2i2c-org/team-compass/pull/734
