### ISSUE TITLE
Write R2R talk for RSECon UK

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#756]
### Context

- **Slides need to be uploaded by Aug 9th**
- Abstract: https://docs.google.com/document/d/1HmQh5W2HR5jlS-yh8_tXQtf7ggbS5DU41KIjyzu8dAc/edit?usp=sharing
-  Initial notes document: https://hackmd.io/@sgibson91/r10_9znt3

**Comment by sgibson91** [comment]
I am creating slides here:

- https://docs.google.com/presentation/d/19Ba8duwNooYyjj6lF34QZYa0rrf-6tz8yK3csH9LzJQ/edit?usp=sharing

**Comment by damianavila** [comment]
This is great, @sgibson91. Please let us know if you want a review from specific team members!

**Comment by sgibson91** [comment]
I've added the slides to the 2i2c Zenodo here: https://doi.org/10.5281/zenodo.8228652

Now all that's left to do is give the talk!

**Comment by damianavila** [comment]
> Now all that's left to do is give the talk!

Nice content on the slides! Eager to watch it (if they record it).
