### ISSUE TITLE
Onboarding Sean Morris, Cloudbank collaborator

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/team-compass#76]
Onboarding champion:  @yuvipanda
Person's name: Sean Morris

# Onboarding checklist

Follow the checklist below to onboard a new team member!

**Accounts**

- [x] <s>(if a 2i2c staff member) Make a `@2i2c.org` GMail account for them.</s>
- [x] Add to [the proper GitHub team](https://github.com/orgs/2i2c-org/teams/2i2c-team)
- [x] Add to [the proper Slack group](https://2i2c.slack.com/admin/user_groups)

**Communication**

- [x] Send them a link to the [Getting started docs](https://team-compass.2i2c.org/en/latest/get-started.html)
- [x] Send them a link to the [2i2c Google Drive](https://drive.google.com/drive/folders/1ABxxSFycGfCzQc9czfwer_dat-GVi4jw?usp=sharing)
  - [x] If they will not have a `@2i2c.org` address, manually add them to the drive.
- [x] Schedule an onboarding meeting for after they've read through the docs

**Permissions**

- [x] Add to appropriate Google Cloud projects
- [x] Add to appropriate AWS projects
- [x] Add to appropriate Azure projects
- [x] Add to the [auth0 2i2c tenant](https://manage.auth0.com/dashboard/us/2i2c/tenant/admins)
- [ ] NameCheap administration privileges to `2i2c.org` and `2i2c.cloud`

**External**

- [ ] Add to [2i2c website](https://2i2c.org/about/)
- [ ] Tweet about their arrival!

**Wrap up**

- [x] Have an onboarding session with the onboarding champion
- [x] Announce in the `#general` Slack channel about our new team member
- [ ] Celebrate, they are now onboarded! 🎉

**Comment by ericvd-ucb** [comment]
is @sean-morris working on this issue?

**Comment by yuvipanda** [comment]
I've a meeting scheduled with @sean-morris Friday 8AM Pacific :)

**Comment by choldgraf** [comment]
@yuvipanda is this done?

**Comment by yuvipanda** [comment]
I think @sean-morris is pretty much very onboarded :)
