### ISSUE TITLE
Onboarding Jenny Wong

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/team-compass#775]
(Starting from the generic onboarding template -- not all of these might apply for a Technical Content Developer and will be adjusted as we work through them)

- Onboarding champion: `@jmunroe`
- New person's name: `Jenny Wong`
- New person's GitHub handle: `@jnywong`

### Onboarding checklist

The **Onboarding champion** should follow the checklist below to onboard a new team member. Don't hesitate to delegate some actions to others (e.g. if another person needs to give access to an account because you aren't able to).

**First steps**

- [x] Send them a welcome e-mail to introduce yourself and mention that you'll be onboarding them.
- [x] Point them to [our onboarding documentation](https://team-compass.2i2c.org/operations/onboarding/)

**Accounts**

Create new accounts and share their account name:

- [x] Get member's [GitHub.com account](https://github.com)
- [x] Get member's [ReadTheDocs.org account](https://readthedocs.org)
- [x] Get member's [Quay.io account](https://quay.io)
- [ ] ~~Get member's [NameCheap.com account](https://namecheap.com)~~
- [ ] ~~Get member's [PagerDuty account](https://pagerduty.com)~~
- [x] Get member's [bitwarden account](https://bitwarden.com)

Create 2i2c accounts and add to team accounts:

- [x] Create a @2i2c.org Google account for them
	- Note that this requires [access to the Admin Panel](https://compass.2i2c.org/en/latest/administration/google-workspace.html?highlight=workspaces#access-and-permissions), a permission held by any 2i2c team lead
- [x] Add them to the proper Google group in our Google Admin space.
- [x] Add to the proper [2i2c GitHub teams](https://github.com/orgs/2i2c-org/teams/)
- [x] Add to the proper [Slack groups](https://2i2c.slack.com/admin/user_groups)
- [x] Add to the proper [FreshDesk group](https://2i2c.freshdesk.com/a/admin/groups
- [ ] ~~Add to propoer [PagerDuty Users group](https://2i2c-org.pagerduty.com/users-new)~~
- [x] Add to our [bitwarden organization](https://vault.bitwarden.com/#/organizations/11313781-4b83-41a3-9d35-afe200c8e9f1/vault) and add to "Default collection"

**Communication**

- [x] Send them a link to the [2i2c Team Compass](https://team-compass.2i2c.org/en/latest/) and its [Team Operations section](https://team-compass.2i2c.org/en/latest/operations/index.html)
- [x] Send them a link to the [2i2c calendars and meetings](https://team-compass.2i2c.org/en/latest/reference/calendar.html)
- [x] Send them a link to the [2i2c Team Google Drive](https://drive.google.com/drive/u/1/folders/0AJcabtB-T0LnUk9PVA)
- [x] Schedule an onboarding meeting for after they've read through the docs

**Documentation**

- [x] Grant appropriate permissions on [ReadTheDocs projects](https://readthedocs.org/)
  - [x] https://readthedocs.org/dashboard/2i2c-pilot-hubs/users/
  - [x] https://readthedocs.org/dashboard/2i2c-team-compass/users/
  - [x] https://readthedocs.org/dashboard/2i2c-pilot-documentation/users/

**Cloud engineering permissions**

_This is only relevant for others that are joining our Engineering team._

- [x] Add to 2i2c hubs as an admin
- [ ] Add to appropriate GCP organizations and projects
  - [ ] Organization `2i2c.org`'s [admin group](https://console.cloud.google.com/iam-admin/groups/03znysh73qbio4n?organizationId=184174754493)
  - [ ] Organization `2i2c.org`s [engineering group](https://console.cloud.google.com/iam-admin/groups/01opuj5n2qnifml?organizationId=184174754493)
  - [ ] Outside-organization project for [`cloudbank`](https://console.cloud.google.com/iam-admin/iam?project=cb-1003-1696)
  - [ ] Outside-organization project for [`meom-ige`](https://console.cloud.google.com/iam-admin/iam?project=meom-ige-cnrs)
  - [ ] Outside-organization project for [`callysto`](https://console.cloud.google.com/iam-admin/iam?project=callysto-202316)
  - [ ] (optional) Outside-organization project for [`pangeo-hubs`](https://console.cloud.google.com/iam-admin/iam?project=columbia)
    - An agreement has to be signed first, and they require a copy of our passports, see https://github.com/2i2c-org/meta/issues/247

- [ ] Add to appropriate AWS projects
  - [ ] Management account [`2i2c-sandbox`](https://2i2c.awsapps.com/start/#/) (Grants SSO access at https://2i2c.awsapps.com/start#/)
  - [ ] Outside-SSO account [`carbonplan`](https://631969445205.signin.aws.amazon.com/console)
  - [ ] Outside-SSO account [`openscapes`](https://783616723547.signin.aws.amazon.com/console)
  - [ ] Outside-SSO account [`nasa-veda`](https://smce-veda.signin.aws.amazon.com/console)
    - An agreement has to be signed first, see https://github.com/2i2c-org/leads/issues/104
- [ ] Add to appropriate Azure projects
  - [ ] Outside-organization subscription for `utoronto` see https://github.com/2i2c-org/team-compass/issues/386
- [x] Add to [quay.io 2i2c team](https://quay.io/organization/2i2c/teams/owners)
- [ ] NameCheap administration privileges to `2i2c.org` and `2i2c.cloud`

**Roles**

- [ ] ~~Onboard into the [Support Steward Role](https://github.com/2i2c-org/team-compass/issues/new?assignees=&labels=type%3A+onboard&template=new-team-member.md&title=Onboarding+%3Cname%3E)~~

**External**

- [x] Add to [2i2c website](https://2i2c.org/organization/)
- [ ] Celebrate their arrival on social media! (Twitter, Mastodon, LinkedIn)

**Wrap up**

- [ ] Have a one-on-one with the new team member to answer any questions they may have
- [ ] Announce in the `#general` Slack channel about our new team member
- [ ] Celebrate, they are now onboarded! 🎉

**Comment by jmunroe** [comment]
Created a Google Workspace account and invited Jenny to the 2i2c-org GitHub org

**Comment by jmunroe** [comment]
> Get member's [bitwarden account](https://bitwarden.com/)

Looks like to add bitwarden user you invite them by email address, so I don't think "bitwarden account" is needed.

<img width="621" alt="image" src="https://github.com/2i2c-org/team-compass/assets/6181563/8d9d7854-e527-4aac-a5d5-f401e6c9b438">

Invited jwong@2i2c.org to the 2i2c org on Bitwarden

**Comment by jmunroe** [comment]
I don't think this are needed for non-engineering roles:

> Get member's [NameCheap.com account](https://namecheap.com/)
> Get member's [PagerDuty account](https://pagerduty.com/)

**Comment by jmunroe** [comment]
Added to FreshDesk (since there is a lot of historical information there that I believe Jenny will need to access to)

**Comment by jmunroe** [comment]
Looking at the our RTD sites now:

- Hub Service Guide: https://docs.2i2c.org/ [(RTD link)](https://readthedocs.org/projects/2i2c-pilot-documentation/)
- Infrastructure Guide: https://infrastructure.2i2c.org/ [(RTD project link)](https://readthedocs.org/projects/2i2c-pilot-hubs/)
- Team Compass: https://team-compass.2i2c.org/ [(RTD project link)](https://readthedocs.org/projects/2i2c-team-compass/)

I doesn't look like we have been added our whole team to these projects.

@choldgraf -- you appear to have admin access to all of these: could you please add me (jmunroe) as a maintainer so that I can in turn add Jenny?

**Comment by jmunroe** [comment]
All the links to the Team Compass in this GitHub issue template seem broken.

We need to change the prefixes `https://team-compass.2i2c.org/en/latest/` to `https://compass.2i2c.org/` throughout the GH template.

**Comment by choldgraf** [comment]
@jmunroe invites sent to each of those RTD pages!

**Comment by jmunroe** [comment]
RTD invites and quay.io invites down.

**Comment by jmunroe** [comment]
I've added a stub for in https://github.com/2i2c-org/2i2c-org.github.io/pull/189

@jnywong, please add a bio / update the profile image used / set your socials as you like by editing content/authors/jenny-wong on https://github.com/2i2c-org/2i2c-org.github.io

**Comment by jnywong** [comment]
Stub updated and https://github.com/2i2c-org/2i2c-org.github.io/pull/193 opened.

**Comment by jnywong** [comment]
Created [PR](https://github.com/2i2c-org/team-compass/pull/783) to update template issue with a prompt to edit helm chart for 2i2c hubs for the following item:

> - [ ] Add to 2i2c hubs as an admin

**Comment by jnywong** [comment]
Closing this issue as I consider my onboarding is done!
