### ISSUE TITLE
Update team compass URLs in onboarding GH template

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/team-compass#776]
All the links to the Team Compass in this GitHub issue template appear broken.

- [ ] We need to change the prefixes https://team-compass.2i2c.org/en/latest/ to https://compass.2i2c.org/ throughout the GH template.

**Comment by jmunroe** [comment]
Aha!  I see @damianavila already has a open PR for this: https://github.com/2i2c-org/team-compass/pull/772

**Comment by damianavila** [comment]
#772 was merged, so let's close this one now!
