### ISSUE TITLE
Onboarding Giuliano Maciocci

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#796]
- Onboarding champion: @choldgraf with support from @haroldcampbell 
- New person's name: Giuliano Maciocci
- New person's GitHub handle: @Gman0909 

### Onboarding checklist

The **Onboarding champion** should follow the checklist below to onboard a new team member. Don't hesitate to delegate some actions to others (e.g. if another person needs to give access to an account because you aren't able to).

**First steps**

- [x] Send them a welcome e-mail to introduce yourself and mention that you'll be onboarding them.
- [x] Point them to [our onboarding documentation](https://compass.2i2c.org/operations/onboarding/)

**Accounts**

Create new accounts and share their account name:

- [x] Get member's [GitHub.com account](https://github.com)
- [ ] Get member's [ReadTheDocs.org account](https://readthedocs.org)
- [ ] Get member's [Quay.io account](https://quay.io)
- [ ] Get member's [NameCheap.com account](https://namecheap.com)
- [ ] Get member's [PagerDuty account](https://pagerduty.com)
- [x] Get member's [bitwarden account](https://bitwarden.com)
- [ ] Get member's [Zoom account](https://zoom.us)
- [ ] Get member's [Freshdesk account](https://www.freshworks.com)

Create 2i2c accounts and add to team accounts:

- [x] Create a @2i2c.org Google account for them
	- Note that this requires [access to the Admin Panel](https://compass.2i2c.org/administration/google-workspace/), a permission held by any 2i2c team lead
- [x] Add them to the proper Google group in our Google Admin space.
- [x] Add to the proper [2i2c GitHub teams](https://github.com/orgs/2i2c-org/teams/)
- [x] Add to the proper [Slack groups](https://2i2c.slack.com/admin/user_groups)
- [ ] Add to the proper [FreshDesk group](https://2i2c.freshdesk.com/a/admin/groups)
- [ ] Add to propoer [PagerDuty Users group](https://2i2c-org.pagerduty.com/users-new)
- [x] Add to our [bitwarden organization](https://vault.bitwarden.com/#/organizations/11313781-4b83-41a3-9d35-afe200c8e9f1/vault) and add to "Default collection"

**Communication**

- [x] Send them a link to the [2i2c Team Compass](https://compass.2i2c.org/) and its [Team Operations section](https://compass.2i2c.org/operations/)
- [x] Send them a link to the [2i2c calendars and meetings](https://compass.2i2c.org/reference/calendar/)
- [x] Send them a link to the [2i2c Team Google Drive](https://drive.google.com/drive/u/1/folders/0AJcabtB-T0LnUk9PVA)
- [x] Schedule an onboarding meeting for after they've read through the docs

**Documentation**

- [ ] Grant appropriate permissions on [ReadTheDocs projects](https://readthedocs.org/)
  - [ ] https://readthedocs.org/dashboard/2i2c-pilot-hubs/users/
  - [ ] https://readthedocs.org/dashboard/2i2c-team-compass/users/
  - [ ] https://readthedocs.org/dashboard/2i2c-pilot-documentation/users/

**Cloud engineering permissions**

_This is only relevant for others that are joining our Engineering team._

- [ ] Add to 2i2c hubs as an admin and update [`helm-charts/basehub/values.yaml`](https://github.com/2i2c-org/infrastructure/blob/master/helm-charts/basehub/values.yaml)
- [ ] Add to appropriate GCP organizations and projects
  - [ ] Organization `2i2c.org`'s [admin group](https://console.cloud.google.com/iam-admin/groups/03znysh73qbio4n?organizationId=184174754493)
  - [ ] Organization `2i2c.org`s [engineering group](https://console.cloud.google.com/iam-admin/groups/01opuj5n2qnifml?organizationId=184174754493)
  - [ ] Outside-organization project for [`cloudbank`](https://console.cloud.google.com/iam-admin/iam?project=cb-1003-1696)
  - [ ] Outside-organization project for [`meom-ige`](https://console.cloud.google.com/iam-admin/iam?project=meom-ige-cnrs)
  - [ ] Outside-organization project for [`callysto`](https://console.cloud.google.com/iam-admin/iam?project=callysto-202316)
  - [ ] (optional) Outside-organization project for [`pangeo-hubs`](https://console.cloud.google.com/iam-admin/iam?project=columbia)
    - An agreement has to be signed first, and they require a copy of our passports, see https://github.com/2i2c-org/meta/issues/247

- [ ] Add to appropriate AWS projects
  - [ ] Management account [`2i2c-sandbox`](https://2i2c.awsapps.com/start/#/) (Grants SSO access at https://2i2c.awsapps.com/start#/)
  - [ ] Outside-SSO account [`carbonplan`](https://631969445205.signin.aws.amazon.com/console)
  - [ ] Outside-SSO account [`openscapes`](https://783616723547.signin.aws.amazon.com/console)
  - [ ] Outside-SSO account [`nasa-veda`](https://smce-veda.signin.aws.amazon.com/console)
    - An agreement has to be signed first, see https://github.com/2i2c-org/leads/issues/104
- [ ] Add to appropriate Azure projects
  - [ ] Outside-organization subscription for `utoronto` see https://github.com/2i2c-org/team-compass/issues/386
- [ ] Add to [quay.io 2i2c team](https://quay.io/organization/2i2c/teams/owners)
- [ ] NameCheap administration privileges to `2i2c.org` and `2i2c.cloud`

**Roles**

- [ ] Onboard into the [Support Triager Role](https://github.com/2i2c-org/team-compass/issues/new?assignees=&labels=type%3A+onboard&template=new-team-member.md&title=Onboarding+%3Cname%3E)

**External**

- [ ] Add to [2i2c website](https://2i2c.org/organization/)
- [ ] Celebrate their arrival on social media! (Twitter, Mastodon, LinkedIn)

**Wrap up**

- [x] Have a one-on-one with the new team member to answer any questions they may have
- [ ] Announce in the `#general` Slack channel about our new team member
- [ ] Celebrate, they are now onboarded! 🎉

**Comment by Gman0909** [comment]
Just adding my GitHub account here

**Comment by choldgraf** [comment]
Thanks @Gman0909 - I've added you to the @2i2c-org/product team which should give you access to 2i2c's various repositories (including private ones).

@haroldcampbell I'm looking through the list above and noticing something:

A lot of those accounts are engineering-focused and we may want to define different sub-lists for people in different roles. (e.g., I don't think that Giuliano needs a quay.io account). As you're helping with onboarding use your best judgment about what accounts Giuliano needs now, and afterwards perhaps we can update this list with more granularity based on role.

**Comment by sgibson91** [comment]
FYI, there is an issue tracking splitting up the onboarding checklists https://github.com/2i2c-org/team-compass/issues/654

**Comment by jnywong** [comment]
I've invited @Gman0909 to [2i2c-org/Teams/Research-Delight-Team](https://github.com/orgs/2i2c-org/teams/research-delight-team/members) to grant access to the Community Showcase Hub.

**Comment by jmunroe** [comment]
Thanks for solving @Gman0909 access issue in the short term. I think 2i2c team members, my understanding should be granted via

- [ ] Add to 2i2c hubs as an admin and update [helm-charts/basehub/values.yaml](https://github.com/2i2c-org/infrastructure/blob/master/helm-charts/basehub/values.yaml)

(The general issue of how we should access to 2i2c staff is discussed in https://github.com/2i2c-org/infrastructure/issues/3587)

**Comment by choldgraf** [comment]
A few more updates here:

- Created a Product Google Group in Google, and added it under `everyone@2i2c.org`. This should give @Gman0909 access to google calendar etc.
- Created a `@product` Slack group and added @Gman0909 
- Gave @Gman0909 an invite to our BitWarden organization (note @haroldcampbell you still have an outstanding invite)

**Comment by choldgraf** [comment]
let's do it!
