### ISSUE TITLE
Create a privacy policy

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/team-compass#810]
### Context

I am very happy that I can link to our Code of Conduct at [https://compass.2i2c.org/code-of-conduct/](https://compass.2i2c.org/code-of-conduct/) that I have referenced in the [Hub Champion Training](https://czi-catalystproject.github.io/hub-champion-training/)  😍 

For the Report Response Protocol, I can see that there is a link to a Google Doc form. I am also planning to collect feedback data from the Hub Champion Training workshops https://github.com/czi-catalystproject/hub-champion-training/issues/73.

### Proposal

To that end, can we define a Privacy Policy that we can reference upstream in the Team Compass?

**Comment by sgibson91** [comment]
This issue may be related https://github.com/2i2c-org/team-compass/issues/388

**Comment by jnywong** [comment]
Ah thanks for surfacing that! My search-fu skills are in awe of your power.

**Comment by jnywong** [comment]
For the Hub Champion Training, I'll create a one-off policy in similar vein to https://github.com/2i2c-org/team-compass/issues/388#issuecomment-1067314766 to move things forward there in the short term. Closing this duplicate issue.

**Comment by choldgraf** [comment]
Just added an update to that issue that might be relevant to @jnywong 

https://github.com/2i2c-org/team-compass/issues/388#issuecomment-1971284451
