### ISSUE TITLE
Feedback for draft language for initiatives board purpose and structure

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#817]
This is a proposal for how to structure the initiatives board.

**Questions to consider**:

1. Is the description clear? Is it missing anything important?
2. Does anything feel fundamentally wrong or unsafe to try?
3. Please make specific edits by editing this top comment.

### What is the initiatives board?

A place to track strategic initiatives that will make progress towards 2i2c's major goals. It is a zoomed-out view of 2i2c's current and upcoming organization-wide priorities. Almost all strategic work should be driven by an `In progress` initiative.[^strategic-work]

[^strategic-work]: By "strategic work" we mean work that is not reactive or operational in nature.

There are two kinds of things in the initiatives board:

1. Strategic goals
2. Initiatives, which we break down into "Strategic initiatives" and "Project initiatives"

Below is a description of each

### What is a strategic goal?

A high-level goal that defines success for 2i2c. This should be outcome-based, measurable, and directional in nature. _All strategic initiatives should be linked to a goal._

### What are initiatives?

An effort that requires coordination from multiple people or many actions over time. **All non-reactive work should be tied to an initiative.**

- **Strategic initiatives** represent progress made towards a strategic goal. These should all result in value delivered to communities.
- **Project initiatives** represent progress made towards goals defined elsewhere in 2i2c. For example: JupyterHub team development priorities.
- **Investment initiatives** represent a focused investment in our team, technology, etc that does not immediately deliver value to communities, but help us build a better foundation to do so. For example: pay down technical debt, focused team training, etc.

Each initiative has the following structure:

````
title: Initiative name in GitHub issue

### Description

A short description of the initiative, with enough context so that people can understand
what kind of work it will entail, and why it is important to 2i2c's overall goals.

### Linked goal or project

- Link to a strategic goal or a project (2i2c-based, upstream, etc)

### Why is this important?

- This will allow us to XXX

### Measures and definition of done

- We expect to see XXX
- This will be complete when YYY

```[tasklist]
- [ ] A growing list of tasks and actions used to coordinate work around this initiative.
- [ ] Each should be an actionable issue that we track independently.
- [ ] This may be empty when the initiative is created! The initiative's goals should be used to decide what action issues to create next.
```
````

Each initiative defines the following metadata:

- **Status**: `Committed`, `In progress`, `Review`, `Waiting / Blocked`, `Done`
- **Checkpoint**: A date when we will assess the measure defined in the initiative (if in `In progress`)
- **Functional area**: The area that is responsible for driving forward the initiative [^responsibility]
- **Primary responsible individual**: The person **assigned to the initiative issue** is responsible for ensuring the work happens.

[^responsibility]: This doesn't mean this area must do all of the work, but they are responsible for making sure the work gets done.

### How initiatives are created

An initiative may be added to the board when the following criteria are met:

- There's a tracking issue that follows the structure above.
- The `#initiatives` team is made aware of the issue and there are no objections.
- The initiative has beend added to the `Committed` column.

Initiatives move into the `In progress` columns via discussion in the bi-weekly initiatives planning meeting.

> **Note** Limit initiatives in progress
>
> We should strive to limit the number of initiatives that are `In Progress`. The more initiatives we have going at once, the harder it will be to complete any one of them, and the slower we'll deliver value to our communities. We should have a small enough number of initiatives In Progress that we can discuss each one of them in a 1-hour planning meeting.

### The initiatives team

The initiatives team is a cross-functional team comprised of representatives from each of 2i2c's functional areas. The goal of this team is to collaborate to further 2i2c's goals and unblock one another, share information across our team, and represent their area's interests and perspectives.

### Bi-weekly initiatives meetings

There are two bi-weekly[^biweekly] meetings with the initiatives team.

[^biweekly]: We might make this less-frequent at some point, but let's start with bi-weekly so we have a chance to iterate and learn more quickly.

- Initiative planning and refinement: This meeting has two phases:
	1. Coordination. Walk the board. Discuss the current state of `In progress` initiatives. Ensure each one has clear next steps, assigned people, and that any coordination between teams is clear. **This happens before each sub-team planning meeting**.
	2. Prioritization: Zoom out. Do we have the right initiatives in general? Is it clear which initiative we'll start next once we finish our current initiatives? Is there any refinement work that must happen for `Next` initiatives? **These happen after each sub-team retrospective**.
- Initiative retrospectives: The same retrospective structure we follow for sub-teams, but with the `#initiative` team. 

### How initiatives relate to our other boards

All non-reactive work on any delivery/sprint boards should be tied to an initiative.

When an initiative is created, we include a [tasklist] that will become populated with issues that we track in delivery/sprint boards. As new tasks are identified (on the fly or in initiatives planning meetings) we add them to the initiatives board.

### How do initiatives relate to team workflows

- In a sprint planning session, if it's not clear what work to commit next, look to the initiatives board and see if there's an actionable task in an `In progress` initiative, and add it to the next sprint board.
- If there are no actionable "next tasks" in an initiative, work with team members to identify a next step that will move the initiative forward.
- In general, if you are not sure what to do and don't have clarity from a sprint board, look to the `In progress` initiatives and think of something that will move one of them forward.

### Relationship with the `#solution-forum`

The `#solution-forum` channel will be re-branded to the `#initiatives` channel, and will be a place to have ephemeral and quick conversation around our initiatives.

The initiatives board is the source of truth for our strategic initiatives, and any important ideas or plans that happen in the `#initiatives` channel should be encoded as updates to the issues on the initiatives board.

**Comment by choldgraf** [comment]
I'm assigning folks that were in the `#solution-forum` team meeting today to review and provide feedback on the role of the "initiatives" board. I'll move this forward early next week if there are no objections. Ideally we can get feedback from at least 1-3 team members.

**Comment by Gman0909** [comment]
This all makes perfect sense to me, although I can see scenarios where we might want to add a new initiative to the board _before_ any tasks are defined as linked issues.

**Comment by choldgraf** [comment]
@Gman0909 good point, I'll clarify that the linked issues will likely be sparse (or empty) to begin. The important thing is that we use the goals of the initiative to "drive" the creation of new actionable issues and track them in the initiative over time.

**Comment by damianavila** [comment]
@choldgraf, you have defined

> Status: Later, next, now, done

But then I see some reference to an `In progress` state, am I missing something?

**Comment by damianavila** [comment]
> Relationship with the #solution-forum
>The #solution-forum channel will be re-branded to the #initiatives channel, and will be a place to have ephemeral and quick conversation around our initiatives.

I concur with this definition and I think any discussion about the "solution forum" should be handled/discussed here as well because I see that space as a conpanion of the Initiatives board. Wondering how others (in addition to Chris and myself) think about this one? Further thoughts?

>The initiatives board is the source of truth for our strategic initiatives, and any important ideas or plans that happen in the #initiatives channel should be encoded as updates to the issues on the initiatives board.

I also agree with this "mandate". It is easy to start long conversation in Slack (our current place for the "solution forum" and most? of the time those conversations are not later reflected in a more permanent record such as an Initiatives issue.

**Comment by choldgraf** [comment]
A few quick updates:

- I've added clearer language about the initiatives and the work that we do on a regular basis in delivery.
- I've updated the status of initiatives to match what we use in sprints (cc @damianavila does that look right?).
- I've clarified the initiatives meeting process to try and make it clearer how the planning meeting relates to the initiatives board.
- I've added a note about "work in progress" limits for initiatives.

cc @damianavila @aprilmj @haroldcampbell and @Gman0909 who have comments I addressed or changes that relate to previous conversations we've had

**Comment by jmunroe** [comment]
Can an initiative be fully specified but not yet committed?  I think this is an important state for an initiative.  

That may be what is described by the word 'committed' in that above description. But the word 'committed' in other project boards has the meaning of being included in the upcoming iteration.

The 'planning' step in an iteration should be intentional about which initiatives 2i2c takes on.  We should avoid is committing to an initiative for which there there is no capacity take it on.

I'd also be careful about turning a planning meeting turning into a 'status update' meeting. My hope the is the board should be sufficient for work in process. But I do like the idea of biweekly planning meetings -- that allows initiatives to be reprioritized as needed.

**Comment by choldgraf** [comment]
Good points @jmunroe - quick responses and I'll do it in separate comments in case folks want to just "react" to one or the other...

> Can an initiative be fully specified but not yet committed? I think this is an important state for an initiative.

Good point, I agree this is an important status update and something that I missed when re-using the terms from the sprint boards. Can we define an initiative status like `Needs refinement`, and use it as a place to put initiatives that we're interested in but need to develop further before we decide whether we want to commit to them? I believe that this status _implicitly_ exists for deliverables/tasks as well, but it just doesn't exist in our Sprint boards which is why that status isn't visible there.

**Comment by choldgraf** [comment]
> I'd also be careful about turning a planning meeting turning into a 'status update' meeting. My hope the is the board should be sufficient for work in process. But I do like the idea of biweekly planning meetings -- that allows initiatives to be reprioritized as needed

Agreed. The planning meeting should be about actively unblocking or clarifying work that needs to be done. It is a "coordination step" to ensure that we have alignment across our team about the most important next actions to take. On this one, perhaps we can use "is this meeting turning into a status update meeting?" as an indicator for whether it's successful after 1-3 months. I'd also ask @haroldcampbell to recommend how to properly "walk the initiatives board" to avoid this outcome.

**Comment by Gman0909** [comment]
Just chipping in to say I agree with the overall direction of travel here, both with the need for an uncommitted state and the avoidance of pure status updates for the planning meeting.

**Comment by choldgraf** [comment]
OK thanks all for this feedback! I think at this point it would be most helpful to converge on some language that we can start with. I wrote up a short PR at the link below and will use that for discussion from here on:

- https://github.com/2i2c-org/team-compass/pull/821
