### ISSUE TITLE
Define a system for managing our blog and its content

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#823]
### Description

We have a blog at 2i2c.org/blog . It contains a collection of "notable updates" (some short, some long) from 2i2c to the external world. It is the primary way for us to communicate our actions and progress in a "long-form" style of writing.

Historically, @choldgraf has written most of the content there. In addition, we have had many (reference list at the bottom for example) examples of "this would be great as a blog post" issues that get lost because there is no process for turning an idea for a blog post into action.

We should improve this system so that there's more clarity and reliability in posting content to our blog.

### Linked goal or project

This goal is not yet created, but I think it feeds into an organizational goal of improving the efficiency of our organizational delivery and operations. Given that communication is an important part of our organization's lifecycle, tightening up processes around communication will reduce friction and coordination burden.

### Why is this important?

Because our blog is the primary way that we communicate with the outside world, it's important that we have a system for regularly pushing content. This boosts our visibility, gives us a chance to own our own narrative, provides transparency to our external stakeholders, and gives a useful "notable events" trail of posts for when we need to put together reports.

### Measures and definition of done

We should have a system that reliably posts content on 2i2c's blog. It needs to define the roles, responsible parties, and processes to follow so that there's clarity on the "next step" when there's something worth posting publicly.

```[tasklist]
- [ ] A growing list of tasks and actions used to coordinate work around this initiative.
- [ ] Each should be an actionable issue that we track independently.
- [ ] This may be empty when the initiative is created! The initiative's goals should be used to decide what action issues to create next.
```

### Examples of dangling issues on the blog

- https://github.com/2i2c-org/team-compass/issues/825
- https://github.com/2i2c-org/team-compass/issues/824
- https://github.com/2i2c-org/meta/issues/933
- https://github.com/2i2c-org/infrastructure/issues/3107
- https://github.com/2i2c-org/team-compass/issues/244
- https://github.com/2i2c-org/team-compass/issues/31
- https://github.com/2i2c-org/team-compass/issues/717
- https://github.com/2i2c-org/infrastructure/issues/3543
- https://github.com/2i2c-org/team-compass/issues/30
- https://github.com/2i2c-org/team-compass/issues/331
- https://github.com/2i2c-org/team-compass/issues/141
- https://github.com/2i2c-org/team-compass/issues/101
- https://github.com/2i2c-org/team-compass/issues/366
- https://github.com/2i2c-org/upstream/issues/35

**Comment by aprilmj** [comment]
This initiative looks like it's largely been replaced by work @jnywong did to organize the blog posts and boost them via social media. Can we close it?

**Comment by choldgraf** [comment]
@jnywong could you take a look at the [dangling issues list at the top](https://github.com/2i2c-org/team-compass/issues/823#issue-2198607371), add any that seems worthy to the upcoming blog posts table, and close all those issues?

**Comment by jnywong** [comment]
Hey yep! Just saw this comment, I'll make sure all of your precious work above does not get lost in the system 👍
