### ISSUE TITLE
Rework the Partnerships Board to be the Operations Board

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#826]
We need to re-work the Partnerships board in order to re-purpose it for organization-wide operations instead of just Partnerships. A few things this probably needs to address:

- How can we avoid the board being too cluttered or hard to find things?
- How should we change the processes around the board to accommodate this larger group?
- How should we plan the Operations board retrospective and sprint planning meetings?

**Comment by jmunroe** [comment]
I'll defer to @haroldcampbell 's guidance here, but I'd been keen to involved in the organization/management of the Operations Board as an evolution of the Partnerships board.

I think our recent efforts on partnerships have gained some practice and experience in running retrospectives and iteration planning that should be directly applicable.

**Comment by choldgraf** [comment]
My suggestion is that @jmunroe gives a shot at making the changes that seem sensible, and tags in @haroldcampbell when needed throughout the process for guidance.

I feel like our first step should be to get that board in an MVP state that is usable by the organization as a whole rather than just Partnerships.

Assuming that's an OK plan, I'm going to add @jmunroe and @haroldcampbell to this issue, but happy to go with a different plan if you two prefer something different. If you're already at capacity with your current sprint workload, I can also give a shot at doing this. Just let me know what you'd prefer to do there!

**Comment by jmunroe** [comment]
I am ok taking this on (it is effectively a redefinition of the work I was already doing within partnerships so in not in conflict with other items in my current iteration)

My intent is to set up a new clean, new board called 'Operations'. I'll do the initial pass of setting up the views/fields and then tag @haroldcampbell for review.

**Comment by choldgraf** [comment]
Any objections for others to begin using this board as soon as it is set up, even though it might change here and there per feedback from @haroldcampbell or others?

**Comment by aprilmj** [comment]
No objections here. I'd love to start using this board (knowing that things I've been working on are all over the place & probably need some cleanup as we work).

**Comment by jmunroe** [comment]
Operation Board: https://github.com/orgs/2i2c-org/projects/50

I fine with tasks and epics being added to this board now -- that is really helpful with setting up which views are useful. The fields associated with the board may continue to evolve but I won't remove any cards that someone else adds.

There are several fields we could define but here are the ones I am starting with:

1. **status**: uncommitted, iteration backlog, in-progress, done, waiting/blocked

2. **iteration**: A particular two-week timebox that a task is scheduled for

3. **initiative:**: link back to the 'initiative' that is associated with this epic/task

**Comment by jmunroe** [comment]
Yes. I just noticed that setting and I agree. (is `tracked by` a newer feature? I wonder why I didn't use it earlier)

**Comment by jmunroe** [comment]
I tried out the 'tracked by' feature as a way of organizing tasks.  I don't think this works well since some tasks are part of epics or are dependencies of other issues. I feel that group by 'initiative' where initiative is defined by a field is more explicit way of visualizing epics and tasks in this board.

**Comment by choldgraf** [comment]
I'm going to take a look at the Operations Board today and try to move over the items I'm working on actively now. For now I'm going to put them in the "committed" column if they are actively driving my work. Once we start adopting an iteration process around this I can move them as needed, but I thought for now it'd be more useful to use this to signal where my time is going.

One thing I felt: adding an item with a new initiative feels like a lot of "toil" steps. If the initiative doesn't yet exist, then you need to:

1. Add the item
2. Go into "settings" -> click on the "Initiative" field settings
3. Copy/paste the title of the initiative there.
4. Click edit, go to description, copy paste the URL of the initiative there.

It also means that single-select is going to be a *huge* list fairly quickly, as new initiatives drive the actions on this board.

I don't know what a better solution would be (I agree that if we do "tracked by" and there are many different issues tracking the tasks here, then it'll also be confusing). Just wanted to share my experience though in case it resonated with others.

**Comment by choldgraf** [comment]
OK - I'm just going to focus on getting the issues on the board in that case 👍

**Comment by choldgraf** [comment]
I've added the tactical issues that I'm involved with to the operations board. A few quick questions:

### Could we stop grouping by initiative?

I found that grouping by initiative makes it hard to identify what we have in-flight, because you've got to scroll through a bunch of negative space before you find something. Instead, I think we could use the "initiative select" menu to the left and/or show the metadata field for initiatives within each card, rather than grouping by them.

For an example, here's a GIF of the current behavior (w/ long scrolling) and what I'm suggesting:

![Image](https://github.com/2i2c-org/team-compass/assets/1839645/ff534a35-3092-489f-9191-38914ee1f567)

### Could we move `Under review` to be before `Done`?

I don't have strong opinions about this, but usually when I've done Kanban the "needs review" column goes first, and Done is to the right of it, mimicking the "flow" of work from left to right. On my small laptop screen, I didn't notice that the "needs review" column was there because it was off-screen and I had seen the "done" already so assumed there was nothing beyond it.

**Comment by jmunroe** [comment]
I agree with both of @choldgraf suggestions:
- Could we stop grouping by initiative? - Yes
- Could we move Under review to be before Done? - Yes

I've made those changes.

**Comment by jmunroe** [comment]
What else is required marked this issue as resolved?

The current proposal is a first iteration of this board to start April 11.  I can see we will need to iterate on on the iterations but until we try and use the board, I don't have any specific actions to take regarding the board itself.

**Comment by choldgraf** [comment]
Two quick thoughts on this:

1. I feel like you and @haroldcampbell should drive the answer to that question, since it wasn't specified to begin with and you're both leading the effort.
2. Based on what you've said, I could imagine the following definition of done:
   
   "The Operations board now reflects the in-flight work across all non-engineering parts of 2i2c, and has the structure needed to take the first iteration of 'operations sprint planning'".

I think that refining/improving the operations board will be done in the coming weeks but doesn't need to be part of this issue.

**Comment by choldgraf** [comment]
Just noting that it looks like the Partnerships board is still in-use, so I'm confused about what should go there vs. the Operations board. Can @jmunroe clarify?

[Partnerships Board](https://github.com/orgs/2i2c-org/projects/47)
[Operations Board](https://github.com/orgs/2i2c-org/projects/50)

**Comment by jmunroe** [comment]
Please use the Operations board.

Partnerships is currently finishing our iteration and will transition fully to Operation once we start the first Operations iteration.

**Comment by jmunroe** [comment]
I'm closing this issue as I think the Operations board is in a usable state.

**Comment by choldgraf** [comment]
Nice - many thanks @jmunroe for all the work to convert the board over.
