### ISSUE TITLE
Document our `org-ops/` repository

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#87]
# Background

We have an [org ops repository](https://github.com/2i2c-org/org-ops) that contains information about cloud access, projects, and credentials. However, it isn't documented anywhere in our team compass (I think?). We should document it so that others understand the context behind this repository, when to use it, and what information to put in it.

I'd imagine we'd either add it to the [general "where information is located" category](https://team-compass.2i2c.org/en/latest/practices/info-location.html) or the one [specifically for the `pilot-hubs` repo](https://team-compass.2i2c.org/en/latest/managed-hubs/about.html#where-is-information-located) (though I think this repository is bigger than just pilot hubs, right?

@yuvipanda could you do this since I believe you're the one that created this repository and has a vision for it?

**Comment by yuvipanda** [comment]
Let's kill it - https://github.com/2i2c-org/org-ops/issues/4

**Comment by yuvipanda** [comment]
TODO:

- [ ] Update our access control docs to remove references to org-ops repo
- [ ] Figure out where our terraform state will be stored, and how it will be managed
- [ ] Archive the repository (or make a 2i2c-attic org and move it there)

**Comment by yuvipanda** [comment]
Closing in favor of https://github.com/2i2c-org/org-ops/issues/4
