### ISSUE TITLE
Review how Engineering backlog items are prioritized

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/team-compass#879]
The current process to prioritise Engineering backlog items needs to be reviewed. The current sub-process [How to prioritize backlog items](https://compass.2i2c.org/engineering/workflow/default-workflow/#how-to-prioritize-backlog-items) doesn't adequately cover work coming from grants nor does it effectively reflect the use of the allocation buckets that we've been using in engineering.

This needs to be a conversation that includes feedback from Engineer, Partnership and Community Success and Product.

## Measures of Success
1. We have an update source of truth, capture in the team compass that describes how work items are ranked (sequence and prioritized) for the engineering team.
2. @Gman0909, @jmunroe, @yuvipanda or @damianavila any other things to add?

**Comment by yuvipanda** [comment]
In practice, I think for the last few months, the priority ordering has been:

1. New Hub requests
2. Anything else with a deadline
3. Partnerships support (although this is primarily managed via the `#sync-partnerships-support-requests` channel now)
4. Product Dev 
5. Anything in Tech support (although this is also primarily managed via engineers reserving upto 30min of their time every day for support tasks, and me asking for this in `#support-freshdesk`)
6. Internal Engineering

Within these, the defacto prioritizer has been me - i've been ordering and sequencing tasks, based on my understanding of priorities from product and partnerships.

**Comment by damianavila** [comment]
Cross-referencing here the previous discussed allocation: https://github.com/2i2c-org/meta/issues/870#issuecomment-1972341260.

@yuvipanda, do you feel the percentages in the cross-referenced message are well represented in your above description? Alternatively, what would be the percentages for the list in your above prio-ordered list?

My impression goes toward most of the "board" capacity being deployed between Product Dev and Internal Engineering (I concur with you that 3 and 5 are now handled outside the board even when sometimes they might have associated github issues).

> Within these, the defacto prioritizer has been me - i've been ordering and sequencing tasks, based on my understanding of priorities from product and partnerships.

I think this is problem (we are creating a new SPoF), and I would advocate to have Product and Partnership representation in the prioritization meeting so you are not the defacto prioritizer.
