### ISSUE TITLE
Share knowledge on *why* the engineering team uses story points

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#883]
The engineering team may have fallen into some of the (anti-)patterns described in https://github.com/2i2c-org/team-compass/issues/882 because the context of _why_ we use story points is missing from our collective understanding. The team should learn more about story points in order to reflect more effectively on our practices regarding them.

### Definition of Done

- [x] Find some articles on story points that particularly discuss motivation for using them and distribute to the team
- [ ] The team reads these articles over the course of the iteration

### Articles advocating the value of Story Points

- [ ] [Story Point](https://martinfowler.com/bliki/StoryPoint.html) - A short 1-pager from Martin Fowler introducing the what/why of Story Points
- [ ] [All about the Point](https://www.thoughtworks.com/en-ca/insights/blog/all-about-point) - A gentle introduction to story points.
- [ ] [Why do we use Story Points for Estimating?](https://www.scrum.org/resources/blog/why-do-we-use-story-points-estimating) - A perspective overview from the SCRUM perspective of "why" Story Points are used by teams.
- [ ] [Agile Story Points: Measure Effort Like a Pro](https://www.easyagile.com/blog/agile-story-points/) - A discussion of Story Points in relation to Sprint Velocity and tools such as [Burndown charts](https://www.projectmanager.com/blog/burndown-chart-what-is-it)
- [ ] [What Are Agile Story Points?](https://www.mountaingoatsoftware.com/blog/what-are-story-points) - VIDEO by Mike Cohn
- [ ] [How to turn user story estimates from a burden to an asset for your team](https://www.thoughtworks.com/insights/blog/agile-project-management/how-to-turn-user-story-estimates-from-a-burden-to-an-asset-for-your-team) - Has some useful discussion related to improving teams' performance

### Articles highlighting the challenges related to Story Points
- [ ] [Can You Stop Using Story Points?](https://medium.com/hackernoon/can-you-stop-using-story-points-ac36449ffa10) - At some point we will mature beyond story points. This article helps to understand the challenges of story points.
- [ ] [Standard Story Points](https://martinfowler.com/bliki/StandardStoryPoints.html) - A short article about why we don't use standard points for or across teams.

### Read by?
Please indicate that you have read the articles by checking the checkbox. We can move the card to done when everyone has read the articles.
- [x] @sgibson91 
- [x] @GeorgianaElena 
- [x] @consideRatio 
- [x] @damianavila 
- [ ] @yuvipanda 
- [x] @haroldcampbell

**Comment by haroldcampbell** [comment]
I've added a list of articles and a video for the team.

**Comment by yuvipanda** [comment]
i read 3 of the links but i don't think i currently have time to do more :( Let's not block this on me. I love story points!

**Comment by sgibson91** [comment]
> I love story points!

Just FYI, the context is not to move away from story points, it's whether we are using them correctly and if we want to change some of the practices outlined here: https://compass.2i2c.org/engineering/workflow/task-sizing/#retroactively-assigning-or-modifying-story-points
