### ISSUE TITLE
[Self-paced learning] K8s fundamentals course

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#898]
- Sarah spends between 2 and 3 days working through the course material
- Sarah posts learning reflections to close this issue

**Comment by sgibson91** [comment]
The completion of this task marks the completion of the course! 🎉 https://www.credly.com/badges/5fcebe78-bcac-4f73-bd46-692782142e15/public_url

**Comment by aprilmj** [comment]
Congratulations Sarah! 🎓🚀
