### ISSUE TITLE
Write up a definition of unplanned work

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/team-compass#904]
### Context

In order to understand and observe when unplanned work is happening, we need to write down a definition of unplanned work. We have been implicitly working with the following definition:

> Unplanned work is any item worked on during an iteration that was not explicitly committed to, by means of being added to the Committed column of the Engineering board, during the Iteration Planning meeting.

We should write this up and add it to the Engineering section of the Team Compass as a reference, even if we intend to tweak it in the future.

### Out of Scope

Debating this definition as it currently stands is **_out of scope for this particular issue_** but can be considered for future work.

### Definition of Done

- [ ] The above definition of unplanned work is added to the Engineering section of the Team Compass

**Comment by haroldcampbell** [comment]
I've added the definition to https://github.com/2i2c-org/team-compass/blob/main/engineering/workflow/task-sizing.md#unplanned-work. I'll mark this as done once I've gotten some feedback from either @sgibson91 or @GeorgianaElena that it meets their expectation from the Retro action.

**Comment by GeorgianaElena** [comment]
That's perfect @haroldcampbell, thank you!
