### ISSUE TITLE
Create a set of standard Issue Labels to use across our repositories

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/team-compass#92]
# Background

Now that we have some team coordination and a workflow defined via [the activity board](https://github.com/orgs/2i2c-org/projects/5?fullscreen=true) it'll be more important that we provide proper categorization / metadata for the labels we use in these issues. We should define a minimal set of labels to use across all repositories, so that we can standardize their use and meaning.

Here are a few topics that we might want to track:

- Issue priority (`prio: low`, `prio: med`, `prio: high`) with increasing "red" colors
- Issue type (`type: enhancement`, `type: bug`, `type: documentation` etc)
- Issue state (e.g., "needs info", "needs upstream", "wont fix")
- Issue tags (`🏷 some tag`) - the tags shouldn't need to be standardized across repos, but the structure should be

# Steps to complete this goal

- [ ] Propose a set of tags via a PR to the team compass
- [ ] Get team feedback on this and converge on a solution
- [ ] Make a PR to add these to our `.github/` repository
- [ ] Do a one-time update to *add* all of these labels to our repositories

**Comment by damianavila** [comment]
Just a quick first thought... let's start with a dozen of tags at maximum, then you can add more as needed.
If you start with a full specification, usually people get confused and they do not know which ones they should be using.

**Comment by choldgraf** [comment]
Ah I missed this comment! See https://github.com/2i2c-org/team-compass/pull/94 for a first proposal and we can iterate there?

I was thinking that we don't get super opinionated about which tags are in each repository, and let those grow more organically. The most important ones to standardize I think are `priority` and `type` (and I am on the fence about `state` 😆)

**Comment by damianavila** [comment]
> Ah I missed this comment! See #94 for a first proposal and we can iterate there?

Sure, I have already left a comment there...

> I was thinking that we don't get super opinionated about which tags are in each repository, and let those grow more organically.

I agree with that!

> The most important ones to standardize I think are priority and type (and I am on the fence about state 😆)

Yep about `type` and `prio`. I like `state` as well.
I think the key thing here is to try to come up with a set of labels adding **new** information on top of the info you get from the boards.
